### ISSUE TITLE
ClassNotFoundException when running quickstart-mp with mvn exec:java

### ISSUE THREAD

**Issue by vinodpahuja** [helidon-io/helidon#1349]
## Environment Details
* Helidon Version: 1.4.1
* Helidon MP
* JDK version: openjdk version "1.8.0_232"
* OS: Window 10

----------

## Problem Description
Can't load log handler "io.helidon.common.HelidonConsoleHandler"
java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
java.lang.ClassNotFoundException: io.helidon.common.HelidonConsoleHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.util.logging.LogManager$5.run(LogManager.java:965)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
        at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
        at java.util.logging.LogManager.access$1500(LogManager.java:145)
        at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
        at java.util.logging.Logger.getHandlers(Logger.java:1777)
        at java.util.logging.Logger.log(Logger.java:735)
        at org.jboss.logging.JDKLogger.doLog(JDKLogger.java:44)
        at org.jboss.logging.Logger.logv(Logger.java:2240)
        at org.jboss.weld.logging.VersionLogger_$logger.version(VersionLogger_$logger.java:24)
        at org.jboss.weld.bootstrap.WeldStartup.<clinit>(WeldStartup.java:149)
        at org.jboss.weld.bootstrap.WeldBootstrap.<init>(WeldBootstrap.java:56)
        at org.jboss.weld.environment.se.Weld.initialize(Weld.java:776)
        at io.helidon.microprofile.server.Server$Builder.createContainer(Server.java:333)
        at io.helidon.microprofile.server.Server$Builder.lambda$doBuild$0(Server.java:236)
        at java.util.Optional.orElseGet(Optional.java:267)
        at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:234)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
        at io.helidon.microprofile.server.Server$Builder.build(Server.java:209)
        at io.helidon.microprofile.server.Server.create(Server.java:95)
        at io.helidon.examples.quickstart.mp.Main.startServer(Main.java:58)
        at io.helidon.examples.quickstart.mp.Main.main(Main.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vinodpahuja** [comment]
I believe it has same [origin] (https://github.com/oracle/helidon/issues/1358) and and (fix)(https://github.com/oracle/helidon/issues/1358#issuecomment-583046392)

**Comment by spericas** [comment]
@vinodpahuja Are you using a shaded jar then?

**Comment by vinodpahuja** [comment]
At first it seems due to similar incompatible dependency with beans.xml, but it could be lazy loading of common module. Still looking into it.

**Comment by romain-grecourt** [comment]
This is because exec:java setup the context class loader but LogManager attempts to load the classes from the application/system class loader. This impacts both SE and MP.

There are hacks to update the built-in class-loaders but since exec:java runs in the same JVM as Maven this would require additional configuration from the user

At this point, we are better off providing an equivalent to `exec:java` with the helidon-maven-plugin, something like `helidon:run`.

**Comment by jburgess** [comment]
@romain-grecourt If this is a proposed solution an equivalent `helidon-gradle-plugin` for us _Gradle_ users would be super-helpful.

**Comment by romain-grecourt** [comment]
@jburgess Proper Gradle support is on our radar, it will be added as part of the 2.x releases.

**Comment by spericas** [comment]
Right, I agree with @romain-grecourt Interestingly, `LogManager` sometimes (in some methods) tries other class loaders and other times (like this one) it does not. So why not use `exec:exec` instead and forgo this same process concept?  

Something like,

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${version.plugin.exec}</version>
                <configuration>
                    <executable>java</executable>
                    <arguments>
                        <argument>-classpath</argument>
                        <!-- automatically adds classpath -->
                        <classpath/>
                        <mainClass>${mainClass}</mainClass>
                    </arguments>
                </configuration>
            </plugin>
```

That seems to work for `exec:exec`. Also should work with module paths.
