### ISSUE TITLE
SSE: RS Cancel is propagated to Jersey by exception

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#3154]
This is continuation of SSE part from the issue #2496

Only way how to propagate cancel from BareResponseImpl to JerseyEventSink is by raising IOException during next write.
https://github.com/oracle/helidon/blob/785ce38ca06b268d16e387fb6498aaaa890695cc/webserver/jersey/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java#L317-L319

Current implementation of SSE in Helidon basically lets Jersey convert Reactive Stream to IO stream and Helidon [converts it back](io.helidon.webserver.jersey.ResponseWriter.DataChunkOutputStream) to reactive stream for subscribing to it with [BareResponseImpl](https://github.com/oracle/helidon/blob/1405501b5ddb3678a43d06d3df904ccdda9ad261/webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java)

Also backpressure is propagated by blocking JerseyEventSink.onNext, which forces api user to spend another thread
https://github.com/oracle/helidon/blob/785ce38ca06b268d16e387fb6498aaaa890695cc/webserver/jersey/src/main/java/io/helidon/webserver/jersey/ResponseWriter.java#L174-L177

We should investigate better way of interacting with Jersey's reactive upstream, specifically how to relay cancel and request signals.

**Comment by danielkec** [comment]
Reproducer
```java
@HelidonTest
@Path("/")
public class ReactiveSseTest {
    SubmissionPublisher<String> broadCastPublisher = new SubmissionPublisher<>();

    void init(@Observes @Initialized(ApplicationScoped.class) Object o) {
        Multi.interval(300, TimeUnit.MILLISECONDS, Executors.newSingleThreadScheduledExecutor())
                .forEach(i -> broadCastPublisher.submit("message" + i));
    }

    @Inject
    WebTarget target;

    @Test
    void name() {
        registerClient(5);
        registerClient(Long.MAX_VALUE);
        Single.never().await();
    }

    private void registerClient(long ord) {
        SseEventSource sseEventSource = SseEventSource.target(target.path("sse-reproduce")).build();
        AtomicLong cnt = new AtomicLong();
        sseEventSource.register(inboundSseEvent -> {
            System.out.println("Client " + ord + ": " + inboundSseEvent.readData());
            if (cnt.incrementAndGet() > ord) {
                sseEventSource.close();
            }
        });
        sseEventSource.open();
    }

    @GET
    @Path("sse-reproduce")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void listenToEvents(@Context Flow.Subscriber<String> sink) {
        broadCastPublisher.subscribe(sink);
    }
}
```

Jersey produces:
```java
INFO: Helidon MP 2.3.1-SNAPSHOT features: [CDI, Config, JAX-RS, Server]
Client 5: message1
Client 5: message2
Client 9223372036854775807: message2
Client 9223372036854775807: message3
Client 5: message3
Client 5: message4
Client 9223372036854775807: message4
Client 5: message5
Client 9223372036854775807: message5
Client 5: message6
Client 9223372036854775807: message6
Client 9223372036854775807: message7
Client 9223372036854775807: message8
Client 9223372036854775807: message9
Jun 24, 2021 5:30:39 PM org.glassfish.jersey.media.sse.internal.JerseyEventSink onNext
SEVERE: Processing onNext signal failed.
java.io.IOException: Bad news: the stream has been closed
	at io.helidon.webserver.jersey.ResponseWriter$DataChunkOutputStream.awaitRequest(ResponseWriter.java:318)
	at io.helidon.webserver.jersey.ResponseWriter$DataChunkOutputStream.write(ResponseWriter.java:177)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:185)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:271)
	at org.glassfish.jersey.media.sse.OutboundEventWriter$1.write(OutboundEventWriter.java:127)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:248)
	at org.glassfish.jersey.message.internal.ReaderWriter.writeToAsString(ReaderWriter.java:170)
	at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:107)
	at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:76)
	at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:36)
	at org.glassfish.jersey.media.sse.OutboundEventWriter.writeTo(OutboundEventWriter.java:113)
	at org.glassfish.jersey.media.sse.OutboundEventWriter.writeTo(OutboundEventWriter.java:43)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	at org.glassfish.jersey.server.ChunkedOutput$1.call(ChunkedOutput.java:231)
	at org.glassfish.jersey.server.ChunkedOutput$1.call(ChunkedOutput.java:198)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:219)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:314)
	at org.glassfish.jersey.server.ChunkedOutput.flushQueue(ChunkedOutput.java:198)
	at org.glassfish.jersey.server.ChunkedOutput.write(ChunkedOutput.java:184)
	at org.glassfish.jersey.media.sse.internal.JerseyEventSink.onNext(JerseyEventSink.java:93)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1307)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(SubmissionPublisher.java:1296)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1253)
	at java.base/java.util.concurrent.SubmissionPublisher$ConsumerTask.exec(SubmissionPublisher.java:930)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Client 9223372036854775807: message10
Client 9223372036854775807: message11
```
