### ISSUE TITLE
Webclient proxy class throwing NullPointerException - Proxy.type is null

### ISSUE THREAD

**Issue by anand-osvc** [helidon-io/helidon#3546]
Getting NullPointerException with io.helidon.webclient.Proxy class, when tried perform a rest api call to a site using proxy with helidon WebClient.

## Environment Details
* Helidon Version: 2.3.4
* Helidon SE
* JDK version: 11
* OS: Oracle Linux / Mac Big Sur
* Docker version (if applicable): NA

----------

## Problem Description
I am getting a NullPointerException with helidon webclient proxy handler, when debugged in local machine, I could see that the type variable in Proxy class is null. I am using following environment variables to initialise proxy for WebClient. 

Env variables
---------------
```
CLIENT_PROXY_NO_DASH_PROXY=*****
CLIENT_PROXY_PORT=****
CLIENT_PROXY_HOST=***
```
Code snippet:
--------------
```
Security security = Security.builder().addProvider(HttpBasicAuthProvider.builder().build()).build();
WebClientSecurity securityService = WebClientSecurity.create(security);
WebClient.Builder clientBuilder = WebClient.builder().config(config.get("client").addService(securityService);
WebClient client = clientBuilder.baseUri("*****my-baseurl*******").addMediaSupport(JsonpSupport.create())
                .addHeader(Http.Header.CONTENT_TYPE, “application/json”)
                .build();
return client.method(Http.Method.PATCH).path("******my-path*******")
                .property(HttpBasicAuthProvider.EP_PROPERTY_OUTBOUND_USER, secret.get().value(“username”).get())
                .property(HttpBasicAuthProvider.EP_PROPERTY_OUTBOUND_PASSWORD, secret.get().value(“password”).get())
                .submit(json);
```
=========
Stack Trace
=========
2021.10.13 07:20:15 WARNING io.netty.channel.ChannelInitializer Thread[helidon-client-0,10,main]: Failed to initialize a channel. Closing: [id: 0x3b6727f2]
**java.lang.NullPointerException
	at io.helidon.webclient.Proxy.handler(Proxy.java:335)**
	at io.helidon.webclient.Proxy.handler(Proxy.java:308)
	at io.helidon.webclient.NettyClientInitializer.lambda$initChannel$0(NettyClientInitializer.java:78)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at io.helidon.webclient.NettyClientInitializer.initChannel(NettyClientInitializer.java:78)
	at io.helidon.webclient.NettyClientInitializer.initChannel(NettyClientInitializer.java:53)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021.10.13 07:20:15 SEVERE com.oracle.osvc.helidon.my-package.MyClass Thread[helidon-client-0,10,main]: CX Update failed for Tenant OSVC*************** incident ID 1****. Error message: io.helidon.webclient.WebClientException: https://******system-url************
java.util.concurrent.CompletionException: io.helidon.webclient.WebClientException: https://******system-url************
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$invoke$20(WebClientRequestBuilderImpl.java:605)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1021)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(AbstractChannel.java:1004)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:237)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:265)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.helidon.webclient.WebClientException: https://******system-url************
	... 23 more
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source)

## Steps to reproduce
1) Instantiate a webclient with following env variables.
CLIENT_PROXY_NO_DASH_PROXY, CLIENT_PROXY_PORT, CLIENT_PROXY_HOST
2) Try to initiate a request to url using the given proxy setting using webclient.
3) Above said exception can be produced.

**Comment by spericas** [comment]
Closing this one since PR #3551 is now merge and proposed workaround seems to work.
