### ISSUE TITLE
MicroProfile RestClient dependencies

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4163]
## Environment Details
* Helidon Version: 2.5.0
* Helidon  MP
* JDK version: 11.0.13
----------

## Problem Description

I attempted to write the simplest Java SE application that uses MicroProfile Rest Client.  According to the MicroProfile Rest Client spec, CDI and MicroProfile Config are not required to use MicroProfile Rest Client (if they are present the spec describes how they should be supported). But it appears as though the Helidon implementation requires those.

This might be what is intended. But this makes the client less useful for applications that do not use CDI.  Also, I had to add `jersey-weld2-se` as a dependency which seemed strange to require me to know that.

## Steps to reproduce

Unzip [helidon-restclient-mp.zip](https://github.com/oracle/helidon/files/8585385/helidon-restclient-mp.zip) and see the README.md.

Do `mvn dependency:tree` to see the dependencies.

Examine the `pom.xml` to see the minimal set of dependencies I found that were needed. Try removing `helidon-microprofile-config`. The application will build, but at runtime it fails with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/microprofile/config/ConfigProvider
	at org.glassfish.jersey.microprofile.restclient.RestClientBuilderImpl.<init>(RestClientBuilderImpl.java:110)
	at org.glassfish.jersey.microprofile.restclient.JerseyRestClientBuilderResolver.newBuilder(JerseyRestClientBuilderResolver.java:30)
	at org.eclipse.microprofile.rest.client.RestClientBuilder.newBuilder(RestClientBuilder.java:55)
	at io.helidon.restclient.mp.ClientMain.main(ClientMain.java:14)
```

Try removing `jakarta.enterprise.cdi-api` . The application will fail at runtime with:
```
Exception in thread "main" org.glassfish.jersey.internal.ServiceConfigurationError: org.glassfish.jersey.spi.ComponentProvider: A dependent class, javax/enterprise/inject/spi/Extension, of the class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider implementing the provider interface org.glassfish.jersey.spi.ComponentProvider is not found. The provider implementation is ignored.
	at org.glassfish.jersey.internal.ServiceFinder.fail(ServiceFinder.java:403)
```

Try removing `jersey-weld2-se`. The application fails at runtime with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/glassfish/jersey/ext/cdi1x/internal/CdiUtil
	at org.glassfish.jersey.microprofile.restclient.RestClientBuilderImpl.build(RestClientBuilderImpl.java:207)
	at io.helidon.restclient.mp.ClientMain.main(ClientMain.java:16)
```

**Comment by Verdent** [comment]
I can confirm, that RestClient will not work without MP Config or CDI. The issue is in the RestClient implementation we are using -> Jersey RC implementation. I have prepared removal of the MP Config hard requirement so far and now I have to figure out the CDI requirement removal stuff.
