### ISSUE TITLE
SubscriberPublMsgToMsgRetComplBean intermittent test failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#4323]
Seeing this test fail intermittently in the 3.x pipeline:

```
00:58:01,523 [ERROR] io.helidon.microprofile.messaging.inner.ChannelTest.innerChannelBeanTest(CdiTestCase)[33]  Time elapsed: 0.08 s  <<< FAILURE!
java.lang.AssertionError: 
Result doesn't match at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean.assertValid(SubscriberPublMsgToMsgRetComplBean.java:61)
Expected: is <[TEst2, tESt3, teST1]>
     but: was <[TEst2, tESt3, teST1]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.microprofile.messaging.AssertableTestBean.assertWithOrigin(AssertableTestBean.java:60)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean.assertValid(SubscriberPublMsgToMsgRetComplBean.java:61)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean$Proxy$_$$_WeldClientProxy.assertValid(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.helidon.microprofile.messaging.inner.ChannelTest.innerChannelBeanTest(ChannelTest.java:68)
```

**Comment by barchetta** [comment]
And saw it on 2.x:
```
[INFO] Running io.helidon.microprofile.messaging.inner.ChannelTest
Error:  Tests run: 105, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.279 s <<< FAILURE! - in io.helidon.microprofile.messaging.inner.ChannelTest
Error:  io.helidon.microprofile.messaging.inner.ChannelTest.innerChannelBeanTest(CdiTestCase)[41]  Time elapsed: 0.073 s  <<< FAILURE!
java.lang.AssertionError: 
Result doesn't match at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean.assertValid(SubscriberPublMsgToMsgRetComplBean.java:62)
Expected: is <[TEst2, tESt3, teST1]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.microprofile.messaging.AssertableTestBean.assertWithOrigin(AssertableTestBean.java:60)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean.assertValid(SubscriberPublMsgToMsgRetComplBean.java:62)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToMsgRetComplBean$Proxy$_$$_WeldClientProxy.assertValid(Unknown Source)
```
