### ISSUE TITLE
OIDC authentication fails if used with proxy 

### ISSUE THREAD

**Issue by satya-24** [helidon-io/helidon#4644]
## Environment Details
* Helidon Version: 2.5.1
* Helidon MP
* JDK version: 11
* OS:Linux
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

OIDC identity provider is deployed in a public network.
When connected Helidon MP application behind a corporate proxy, OIDC fails to reach the identity provider, even with proxy configurations.

The problem can be consistently reproduced.

[//]: # "State if the problem is easily reproducible or happens intermittently"

stack trace
```
[trmqa@slc14xtz console]$ java ${JAVA_FLAGS}  -jar target/otmm-console.jar
2022.07.14 21:28:41 INFO io.helidon.common.LogConfig Thread[main,5,main]: Logging at initialization configured using classpath: /logging.properties
2022.07.14 21:28:42 WARNING org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider Thread[main,5,main]: Class class [Ljava.lang.String; has null package
2022.07.14 21:28:42 WARNING org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider Thread[main,5,main]: Class class [Ljava.lang.String; has null package
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.util.concurrent.CompletionException: io.helidon.webclient.WebClientException: http://129.80.8.224:8080/realms/tmmdev/protocol/openid-connect/certs
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158)
	at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$invoke$20(WebClientRequestBuilderImpl.java:605)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: io.helidon.webclient.WebClientException: http://129.80.8.224:8080/realms/tmmdev/protocol/openid-connect/certs
	... 17 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /129.80.8.224:8080
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	... 8 more
```

[//]: # "Include stack traces or command outputs"

## Steps to reproduce

1. Provide OIDC identity configurations of an identity provider in public network.
2. Connect to a VPN/Corporate network that cannot reach public resource without a proxy.
3. Configure proxy settings as below.
4. Run the application

Expectation: The application run without any errors.
Actual: Above reported error is thrown

[//]: # "Step by step instructions to reproduce the problem"

I have used the below configurations. 
Configurations:

```
server:
  static.classpath:
    location: "/WEB"
    context: "/consoleui"

client:
  proxy:
    use-system-selector: false
    host: "www-proxy.us.oracle.com"
    port: 80
    no-proxy: [ "localhost" ,"127.0.0.1", ".oraclecorp.com" , ".docker.oraclecorp.com" ,".us.oracle.com" , ".oci.oraclecorp.com" ]

security:
  config.require-encryption: false
  jersey:
    enabled: true
  providers:
    - oidc:
        proxy-protocol: "http"
        proxy-host: "www-proxy.us.oracle.com"
        proxy-port: 80
```

[//]: # "Provide sample code/application if relevant"

**Comment by klustria** [comment]
I'm getting this error:

```
Exception in thread "main" io.helidon.common.Errors$ErrorMessagesException: FATAL: Failed to load metadata: java.util.concurrent.CompletionException: io.helidon.webclient.WebClientException: Request failed with code 404 from https://150.136.243.50:8877/realms/helidon-course/.well-known/openid-configuration at java.util.concurrent.CompletionException: io.helidon.webclient.WebClientException: Request failed with code 404
        at io.helidon.common.Errors.checkValid(Errors.java:183)
 
```

and on keycloak, I'm seeing this problem:

```
2022-09-10 08:00:49,204 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Error response 404: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: https://150.136.243.50:8877https://150.136.243.50:8877/realms/helidon-course/.well-known/openid-configuration
```

**Comment by klustria** [comment]
Using Wireshark I have observed this request and response when using proxy (which fails):
```
GET http://localhost:8877/realms/helidon-course/.well-known/openid-configuration HTTP/1.1
HTTP/1.1 404 Not Found , JavaScript Object Notation (application/json)
```
while without proxy, it looks like this (which succeeds:
```
GET /realms/helidon-course/.well-known/openid-configuration HTTP/1.1 
HTTP/1.1 200 OK , JavaScript Object Notation (application/json)
```
From the  message request, it can be seen that the one with proxy uses absolute URL while the one without uses relative URL. This seems to be similar issue as this: https://github.com/helidon-io/helidon/issues/3577 which was fixed using a flag in this PR: https://github.com/helidon-io/helidon/pull/3614.

**Comment by klustria** [comment]
The behavior looks identical as what was observed in https://github.com/helidon-io/helidon/issues/3577. It was fixed via PR: https://github.com/helidon-io/helidon/pull/3614 using a flag but seems like not ideal for an MP app. The goal is now to investigate why with proxy, absolute URI is used in the PATH (which fails) while without proxy, it uses relative URI (which succeeds).

**Comment by klustria** [comment]
Using curl to send the same request via proxy also works:
```
curl -k -v --http1.1 "http://127.0.0.1:8877/realms/helidon-course/.well-known/openid-configuration"
```
and WireShark showed this request/response result:
```
GET /realms/helidon-course/.well-known/openid-configuration HTTP/1.1
HTTP/1.1 200 OK , JavaScript Object Notation (application/json)
```

**Comment by klustria** [comment]
Bottomline, question is why do we use absolute URI path when using proxy as this causes the recipient to receive the URL with hostname and port duplicated, hence causing a 404:
```
2022-10-25 18:54:32,995 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-0) Error response 404: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://localhost:8877http://localhost:8877/realms/helidon-course/.well-known/openid-configuration

```

**Comment by klustria** [comment]
The use of absolute request URI on Proxy and relative request URI on non-proxy were reported and changed in https://github.com/helidon-io/helidon/issues/2302 and https://github.com/helidon-io/helidon/issues/3438. The relevant information of using absolute URI when there is proxy is mentioned in `5.1.2 Request-URI` of https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html which states the following:
```
The absoluteURI form is REQUIRED when the request is being made to a proxy. The proxy is requested to forward the request or service it from a valid cache, and return the response. Note that the proxy MAY forward the request on to another proxy or directly to the server

specified by the absoluteURI. In order to avoid request loops, a proxy MUST be able to recognize all of its server names, including any aliases, local variations, and the numeric IP address. An example Request-Line would be:

       GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1
To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies.
```

**Comment by klustria** [comment]
The goal now is to see if PR https://github.com/helidon-io/helidon/pull/3614 which uses `relative-uris` config flag to allow forcing of request URIs to use relative path can be used for OIDC config.

**Comment by klustria** [comment]
PR https://github.com/helidon-io/helidon/pull/5267 is the potential fix for this issue. Basically, the goal is to add relative-iris boolean flag in OIDC config to force internal webclient in OIDC to use relative URI if needed.

**Comment by klustria** [comment]
PR https://github.com/helidon-io/helidon/pull/5267 has been reviewed and merged.
