### ISSUE TITLE
HelidonTest doesn't start container properly with `TestInstance.Lifecycle.PER_CLASS`

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#4663]
Reported by @rlubke 

## Environment Details
* Helidon Version: master branch
* Helidon MP
* JDK version: 17.0.1-open
* OS: Ubuntu 18.04.6 LTS

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
```java
@HelidonTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class TestTest {
    @Test
    void name(){
    }
}
```
leads to
```
java.lang.IllegalStateException: Error while instantiating SeContainerInitializer
...
Caused by: java.lang.IllegalStateException: Helidon MUST be started using io.helidon.microprofile.cdi.Main, or through io.helidon.microprofile.server.Server. This is to ensure compatibility with GraalVM native-image. If you want to still use SeContainerInitializer, please configure mp.initializer.allow=true to disable this exception.
	at io.helidon.microprofile.cdi.HelidonContainerInitializer.<init>(HelidonContainerInitializer.java:45)
       ...
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 62 more
```

with `System.setProperty("mp.initializer.allow", "true");`

```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "this.testClass" is null
	at io.helidon.microprofile.tests.junit5.HelidonJunitExtension$AddBeansExtension.registerAddedBeans(HelidonJunitExtension.java:475)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by danielkec** [comment]
`TestInstance.Lifecycle.PER_CLASS` doesn't work together with `@HelidonTest` as test class is actually a CDI singleton bean in HelidonTest

**Comment by danielkec** [comment]
We should consider some way of fall back or better error message

**Comment by tomas-langer** [comment]
`@HelidonTest` works the same way as instance per class. So just removing `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` will solve the problem.
We should add an exception that will provide a good error message explaining what is wrong.
