### ISSUE TITLE
Improve configuration of FT thread pools in SE/MP

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#4935]
There are currently thread pools use by FT SE and others by FT MP. Config can be use to adjust the sizes in MP, but not in SE (at least not with some additional method call). Moreover, the initialization of the SE pools (e.g. Async) is done very early in the startup process (by the Health CDI extension) and is, thus, difficult to intercept without a user-defined CDI extension. 

There should be an easier mechanism to configure all these pools. Additionally, settings the sizes of the MP pools _should_ have an impact on the SE pools as well. The problem was uncovered during support.

**Comment by tjquinno** [comment]
@spericas I saw an (I hope) intermittent failure in a pipeline job with the 2.x change:
```
20:04:04,791 [ERROR] Tests run: 23, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.084 s <<< FAILURE! - in io.helidon.health.HealthSupportTest
20:04:04,791 [ERROR] io.helidon.health.HealthSupportTest.checkLazyFaultToleranceInitialization  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.health.HealthSupportTest.checkLazyFaultToleranceInitialization(HealthSupportTest.java:228)
```

**Comment by tjquinno** [comment]
Follow-up: The tests pass fine for me locally, but JUnit runs them in a different order in the pipeline. I suspect that in the pipeline the earlier-running test triggers the health FT usage so when the new test runs which expects FT not yet set up finds it already initialized and fails.

**Comment by spericas** [comment]
@tjquinno Good point. Let me see how I can fix that.
