### ISSUE TITLE
Intermittent CircuitBreakerTest.testCircuitBreaker

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#4977]
```
java.lang.AssertionError: 

Expected: is <HALF_OPEN>
     but: was <OPEN>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.nima.faulttolerance.CircuitBreakerTest.testCircuitBreaker(CircuitBreakerTest.java:64)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by m0mus** [comment]
This fails very often.
