### ISSUE TITLE
Intermittent TestDbSecrets.testAddDatabase

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#4979]
```
java.util.concurrent.CompletionException: io.helidon.integrations.vault.VaultRestException: 930ff6cd-5c8e-40f4-bcde-592b28f97524: Failed to invoke POST on path database/config/mysql. Status 400 Bad Request. Vault errors [error creating database object: error verifying connection: dial tcp 127.0.0.1:3306: connect: connection refused]
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.helidon.common.reactive.Awaitable.await(Awaitable.java:54)
	at io.helidon.integrations.vault.secrets.database.DbSecretsImpl.configure(DbSecretsImpl.java:46)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at io.helidon.integrations.vault.cdi.DbSecrets$_$$_WeldClientProxy.configure(Unknown Source)
	at io.helidon.tests.integration.vault.mp.TestDbSecrets.testAddDatabase(TestDbSecrets.java:95)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at io.helidon.tests.integration.vault.mp.TestDbSecrets$Proxy$_$$_WeldClientProxy.testAddDatabase(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
```

Most likely application to 2.x and 3.x.

We may need to implement a probe to ensure that the container is ready. However given that we plan on migrating to GitHub actions, this is very low priority.

**Comment by m0mus** [comment]
Disable this test.
