### ISSUE TITLE
Intermittent TestServer.checkMetricsForExecutorService

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#4982]
```
java.lang.AssertionError: 
Completed task count after accessing slow endpoint
Expected: is <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.metrics.TestServer.checkMetricsForExecutorService(TestServer.java:221)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
```

**Comment by tomas-langer** [comment]
It seems there is an inherent race condition in this test - the update of metrics may happen after the response is returned, causing the next request to be "too early" to see the modified metric.
This should be refactored to use some deterministic appraoch

**Comment by tomas-langer** [comment]
For `main` branch, we will disable this test until a solution is found

**Comment by tjquinno** [comment]
Yes, this is the case in at least one other test as well. I am addressing them.

**Comment by danielkec** [comment]
Just failed in 4x on top of the fix commit https://github.com/helidon-io/helidon/commit/ce733cba0a5196fd855f86ab01a1203dae7c30fa

```
[INFO] Running io.helidon.metrics.TestServer
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.559 s <<< FAILURE! - in io.helidon.metrics.TestServer
Error:  io.helidon.metrics.TestServer.checkMetricsForExecutorService  Time elapsed: 1.021 s  <<< FAILURE!
java.lang.AssertionError: 
Completed task count after accessing slow endpoint
Expected: is <1>
     but: was <0>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.metrics.TestServer.lambda$checkMetricsForExecutorService$1(TestServer.java:223)
	at io.helidon.common.testing.junit5.MatcherWithRetry.retry(MatcherWithRetry.java:76)
	at io.helidon.metrics.TestServer.checkMetricsForExecutorService(TestServer.java:207)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by danielkec** [comment]
https://github.com/helidon-io/helidon/pull/5047/files#r987852724

**Comment by tjquinno** [comment]
Re-opening. Daniel had improved on my original retry approach, but retrying is not the right solution here. The test `GreetService` already has a `CountdownLatch` which other tests use but this one did not. I'll submit yet another PR that fixes the test so it correctly uses the latch.
