### ISSUE TITLE
Add null check to MP Server.Builder.config()

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5022]
Make sure we throw NPE early in `io.helidon.microprofile.server.Server.Builder.config(Config)` - both for SE config and MP config
Same in `MpConfigSources.create(Config)`

**Comment by tomas-langer** [comment]
Related to issue reported by customer, where we get a NPE at runtime from internals with the following stack trace:

```
Exception in thread "main" java.lang.NullPointerException
        at io.helidon.config.mp.MpHelidonConfigSource.getValue(MpHelidonConfigSource.java:48)
        at org.eclipse.microprofile.config.spi.ConfigSource.getOrdinal(ConfigSource.java:152)
        at io.helidon.config.mp.MpConfigBuilder$OrdinalSource.findOrdinal(MpConfigBuilder.java:493)
        at io.helidon.config.mp.MpConfigBuilder$OrdinalSource.<init>(MpConfigBuilder.java:484)
        at io.helidon.config.mp.MpConfigBuilder.withSources(MpConfigBuilder.java:202)
        at io.helidon.microprofile.server.Server$Builder.config(Server.java:323)
```
