### ISSUE TITLE
Intermittent TestJBatchEndpoint.runJob

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#5035]
```
org.opentest4j.AssertionFailedError: Job Result string ==> expected: <{"Steps executed":"[step1, step2]","Status":"COMPLETED"}> but was: <{"Steps executed":"[step1]","Status":"STARTED"}>
	at io.helidon.examples.jbatch.TestJBatchEndpoint.runJob(TestJBatchEndpoint.java:59)
```

**Comment by danielkec** [comment]
Got it again on 3.x 
```
org.opentest4j.AssertionFailedError: Job Result string ==> expected: <{"Steps executed":"[step1, step2]","Status":"COMPLETED"}> but was: <{"Steps executed":"[step1]","Status":"STARTED"}>
	at io.helidon.examples.jbatch.TestJBatchEndpoint.runJob(TestJBatchEndpoint.java:59)
```
