### ISSUE TITLE
4.x: AccessLogTest intermittently fails

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5135]
```
[INFO] Running io.helidon.nima.tests.integration.server.accesslog.AccessLogTest
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.78 s <<< FAILURE! - in io.helidon.nima.tests.integration.server.accesslog.AccessLogTest
Error:  io.helidon.nima.tests.integration.server.accesslog.AccessLogTest.testRequestsAndValidateAccessLog  Time elapsed: 0.205 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing ["127.0.0.1 - [03/Dec/2007:10:15:30 +0000] \"GET /access HTTP/1.1\" 200", "127.0.0.1 - [03/Dec/2007:10:15:30 +0000] \"GET /wrong HTTP/1.1\" 404"]
     but: No item matched: "127.0.0.1 - [03/Dec/2007:10:15:30 +0000] \"GET /wrong HTTP/1.1\" 404"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.nima.tests.integration.server.accesslog.AccessLogTest.testRequestsAndValidateAccessLog(AccessLogTest.java:97)
```

**Comment by barchetta** [comment]
The test seems to assume all log records will have been flushed to the file by the time the assert occurs. This seems like a bad assumption as you  have one thread writing to the file and another reading from the file and who knows how much buffering is going on (by java, user land, kernel, etc).

If there was a way to run the assert after the webserver was shutdown that should be more reliable since, presumably, the log file would be closed.
