### ISSUE TITLE
NullPointerException when illegal character is in the URL

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#5173]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.5.x
* Helidon MP

----------

## Problem Description
When a URL request contains invalid characters, the log will show an NPE.

## Steps to reproduce
1. Use the helidon-mp-quickstart app
2. Increase the log level of **io.helidon.webserver.ForwardingHandler** to FINEST 
3. Build and run the app
4. Issue a request with an invalid character (|) in the URL: curl -X  GET "http://localhost:8080/greet?page=overview|"
5. Error/Exception like below will appear in the logs
```
00:59:57.317 level=ERROR [thread=nioEventLoopGroup-3-2] class=i.h.webserver.ForwardingHandler - msg="Error intercepted before request context established. "
java.lang.NullPointerException: null
    at io.helidon.webserver.ForwardingHandler.channelReadHttpContent(ForwardingHandler.java:259)
    at io.helidon.webserver.ForwardingHandler.lambda$channelRead0$5(ForwardingHandler.java:183)
    at io.helidon.webserver.RequestContext.lambda$runInScope$4(RequestContext.java:72)
    at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
    at io.helidon.webserver.RequestContext.runInScope(RequestContext.java:70)
    at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:183)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.jav
```

**Comment by klustria** [comment]
The issue does not seem to have adverse effect on the overall functionality. The issue happens on this line:
```
requestEntityAnalyzed.complete(ChannelFutureListener.CLOSE_ON_FAILURE);
```
where `requestEntityAnalyzed` is not set and hence causing the NPE

**Comment by spericas** [comment]
@klustria We should move the init of that future to before the creation of `BareRequestImpl`.

**Comment by klustria** [comment]
Merged in 2.x hence closing
