### ISSUE TITLE
Review all metrics tests for possible race conditions

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#5345]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP 
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
Santiago saw this intermittent test failure:
```
[INFO] Running io.helidon.integrations.micrometer.cdi.HelloWorldTest
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.517 s <<< FAILURE! - in io.helidon.integrations.micrometer.cdi.HelloWorldTest
Error:  io.helidon.integrations.micrometer.cdi.HelloWorldTest.testSlowTimer  Time elapsed: 6.014 s  <<< FAILURE!
java.lang.AssertionError: 
Slow message timer count
Expected: is <3L>
     but: was <2L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.integrations.micrometer.cdi.HelloWorldTest.testSlowTimer(HelloWorldTest.java:98)
	at io.helidon.integrations.micrometer.cdi.HelloWorldTest$Proxy$_$$_WeldClientProxy.testSlowTimer(Unknown Source)
```
with 4.x. 

It's similar to some other intermittent failures we've seen. The underlying cause is that, for metrics updates which occur after the measured code completes (such as timers), the server updates the values using `response.whenSent`. It's possible, due to thread scheduling, that the server has sent the response to the test client and the test client has checked the metric that it expects to be updated _before_ (due to the async nature of `whenSent`) the server has updated the metric value. The test then reports a failure.

Other metrics tests might have the same potential problem.

This issue represents an overall review of all metrics tests that check a metric value that is updated after the measured code runs.

**Comment by tomas-langer** [comment]
In 4.x I have seen these:
```
Error:  io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test  Time elapsed: 7.516 s  <<< FAILURE!
java.lang.AssertionError: 
Change in count for explicit SimpleTimer
Expected: is <1L>
     but: was <2L>
	at io.helidon.common.testing.junit5.MatcherWithRetry.assertThatWithRetry(MatcherWithRetry.java:64)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test(HelloWorldAsyncResponseTest.java:120)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest$Proxy$_$$_WeldClientProxy.test(Unknown Source)
```

and `HelloWorldTest.testSyntheticTimer()`  failing on wrong HTTP response status (in `HttpURLConnection` as part of the web target request to `helloworld/withArg/Joe` endpoint

**Comment by tomas-langer** [comment]
More details on the last one:
```
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.957 s <<< FAILURE! - in io.helidon.microprofile.metrics.HelloWorldTest
Error:  io.helidon.microprofile.metrics.HelloWorldTest.testSyntheticSimpleTimer  Time elapsed: 0.004 s  <<< ERROR!
jakarta.ws.rs.client.ResponseProcessingException: Failed to convert a response into an exception.
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:974)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:755)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:422)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:318)
	at io.helidon.microprofile.metrics.HelloWorldTest.lambda$testSyntheticSimpleTimer$5(HelloWorldTest.java:191)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at io.helidon.microprofile.metrics.HelloWorldTest.testSyntheticSimpleTimer(HelloWorldTest.java:187)
	at io.helidon.microprofile.metrics.HelloWorldTest.testSyntheticSimpleTimer(HelloWorldTest.java:137)
	at io.helidon.microprofile.metrics.HelloWorldTest$Proxy$_$$_WeldClientProxy.testSyntheticSimpleTimer(Unknown Source)
...
Caused by: java.io.IOException: Invalid Http response
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1703)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:378)

```

**Comment by tjquinno** [comment]
Have you seen the `io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test` failure locally or in the pipelines or both?

With the default settings `assertThatWithRetry` performs up to 10 retries 500 ms apart, for a total of up to 5 seconds. You can set `io.helidon.test.retryCount` and `io.helidon.test.retryDelayMs` to control the behavior. We can certainly increase the default number of retries to something larger. Typically it will not take the max to succeed so it should not cost much to make that change.

The stack trace from Jersey is odd. The endpoint the test invokes is very simple, so I assume the error means Java cannot even read enough of the response to get the status. Not sure how to explain that.

**Comment by tjquinno** [comment]
Actually, the first failure (found 2, expected 1) is also odd. The invoked endpoint and one other have the same `@SimplyTimed` annotation, and therefore update the same `SimpleTimer`, but the test records the simple timer's count before it invokes the endpoint, and after invoking the endpoint is testing to make sure the counter increased by exactly 1. 

What is odd here is that the count has increased by 2. The retry would handle the case where the difference started out as 0 because of timing issues and then eventually became 1 once metrics in the server finished the metrics update. But it's surprising that the metric would have updated twice (not once) during the execution of the test. 

I am looking into how this might happen. Not obvious (yet).
