### ISSUE TITLE
[4.x] - webclient.MutualTlsTest.testNoClientCert intermittently fails

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#5489]
Intermittent:

```
io.helidon.tests.integration.webclient.MutualTlsTest.testNoClientCert  Time elapsed: 0.125 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string containing "Received fatal alert: bad_certificate"
```

**Comment by tomas-langer** [comment]
```
Error:  Failures: 
Error:    MutualTlsTest.testNoClientCert:86 
Expected: a string containing "Received fatal alert: bad_certificate"
     but: was "(client reqID: 13) Connection reset by the host"
```

**Comment by tomas-langer** [comment]
Still failing, have trouble reproducing locally though

**Comment by barchetta** [comment]
Still failing:
```
[INFO] Running io.helidon.tests.integration.webclient.MutualTlsTest
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.527 s <<< FAILURE! - in io.helidon.tests.integration.webclient.MutualTlsTest
Error:  io.helidon.tests.integration.webclient.MutualTlsTest.testNoClientCert  Time elapsed: 0.128 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: a string containing "Received fatal alert: bad_certificate"
     but: was "(client reqID: 9) Connection reset by the host"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.tests.integration.webclient.MutualTlsTest.testNoClientCert(MutualTlsTest.java:86)
```

**Comment by romain-grecourt** [comment]
https://github.com/helidon-io/helidon/actions/runs/5406496548/jobs/9823436827

**Comment by barchetta** [comment]
See also #7229

**Comment by tomas-langer** [comment]
```
Error:    MutualTlsTest.testNoClientCert:91 
Expected: a string containing "Received fatal alert: bad_certificate"
     but: was "java.net.SocketException: Broken pipe"
```

**Comment by tomas-langer** [comment]
If i do a `@RepeatedTest` on the class, I can reproduce even locally (failed 2 times out of 70 invocations)

**Comment by tomas-langer** [comment]
Increased priority as this is failing `main` pipelines too often

**Comment by tomas-langer** [comment]
Closing this issue as it is fixed for now.
I am checking with JDK if the problem we see (e.g. `startHandshake` not failing on client) is expected or not.
