### ISSUE TITLE
ConcurrentModificationException in HttpSignProvider

### ISSUE THREAD

**Issue by janotav** [helidon-io/helidon#5594]
## Environment Details
* Helidon Version: 2.5.4
* Helidon SE
* JDK version: 11
* OS: Linux

----------

## Problem Description

Under load, following exception is encountered in `HttpSignProvider`:

```
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap.computeIfAbsent(HashMap.java:1135) ~[?:?]
	at io.helidon.security.providers.httpsign.HttpSignProvider.lambda$signRequest$9(HttpSignProvider.java:270) ~[helidon-security-providers-http-sign-2.5.4.jar:2.5.4]
	at java.util.Optional.map(Optional.java:265) ~[?:?]
	at io.helidon.security.providers.httpsign.HttpSignProvider.signRequest(HttpSignProvider.java:269) ~[helidon-security-providers-http-sign-2.5.4.jar:2.5.4]
	at io.helidon.security.providers.httpsign.HttpSignProvider.lambda$outboundSecurity$4(HttpSignProvider.java:261) ~[helidon-security-providers-http-sign-2.5.4.jar:2.5.4]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117) ~[helidon-common-context-2.5.4.jar:2.5.4]
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154) ~[helidon-common-context-2.5.4.jar:2.5.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
```

In order to minimize latency of our reverse proxy, we cache/reuse HttpSignProvider across requests. Is that valid?

**Comment by Verdent** [comment]
Fixed
