### ISSUE TITLE
helidon-nima-example, HTTP ERROR 500 Internal server error

### ISSUE THREAD

**Issue by artshell** [helidon-io/helidon#5769]
Run "helidon-nima-example"  and then test with web browser，
Request: http://localhost:8080/parallel?count=10000
Report: "HTTP ERROR 500 Internal server error"

## Environment Details
* Helidon Version: 4.0.0-ALPHA2
* Helidon SE
* JDK version: 19
* OS: MAC OS
* Docker version (if applicable): no

----------

## Problem Code

```java
    private void parallel2(ServerRequest req, ServerResponse res) throws Exception {

        try (var exec = Executors.newVirtualThreadPerTaskExecutor()) {
            // try increment count to 10000
            var count = count(req);
            var responses = new ConcurrentLinkedQueue<String>();
            var latch = new CountDownLatch(count);

            for (int i = 0; i < count; i++) {
                exec.submit(() -> {
                    var result = callRemote(client);
                    if (responses.add(result)) {
                        latch.countDown();
                    }
                });
            }

            latch.await();

            res.send("Combined results: " + responses);
        }
    }
```

## Problem Description
* " Internal server error
io.helidon.common.http.RequestException: 
	at io.helidon.common.http.RequestException$Builder.build(RequestException.java:126)
	at io.helidon.nima.webserver.http.ErrorHandlers.handleError(ErrorHandlers.java:117)
	at io.helidon.nima.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:81)
	at io.helidon.nima.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:114)
	at io.examples.helidon.nima.NimaMain.lambda$routing$0(NimaMain.java:34)
	at io.helidon.nima.webserver.http.Filters$FilterChainImpl.runNextFilter(Filters.java:125)
	at io.helidon.nima.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:50)
	at io.helidon.nima.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:112)
	at io.helidon.nima.webserver.http.Filters.filter(Filters.java:81)
	at io.helidon.nima.webserver.http.HttpRouting.route(HttpRouting.java:94)
	at io.helidon.nima.webserver.http1.Http1Connection.route(Http1Connection.java:254)
	at io.helidon.nima.webserver.http1.Http1Connection.handle(Http1Connection.java:140)
	at io.helidon.nima.webserver.ConnectionHandler.run(ConnectionHandler.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:352)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:287)
	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:174)
	at java.base/jdk.internal.vm.Continuation.enter0(Continuation.java:327)
	at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:320)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1048)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
	at io.examples.helidon.nima.BlockingService.parallel2(BlockingService.java:105)
	at io.helidon.nima.webserver.http.HttpRouting$RoutingExecutor.doRoute(HttpRouting.java:343)
	at io.helidon.nima.webserver.http.HttpRouting$RoutingExecutor.execute(HttpRouting.java:305)
	at io.helidon.nima.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:50)
	... 16 more"

## Steps to reproduce
*  "try increment count  to 10000"

**Comment by tomas-langer** [comment]
As far as I can tell, this code is not part of our repository.

**Comment by tomas-langer** [comment]
Also you only decrement the latch if you successfully add to the queue, so if you ever get a `false` back, this code never completes.
I have tried similar code to yours, and it works just fine - I am using `latch.countDown()` in a `finally` block, to make sure it is done for every single repetition.

**Comment by artshell** [comment]
good idea, thanks!

But there was another problem！report `java.io.IOException: Too many open files`

Problem solved when used fixed FIXED_POOL (Although this is not recommended instead of `Semaphore`)，

```java
    private static final ThreadFactory VIRTUAL_FACTORY = Thread.ofVirtual()
            .name("async-executor-virtual-thread-", 0)
            .factory();

    public static final ExecutorService VIRTUAL_THREAD_FIXED_POOL = Executors.newFixedThreadPool(5000, VIRTUAL_FACTORY);
```

**Comment by tomas-langer** [comment]
You are doing 10000 parallel requests - each request opens a connection to the server (there is a client/server request for each parallel task).
Your operating system is not capable of handling it. You should be able to increase the number of open file descriptors on your operating system if you want to do tests like this.
The example is really to show how to do parallel tasks in a virtual thread environment. Running 10000 in parallel is quite a big thing, and you need to make sure your environment is ready for it.
I will close this issue, as this is not a Helidon Níma issue.
