### ISSUE TITLE
Metrics incorrectly uses top-level config, not `metrics`-level, in setting global tags

### ISSUE THREAD

**Issue by martin-sladecek** [helidon-io/helidon#5791]
MetricsCdiExtension fails when `tags` env. property is present.

## Environment Details
* Helidon Version: 3.1.0
* Helidon MP
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
We have `tags` environment in our pipeline, which leads to a following error in tests:
```
java.lang.IllegalArgumentException: Error(s) in global tag expression: [Missing '=': ]
	at io.helidon.metrics.api.MetricsSettingsImpl$Builder.globalTagsExpressionToMap(MetricsSettingsImpl.java:219)
	at io.helidon.config.ConfigValues.lambda$create$4(ConfigValues.java:146)
	at io.helidon.config.ConfigValues$GenericConfigValueImpl.asOptional(ConfigValues.java:233)
	at io.helidon.config.ConfigValue.ifPresent(ConfigValue.java:227)
	at io.helidon.metrics.api.MetricsSettingsImpl$Builder.config(MetricsSettingsImpl.java:161)
	at io.helidon.metrics.api.MetricsSettingsImpl$Builder.config(MetricsSettingsImpl.java:95)
	at io.helidon.metrics.api.MetricsSettings.create(MetricsSettings.java:53)
	at io.helidon.metrics.serviceapi.MetricsSupport.create(MetricsSupport.java:89)
	at io.helidon.servicecommon.restcdi.HelidonRestCdiExtension.registerService(HelidonRestCdiExtension.java:245)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.registerService(MetricsCdiExtension.java:736)
``` 

The reason is that `MetricsCdiExtension.seComponentConfig` is constructing a Config that also contains system properties and env variables, so our `tags` env variable is interpreted as `metrics.tags` configuration property.

## Steps to reproduce
Run a microservice with empty tags env. property.

**Comment by tjquinno** [comment]
This is a bug. The Helidon code should be using `metrics.` (for SE) or `mp.metrics.` (for MP) as a prefix for the config key for `tags` (and `appName` as well).
