### ISSUE TITLE
Null Pointer Exception when using Builder Based RestClients and FT annotation and FT metrics together

### ISSUE THREAD

**Issue by RahulBalan** [helidon-io/helidon#6056]
## Environment Details
* Helidon Version: 2.5.4
* Helidon SE or Helidon MP : MP
* JDK version: 17 
* OS:
* Docker version (if applicable):

----------

## Problem Description

We are noticing a problem with helidon.microprofile.faulttolerance
Our micro service is using RestClient. This rest client has @Retry annotation. But its not having @RegisterRestClient.
We are creating an instance of RestClient at run time using RestClientBuilder.newBuilder().build() and uses it.
Since we are not using @RegisterRestClient ,the bean is no prepared and FaultToleranceExtension.registerFaultToleranceMethods is not invoked for our Restclient while starting the container.
Hence our method is not added to the collection FaultToleranceExtension.registeredMethods;
So when FaultToleranceExtension.registerMetricsAndInitExecutors loops through  registeredMethods to invoke FaultToleranceMetrics.registerRetryMetrics , since our method is not present in the registeredMethods , retry.retries.total counter is not registered for our method.
Once the container is started and our services uses the RestClient(created at run time) , CommandInterceptor.interceptCommand is called, which calls MethodInvoker.get(), which calls updateMetricsAfter() , which calls updateCounter().
In updateCounter() , Counter counter = getCounter(method, name) returns null (our counter is not registered as i mentioned above)  .
But there is no null check. Hence counter.getCount() throws null pointer exception

**Comment by RahulBalan** [comment]
Stack trace
=========
Caused by: java.lang.NullPointerException: Cannot invoke \"org.eclipse.microprofile.metrics.Counter.getCount()\" because \"counter\" is null
at io.helidon.microprofile.faulttolerance.MethodInvoker.updateCounter(MethodInvoker.java:764) ~[helidon-microprofile-fault-tolerance-2.5.4.jar:2.5.4]
at io.helidon.microprofile.faulttolerance.MethodInvoker.updateMetricsAfter(MethodInvoker.java:657) ~[helidon-microprofile-fault-tolerance-2.5.4.jar:2.5.4]
at io.helidon.microprofile.faulttolerance.MethodInvoker.get(MethodInvoker.java:436) ~[helidon-microprofile-fault-tolerance-2.5.4.jar:2.5.4]
at io.helidon.microprofile.faulttolerance.CommandInterceptor.interceptCommand(CommandInterceptor.java:54) ~[helidon-microprofile-fault-tolerance-2.5.4.jar:2.5.4]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-2.5.4.jar:2.5.4]
at org.jboss.weld.interceptor.proxy.WeldInvocationContextImpl.invokeNext(WeldInvocationContextImpl.java:92) ~[weld-core-impl-2.5.4.jar:2.5.4]
at org.jboss.weld.interceptor.proxy.WeldInvocationContextImpl.proceed(WeldInvocationContextImpl.java:124) ~[weld-core-impl-2.5.4.jar:2.5.4]
at org.jboss.weld.bean.InterceptorImpl.intercept(InterceptorImpl.java:105) ~[weld-core-impl-2.5.4.jar:2.5.4]
at org.glassfish.jersey.microprofile.restclient.InterceptorInvocationContext$InvocationInterceptor.intercept(InterceptorInvocationContext.java:136) ~[jersey-mp-rest-client-2.35.jar:?]
at org.glassfish.jersey.microprofile.restclient.InterceptorInvocationContext.proceed(InterceptorInvocationContext.java:108) ~[jersey-mp-rest-client-2.35.jar:?]
at org.glassfish.jersey.microprofile.restclient.RestClientModel.invokeMethod(RestClientModel.java:69) ~[jersey-mp-rest-client-2.35.jar:?]
at org.glassfish.jersey.microprofile.restclient.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:70) ~[jersey-mp-rest-client-2.35.jar:?]
at jdk.proxy2.$Proxy239.getFeedConfigurationBySignal(Unknown Source) ~[?:?]
at com.oracle.osc.digitalsales.restclient.impl.FARestClientImpl.getFeedConfigurationBySignal(FARestClientImpl.java:189) ~[osc-commoncore-23.04.1-M4-SNAPSHOT.jar:?]
at com.oracle.osc.digitalsales.restclient.impl.FARestClientImpl$Proxy$_$$_WeldClientProxy.getFeedConfigurationBySignal(Unknown Source) ~[osc-commoncore-23.04.1-M4-SNAPSHOT.jar:?]
at com.oracle.osc.feed.rest.fa.client.facade.impl.FaRestClientFacadeImpl.getFeedConfigurationBySignal(FaRestClientFacadeImpl.java:129) ~[feed-system-api-1.jar:?]
... 168 more

**Comment by jbescos** [comment]
I am not sure whether this is a bug. The NPE is thrown because of a missusage of the `@RegisterRestClient`. NPE are expected to happen if you are using a bean that was supposed to be instanced by CDI, because it will have null dependencies.

**Comment by tomas-langer** [comment]
This is an issue for a no longer supported version of Helidon.
Also the explanation by Jorge seems to be valid and explains the reason an NPE was thrown. 
Closing this issue.
