### ISSUE TITLE
[4.x] RC in JMS tests

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6366]
```
Error:  Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.809 s <<< FAILURE! - in io.helidon.messaging.connectors.jms.JmsMpTest
Error:  io.helidon.messaging.connectors.jms.JmsMpTest.error  Time elapsed: 0.006 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.hamcrest.collection.IsIterableContainingInAnyOrder.matchesSafely(IsIterableContainingInAnyOrder.java:26)
	at org.hamcrest.collection.IsIterableContainingInAnyOrder.matchesSafely(IsIterableContainingInAnyOrder.java:16)
	at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:55)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.messaging.connectors.jms.AbstractMPTest.produceAndCheck(AbstractMPTest.java:59)
	at io.helidon.messaging.connectors.jms.AbstractMPTest.produceAndCheck(AbstractMPTest.java:42)
	at io.helidon.messaging.connectors.jms.JmsMpTest.error(JmsMpTest.java:231)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at io.helidon.messaging.connectors.jms.JmsMpTest$Proxy$_$$_WeldClientProxy.error(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

**Comment by spericas** [comment]
Maybe just this?

```
diff --git a/tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AbstractMPTest.java b/tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AbstractMPTest.java
index eed5e42585..b314d6c0fe 100644
--- a/tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AbstractMPTest.java
+++ b/tests/integration/jms/src/test/java/io/helidon/messaging/connectors/jms/AbstractMPTest.java
@@ -56,7 +56,10 @@ public abstract class AbstractMPTest extends AbstractJmsTest {
                     expected.toString(), consumingBean.consumed().toString()));
         }
         if (!expected.isEmpty()) {
-            assertThat(consumingBean.consumed(), Matchers.containsInAnyOrder(expected.toArray()));
+            // This list requires a synchronized block for traversing
+            synchronized (consumingBean.consumed()) {
+                assertThat(consumingBean.consumed(), Matchers.containsInAnyOrder(expected.toArray()));
+            }
         }
     }
```

**Comment by danielkec** [comment]
Its a missed test checking functionality from Messaging 1.0 and worked by chance, probability of the failure rizen when `period-executions` got configured to lower value for making test running faster.
