### ISSUE TITLE
Migrating from 2.x to 3.x yields java.lang.IllegalArgumentException: context is not a valid SpanContextShim object

### ISSUE THREAD

**Issue by rlubke** [helidon-io/helidon#6476]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.1.2
* Helidon MP
* JDK version: 17
* OS: MacOS
* Docker version (if applicable): N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Migrating https://github.com/oracle/coherence-helidon-sockshop-sample to Helidon 3.1.2.  Integrate tests are failing with the following:

`java.lang.IllegalArgumentException: context is not a valid SpanContextShim object
	at io.opentelemetry.opentracingshim.SpanBuilderShim.getContextShim(SpanBuilderShim.java:250)
	at io.opentelemetry.opentracingshim.SpanBuilderShim.addReference(SpanBuilderShim.java:82)
	at io.opentelemetry.opentracingshim.SpanBuilderShim.asChildOf(SpanBuilderShim.java:72)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.microprofile.tracing.MpTracingInterceptor.trace(MpTracingInterceptor.java:83)
	at io.helidon.microprofile.tracing.MpTracingInterceptor.aroundMethod(MpTracingInterceptor.java:55)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)`

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

Checkout the `23.03` branch of https://github.com/oracle/coherence-helidon-sockshop-sample.  Within Intellij or from the command line, run the CartResourceIT test.

**Comment by rlubke** [comment]
Note, I temporarily disabled tracing within the test, so if run as-is in the branch, it will pass.  Re-enable tracing to observe the failure.
