### ISSUE TITLE
Provide option to disable DnsResolver when communicating with proxy server

### ISSUE THREAD

**Issue by jitendramca06** [helidon-io/helidon#6479]
Environment Details
* Helidon Version:io.helidon.webclient:helidon-webclient:2.5.6
* JDK version:java version "17.0.3" 2022-04-19 LTS
* OS:Oracle Linux Server,VERSION="7.8"

----------

Problem Description
Current behavior:
I have a Proxy server which is running on **localhost** and port **1026**. When I am calling the endpoint using **io.helidon.webclient.WebClient** then I am getting below error. But When I am calling the endpoint using **java.net.HttpURLConnection** then call is going through proxy server and I am able to get proper response.

**Caused by: io.helidon.webclient.WebClientException: http://api.getgexchangerates.com:1025/currencyexchangerates/USD/webClient
    at io.helidon.webclient.WebClientRequestBuilderImpl.lambda$invoke$15(WebClientRequestBuilderImpl.java:622)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
    at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:110)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
    at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:214)
    at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
    at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
    at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
    at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
    at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
    at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: api.getgexchangerates.com: nodename nor servname provided, or not known
    at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
    at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
    at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
    at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
    at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
    at java.base/java.net.InetAddress.getByName(InetAddress.java:1251)
    at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
    at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
    at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
    at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
    at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
    at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
    at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
    at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
    at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
    at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)**

Expected behavior:
If we set **http.proxyHost** and **http.proxyPort** either using system property or **io.helidon.webclient.Proxy** then **io.helidon.webclient.WebClient** should communicate with proxy server without doing any hostname verification.

Step by step instructions to reproduce the problem:-
I have written a sample proxy server **MyProxyServer** and **WebClientWithProxy** classes to reproduce the scenario in local(Classes are available with Archive.zip).

1. Download Archive.zip and extract and add these java classes **MyProxyServer** and **WebClientWithProxy** in intellij
2. Start proxy server **MyProxyServer**
3. Run  **WebClientWithProxy**
Now you will able to see **java.net.HttpURLConnection** successfully doing communication with proxy server and getting the response code as 200 but **io.helidon.webclient.WebClient** doing hostname verification before communicating to proxy server.
We want **io.helidon.webclient.WebClient** to communicate proxy server without doing any hostname verification

[Archive.zip](https://github.com/helidon-io/helidon/files/11047062/Archive.zip)

**Comment by klustria** [comment]
The change can be used to disable DNS resolver by using WebClientRequestBuilder's dnsResolverType() and set it to DnsResolverType.NONE like below:
```
WebClientConfiguration webConfig = WebClient.builder()
                 .baseUri("http://localhost:80")
                 .dnsResolverType(DnsResolverType.NONE)
                 .configuration();
```

**Comment by klustria** [comment]
Merge completed, hence closing
