### ISSUE TITLE
Migration from 2.x to 3.x appears to have changed behavior in @RegisterRestClient annotation handling

### ISSUE THREAD

**Issue by rlubke** [helidon-io/helidon#6504]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.1.2
* Helidon MP
* JDK version: 17.0.6
* OS: MacOS
* Docker version (if applicable): N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

See https://github.com/oracle/coherence-helidon-sockshop-sample/blob/master/orders/src/main/java/com/oracle/coherence/examples/sockshop/helidon/orders/CartsClient.java

Notice how `@RegisterRestClient` is used.  In Helidon 3.x, any attempts to use the client result in a host not found error for `carts`.  In 2.x, the host and port were resolved and the client functioned.

Here is the stacktrace from Helidon 3.x:

```
jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: carts
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:270)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

Check out the `23.03` branch from https://github.com/oracle/coherence-helidon-sockshop-sample
Run the `CoherenceOrderResourceIT` test in the `orders` module.  Tests `testCreateOrder`, `testPaymentDeclined`, and `testPaymentFailure` all fail with ` java.net.UnknownHostException: carts`

**Comment by Verdent** [comment]
Not a bug
