### ISSUE TITLE
Intermittent test failure WaterMarkedBackpressureIT

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6524]
In main branch pipeline

```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.073 s <<< FAILURE! - in io.helidon.reactive.webserver.WaterMarkedBackpressureIT
Error:  io.helidon.reactive.webserver.WaterMarkedBackpressureIT.linear  Time elapsed: 5.024 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is <101L>
     but: was <143L>
	at io.helidon.reactive.webserver.WaterMarkedBackpressureIT.linear(WaterMarkedBackpressureIT.java:122)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    WaterMarkedBackpressureIT.linear:122 
```

[logs_3116.zip](https://github.com/helidon-io/helidon/files/11111198/logs_3116.zip)

**Comment by romain-grecourt** [comment]
Happened here: https://github.com/helidon-io/helidon/actions/runs/4724175010/jobs/8381056968

**Comment by barchetta** [comment]
And here https://github.com/helidon-io/helidon/actions/runs/4736275822/jobs/8423499776?pr=6644

```
[INFO] Running io.helidon.webserver.WaterMarkedBackpressureIT
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.823 s <<< FAILURE! - in io.helidon.webserver.WaterMarkedBackpressureIT
Error:  io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush  Time elapsed: 15.393 s  <<< FAILURE!
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)
Caused by: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)
```

**Comment by tomas-langer** [comment]
And now:
```
Running io.helidon.webserver.WaterMarkedBackpressureIT
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.887 s <<< FAILURE! - in io.helidon.webserver.WaterMarkedBackpressureIT
Error:  io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush  Time elapsed: 15.376 s  <<< FAILURE!
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)
Caused by: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    WaterMarkedBackpressureIT.autoFlush:175 » Completion java.util.concurrent.Time...
[INFO] 
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by romain-grecourt** [comment]
And here: https://github.com/helidon-io/helidon/actions/runs/4813688292/jobs/8570534396?pr=6699

```
Running io.helidon.webserver.WaterMarkedBackpressureIT
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 20.927 s <<< FAILURE! - in io.helidon.webserver.WaterMarkedBackpressureIT
Error:  io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush  Time elapsed: 15.402 s  <<< FAILURE!
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)
Caused by: java.util.concurrent.TimeoutException
	at io.helidon.webserver.WaterMarkedBackpressureIT.autoFlush(WaterMarkedBackpressureIT.java:175)
```

**Comment by danielkec** [comment]
Leaving out 4.x as whole thing gets removed soon
