### ISSUE TITLE
Fault tolerance without metrics causes runtime exception

### ISSUE THREAD

**Issue by AlirezaDastyar** [helidon-io/helidon#6579]
So when I try to use fault tolerance without  metrics I get `java.lang.ClassNotFoundException: org.eclipse.microprofile.metrics.Metric`

## Environment Details
* Helidon Version: 3.2.0
* Helidon MP
* JDK version: 17.0.6
* OS: Fedora 36

----------

## Problem Description
When I try to run a app that uses fault tolerance without metrics I get following error:
```
2023.04.08 13:06:38 INFO io.helidon.common.LogConfig Thread[main,5,main]: Logging at initialization configured using classpath: /logging.properties
Exception in thread "main" jakarta.enterprise.event.ObserverException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:78)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:103)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:340)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/microprofile/metrics/Metric
        at io.helidon.microprofile.faulttolerance.FaultToleranceExtension.validateAnnotations(FaultToleranceExtension.java:220)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.microprofile.metrics.Metric
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 21 more
```
And when I add the metrics dependency everything works just fine:
```
<dependency>
    <groupId>io.helidon.microprofile.metrics</groupId>
    <artifactId>helidon-microprofile-metrics</artifactId>
</dependency>
```

## Steps to reproduce

1. Use the starter at helidon.io
2. Chose Helidon MP flaver
3. Select custom for application type
4. Leave Media Support + Security + Database with default values
5. Select fault tolerance in extra section
6. Leave everything else with default value (all unchecked)
7. Download and try to run the app (I've deleted the tests to get rid of dependency errors)

**Comment by spericas** [comment]
This is expected, there's currently with Metrics dependency in FT. In fact, you cannot run the MP FT TCKs without Metrics either.

**Comment by AlirezaDastyar** [comment]
Oh, I see, does it make sense to mention that in Helidon docs? or it's expected of users to read the [MP FT docs](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-4.0/microprofile-fault-tolerance-spec-4.0.html#_relationship_to_microprofile_metrics)?
Thank you for your reply.

**Comment by tomas-langer** [comment]
This dependency is marked as `provided` in FaultTolerance, but it is not a mandatory dependency of MP core application.
So the dependency should not be marked as `provided` but rather as `compile`.

**Comment by spericas** [comment]
Yes, we need to change the scope.
