### ISSUE TITLE
 Helidon upload api high response times with concurrent users

### ISSUE THREAD

**Issue by NarendraBanothu** [helidon-io/helidon#6596]
We are having a use case to read the file as input to one of our rest APIs using file FormDataParam implemented in Helidon 2.5.4. If we are calling this upload api with file size of 200Mb then response time is 20 sec but if we are parallelly calling this with 6 files then the response time is increasing to 2min to 3 min. JFR tracing is saying FormDataParamValueParamProvider$ValueProvider.getEntity(ContainerRequest) is taking 90% of the API response.

@POST
 @Path("/upload")
 @Consumes(MediaType.MULTIPART_FORM_DATA)
 @Produces(MediaType.APPLICATION_JSON)
 public Response upload(@FormDataParam("flowName") final String flowName,
                        @FormDataParam("dateFormat") final String dateFormat,
                        @FormDataParam("fileId") final String fileId,
                        @FormDataParam("uploadSource") final String uploadSource,
                        @FormDataParam("file") final FormDataContentDisposition fileContentDisposition,
                        @FormDataParam("file") final InputStream fileInputStream,
                        @FormDataParam("forceTrigger") final Boolean forceTrigger,
                        @PathParam("locale") String locale) {

90.61% (about 1.0 min, 5037 samples) - org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataParamValueProvider.apply(ContainerRequest)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$ValueProvider.getEntity(ContainerRequest)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.server.ContainerRequest.readEntity(Class)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(Class, PropertiesDelegate)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(Class, Type, Annotation[], PropertiesDelegate)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(Class, Type, Annotation[], MediaType, MultivaluedMap, PropertiesDelegate, InputStream, Iterable, boolean)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed()
90.59% (~1.0 min, 5036) - org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(ReaderInterceptorContext)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed()
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorContext)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorContext, MessageBodyReader, EntityInputStream)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(Class, Type, Annotation[], MediaType, MultivaluedMap, InputStream)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(Class, Type, Annotation[], MediaType, MultivaluedMap, InputStream)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(Class, Type, Annotation[], MediaType, MultivaluedMap, InputStream)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(Class, Type, Annotation[], MediaType, MultivaluedMap, InputStream)
90.59% (~1.0 min, 5036) - org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.getMimeParts(MIMEMessage)
90.59% (~1.0 min, 5036) - org.jvnet.mimepull.MIMEMessage.getAttachments()
90.59% (~1.0 min, 5036) - org.jvnet.mimepull.MIMEMessage.parseAll()
90.59% (~1.0 min, 5036) - org.jvnet.mimepull.MIMEMessage.makeProgress()
89.69% (~59.974 s, 4986) - org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next()
89.69% (~59.974 s, 4986) - org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next()
89.69% (~59.974 s, 4986) - org.jvnet.mimepull.MIMEParser.access$600(MIMEParser)
89.69% (~59.974 s, 4986) - org.jvnet.mimepull.MIMEParser.readBody()
81.58% (~54.549 s, 4535) - org.jvnet.mimepull.MIMEParser.fillBuf()
81.58% (~54.549 s, 4535) - org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(byte[], int, int)
81.58% (~54.549 s, 4535) - org.glassfish.jersey.message.internal.EntityInputStream.read(byte[], int, int)
81.58% (~54.549 s, 4535) - io.helidon.media.common.DataChunkInputStream.read(byte[], int, int)
81.47% (~54.477 s, 4529) - java.util.concurrent.CompletableFuture.get()
81.47% (~54.477 s, 4529) - java.util.concurrent.CompletableFuture.waitingGet(boolean)
81.42% (~54.441 s, 4526) - java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker)
81.42% (~54.441 s, 4526) - java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool$ManagedBlocker)
81.42% (~54.441 s, 4526) - java.util.concurrent.CompletableFuture$Signaller.block()
81.42% (~54.441 s, 4526) - java.util.concurrent.locks.LockSupport.park(Object)
81.42% (~54.441 s, 4526) - jdk.internal.misc.Unsafe.park(boolean, long)

**Comment by NarendraBanothu** [comment]
All the helidon threads are waiting on the below stack trace

"helidon-server-1" #41 daemon prio=5 os_prio=0 cpu=7834.50ms elapsed=42134.39s tid=0x00007fd4aa5cd480 nid=0x3e waiting on condition  [0x00007fd43ddfb000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.6/Native Method)
	- parking to wait for  <0x00000000e56e2910> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.6/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.6/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.6/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.6/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.6/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.6/CompletableFuture.java:2072)
	at io.helidon.media.common.DataChunkInputStream.read(DataChunkInputStream.java:131)
	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:79)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:273)
	at org.jvnet.mimepull.MIMEParser.fillBuf(MIMEParser.java:415)
	at org.jvnet.mimepull.MIMEParser.readBody(MIMEParser.java:191)
	at org.jvnet.mimepull.MIMEParser.access$600(MIMEParser.java:38)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:140)
	at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:102)
	at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:200)
	- locked <0x00000000e8882680> (a org.jvnet.mimepull.MIMEMessage)
	at org.jvnet.mimepull.MIMEMessage.parseAll(MIMEMessage.java:160)
	at org.jvnet.mimepull.MIMEMessage.getAttachments(MIMEMessage.java:86)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.getMimeParts(MultiPartReaderClientSide.java:248)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:207)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:67)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:159)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:69)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:819)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:253)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$ValueProvider.getEntity(FormDataParamValueParamProvider.java:84)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataParamValueProvider.apply(FormDataParamValueParamProvider.java:235)
	at org.glassfish.jersey.media.multipart.internal.FormDataParamValueParamProvider$FormDataParamValueProvider.apply(FormDataParamValueParamProvider.java:222)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:64)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:335)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler$$Lambda$2600/0x00000008017606d0.run(Unknown Source)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
	at io.helidon.common.context.ContextAwareExecutorImpl$$Lambda$2584/0x00000008016f9180.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.6/Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.6/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.6/Unknown Source)

**Comment by Nish-Na** [comment]
Hi Dmitry

What client do you use here? Is it Helidon WebClient?
No UI. So, using postman & gatling. 

Is the performance degradation the same without @FormData parameters? 
Could see the same measurement with and without.

Thank You

**Comment by Nish-Na** [comment]
Have tried the below settings for jersey along with Dmitry, could see any improvment
```
jersey:
  connector:
    helidon:
      entity:
        type: <type>
```
<type> : OUTPUT_STREAM_MULTI, BYTE_ARRAY_OUTPUT_STREAM, READABLE_BYTE_CHANNEL

**Comment by dalexandrov** [comment]
Additional investigation has to be made on `DataChunkInputStream` in Helidon, as there is active waiting detected.

**Comment by dalexandrov** [comment]
We have done some investigation on our local machines. We were able to run the same Gatling tests for 1 and 6 users. 
For Mac M1 64G, 8TB nvme, the results for 200mb upload that we have:
1 user - 407 ms upload time
6 users in parallel - 791 ms upload time

This is measuring only upload time with no writing to disk. 
I would kindly ask you to check the environment you are using in do your measurements.
