### ISSUE TITLE
4.x io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test intermittent failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6653]
Intermittently seen on PR validation (https://github.com/helidon-io/helidon/pull/6572).

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.helidon.microprofile.metrics.TestMetricsOnOwnSocket
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.634 s - in io.helidon.microprofile.metrics.TestMetricsOnOwnSocket
[INFO] Running io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.199 s <<< FAILURE! - in io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest
Error:  io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test  Time elapsed: 7.519 s  <<< FAILURE!
java.lang.AssertionError: 
Change in count for explicit SimpleTimer
Expected: is <1L>
     but: was <2L>
	at io.helidon.common.testing.junit5.MatcherWithRetry.assertThatWithRetry(MatcherWithRetry.java:68)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test(HelloWorldAsyncResponseTest.java:120)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest$Proxy$_$$_WeldClientProxy.test(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by romain-grecourt** [comment]
Also occurred in 3.x https://github.com/helidon-io/helidon/actions/runs/5084245287/jobs/9136288058

**Comment by barchetta** [comment]
And 2.x:
```
Error:  io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test  Time elapsed: 2.014 s  <<< FAILURE!
java.lang.AssertionError: 
Change in count for explicit SimpleTimer
Expected: is <1L>
     but: was <2L>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest.test(HelloWorldAsyncResponseTest.java:120)
	at io.helidon.microprofile.metrics.HelloWorldAsyncResponseTest$Proxy$_$$_WeldClientProxy.test(Unknown Source)
```

**Comment by barchetta** [comment]
assigning to @tjquinno as we are seeing this fairly often during PR validation.

**Comment by tjquinno** [comment]
Sigh. This test uses explicit synchronization between the test client and the service precisely to avoid such problems, but obviously it's not working all the time.

I'll take a look.

**Comment by tjquinno** [comment]
I have disabled the offending test temporarily until I get time to dig into the root cause of the failures.

**Comment by barchetta** [comment]
Still seeing this pretty often in 3.x

**Comment by romain-grecourt** [comment]
Happened in 3.x here: https://github.com/helidon-io/helidon/actions/runs/6004982497/job/16286752029?pr=7457
