### ISSUE TITLE
3.x: intermitent test failure KafkaMpTest

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6730]
This was after the kafka-clients upgrade to 3.4.0. Don't know if that matters or not.

```
 [INFO] Running io.helidon.messaging.connectors.kafka.KafkaMpTest
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.691 s <<< FAILURE! - in io.helidon.messaging.connectors.kafka.KafkaMpTest
Error:  io.helidon.messaging.connectors.kafka.KafkaMpTest.noAckDQL  Time elapsed: 1.382 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable over ["0", "1", "2", "4", "5", "6", "7", "8", "9", "10"] in any order
     but: No item matches: "10" in ["1", "0", "2", "6", "7", "8", "4", "9", "5"]
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.messaging.connectors.kafka.KafkaMpTest.noAckDQL(KafkaMpTest.java:366)
```

**Comment by barchetta** [comment]
Still seeing this intermitently in 4.x pipeline:

```
[INFO] Running io.helidon.messaging.connectors.kafka.EmittingPublisherTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 s - in io.helidon.messaging.connectors.kafka.EmittingPublisherTest
[INFO] Running io.helidon.messaging.connectors.kafka.KafkaMpTest
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 52.921 s <<< FAILURE! - in io.helidon.messaging.connectors.kafka.KafkaMpTest
Error:  io.helidon.messaging.connectors.kafka.KafkaMpTest.error  Time elapsed: 0.869 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing ["10"]
     but: Not matched: "20"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.messaging.connectors.kafka.AbstractKafkaTest.produceAndCheck(AbstractKafkaTest.java:108)
	at io.helidon.messaging.connectors.kafka.AbstractKafkaTest.produceAndCheck(AbstractKafkaTest.java:87)
	at io.helidon.messaging.connectors.kafka.KafkaMpTest.error(KafkaMpTest.java:341)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```
