### ISSUE TITLE
MultiPart IllegalReferenceCountException: refCnt: 0, decrement: 1

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#6845]
## Environment Details
* Helidon Version: 2.6.0
* Helidon SE

----------

Consuming a body part content as an `InputStream` in a different threads triggers the following exception:

```java
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.common@4.1.86.Final/io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.common@4.1.86.Final/io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:147)
	at io.netty.buffer@4.1.86.Final/io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.helidon.common.http@2.6.0/io.helidon.common.http.ByteBufferDataChunk.release(ByteBufferDataChunk.java:86)
	at io.helidon.media.multipart@2.6.0/io.helidon.media.multipart.BodyPartChunk.release(BodyPartChunk.java:49)
	at io.helidon.media.common@2.6.0/io.helidon.media.common.DataChunkInputStream.releaseChunk(DataChunkInputStream.java:86)
	at io.helidon.media.common@2.6.0/io.helidon.media.common.DataChunkInputStream.read(DataChunkInputStream.java:164)
	at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:387)
	at com.oracle.cx.industries.edk.integrations.base.http@23.10.0.0-SNAPSHOT/com.oracle.cx.industries.edk.integrations.base.http.internal.MultipartSpokeReplySubscriber.lambda$onNext$3(MultipartSpokeReplySubscriber.java:107)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.helidon.common.reactive@2.6.0/io.helidon.common.reactive.SingleToFuture.onNext(SingleToFuture.java:67)
	at io.helidon.common.reactive@2.6.0/io.helidon.common.reactive.SingleObserveOn$ObserveOnSubscriber.run(SingleObserveOn.java:127)
	at io.helidon.common.context@2.6.0/io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context@2.6.0/io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Reproducer:

```java
ExecutorService executor = ThreadPoolSupplier.builder()
                                                   .corePoolSize(5)
                                                   .build()
                                                   .get();

MultiPartSupport multiPartSupport = MultiPartSupport.create();
WebClient webClient = WebClient.builder()
                               .baseUri("http://localhost:8080")
                               .addMediaSupport(multiPartSupport)
                               .build();

WebServer.builder()
         .port(8080)
         .addMediaSupport(multiPartSupport)
         .routing(Routing.builder()
                         .get("/test", (req, res) -> {
                             final var capacity = 21 << 20;
                             final var buffer = ByteBuffer.allocate(capacity);
                             final byte[] contents = new byte[capacity - 1];
                             Arrays.fill(contents, (byte) 0x20);
                             buffer.put(contents);
                             buffer.put((byte) 0x00);
                             buffer.flip();
                                 /*
                                    now we have a buffer with 21MB capacity, all filled with spaces except the last
                                    byte that is the NUL or \0 byte to terminate the string
                                  */
                             res.send(WriteableMultiPart
                                     .builder()
                                     .bodyPart(WriteableBodyPart
                                             .builder()
                                             .publisher(Single.just(DataChunk.create(buffer)))
                                             .headers(WriteableBodyPartHeaders
                                                     .builder()
                                                     .contentType(TEXT_PLAIN)
                                                     .contentDisposition(ContentDisposition
                                                             .builder()
                                                             .name("too-big")
                                                             .build())
                                                     .build())
                                             .build())
                                     .build()); // we actually don't need payload here
                         })
                         .get("/", (req, res) ->
                                 webClient.get()
                                          .path("test")
                                          .accept(MediaType.MULTIPART_FORM_DATA)
                                          .submit()
                                          .flatMap(response -> response.content().asStream(ReadableBodyPart.class))
                                          .subscribe(new Flow.Subscriber<>() {

                                              Flow.Subscription subscription;

                                              @Override
                                              public void onSubscribe(Flow.Subscription subscription) {
                                                  this.subscription = subscription;
                                                  subscription.request(1L);
                                              }

                                              @Override
                                              public void onNext(ReadableBodyPart part) {
                                                  part.content()
                                                      .as(InputStream.class)
                                                      .observeOn(executor)
                                                      .onError(req::next)
                                                      .forSingle(is -> {
                                                          try {
                                                              byte[] bytes = is.readAllBytes();
                                                              subscription.request(1L);
                                                          } catch (Throwable e) {
                                                              req.next(e);
                                                          }
                                                      })
                                                      .exceptionally(res::send);
                                                  subscription.request(1L);
                                              }

                                              @Override
                                              public void onError(Throwable throwable) {
                                                  throwable.printStackTrace(System.out);
                                                  res.send("OK");
                                              }

                                              @Override
                                              public void onComplete() {
                                                  res.send("OK");
                                              }
                                          })))
         .build()
         .start();
```

**Comment by romain-grecourt** [comment]
The issue is actually caused by a race condition in `DataChunk.release()`, specifically in `io.helidon.common.http.ByteBufferDataChunk.release()`.

The `isReleased` field needs to be changed to an `AtomicBoolean`.

**Comment by romain-grecourt** [comment]
A work-around is to use a custom implementation of `DataChunk` in order to override `release()` and `isReleased()` to be backed with an `AtomicBoolean`.

```java
static final class DataChunkImpl extends DelegatingDataChunkImpl {

    private final AtomicBoolean isReleased = new AtomicBoolean();

    private DataChunkImpl(DataChunk delegate) {
        super(delegate);
    }

    @Override
    public boolean isReleased() {
        return isReleased.get();
    }

    @Override
    public void release() {
        if (isReleased.compareAndSet(false, true)) {
            super.release();
        }
    }
}

static class DelegatingDataChunkImpl implements DataChunk {

    private final DataChunk delegate;

    private DelegatingDataChunkImpl(DataChunk delegate) {
        this.delegate = delegate;
    }

    @Override
    public ByteBuffer[] data() {
        return delegate.data();
    }

    @Override
    public <T> T[] data(Class<T> clazz) {
        return delegate.data(clazz);
    }

    @Override
    public <T> boolean isBackedBy(Class<T> clazz) {
        return delegate.isBackedBy(clazz);
    }

    @Override
    public int remaining() {
        return delegate.remaining();
    }

    @Override
    public Iterator<ByteBuffer> iterator() {
        return delegate.iterator();
    }

    @Override
    public long id() {
        return delegate.id();
    }

    @Override
    public byte[] bytes() {
        return delegate.bytes();
    }

    @Override
    public boolean isReleased() {
        return delegate.isReleased();
    }

    @Override
    public void release() {
        delegate.release();
    }

    @Override
    public boolean flush() {
        return delegate.flush();
    }

    @Override
    public DataChunk duplicate() {
        return delegate.duplicate();
    }

    @Override
    public boolean isReadOnly() {
        return delegate.isReadOnly();
    }

    @Override
    public boolean isFlushChunk() {
        return delegate.isFlushChunk();
    }

    @Override
    public void writeFuture(CompletableFuture<DataChunk> writeFuture) {
        delegate.writeFuture(writeFuture);
    }

    @Override
    public Optional<CompletableFuture<DataChunk>> writeFuture() {
        return delegate.writeFuture();
    }
}
```

The client request can be changed like this:

```java
webClient.get()
      .path("test")
      .accept(MediaType.MULTIPART_FORM_DATA)
      .submit()
      .forSingle(response -> {
          String boundary = response.headers()
                                    .contentType()
                                    .map(ct -> ct.parameters().get("boundary"))
                                    .orElseThrow(() -> new BadRequestException("boundary header is missing"));

          MultiPartDecoder decoder = MultiPartDecoder.create(boundary, req.content().readerContext());
          response.content().map(DataChunkImpl::new).subscribe(decoder);
          Multi.create(decoder)
               .flatMap(part -> part.content().as(InputStream.class).observeOn(executor))
               .forEach(is -> {
                   try {
                       is.readAllBytes();
                   } catch (IOException e) {
                       throw new RuntimeException(e);
                   }
               })
               .onErrorResumeWithSingle(th -> {
                   if (th.getMessage().equals("Invalid state: END_MESSAGE")) {
                       // work-around for https://github.com/helidon-io/helidon/issues/6828
                       return Single.empty();
                   }
                   return Single.error(th);
               })
               .onError(req::next)
               .onComplete(res::send)
               .ignoreElement();
```
