### ISSUE TITLE
On rest call time out SocketTimeout exception is getting suppressed and InvocationInterceptorException is getting thrown

### ISSUE THREAD

**Issue by lakshmi-bhat** [helidon-io/helidon#6878]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3
* Helidon SE or Helidon MP: 3
* JDK version: 17
* OS: macOS Monterey
* Docker version (if applicable):
* helidon-jersey-client getting derived: 3.0.1

----------

## Problem Description
We are creating a rest client builder with read time out. So when rest call gets timeout we are expecting it to throw SocketTimeoutException but with Helidon 3 it is throwing InvocationInterceptorException by suppressing the original exception.

This issue is consistently reproducible.
Create a client with read timeout(preferably with less time)
          Client  client = ClientBuilder.newBuilder().register(ProcessingException.class).readTimeout(1,TimeUnit.MILLISECONDS).build();

Do a GET on rest endpoint
client.target(target).request().headers(<required-header>).header("Authorization", <auth>).get();

Previously this used to throw SocketTimeoutException, now this is throwing InvocationInterceptorException.

`org.glassfish.jersey.client.InvocationInterceptorStages$InvocationInterceptorException: Exceptions were thrown. See suppressed exceptions for the list.
`

`org.glassfish.jersey.client.InvocationInterceptorStages.createProcessingException(InvocationInterceptorStages.java:591), org.glassfish.jersey.client.InvocationInterceptorStages.suppressExceptions(InvocationInterceptorStages.java:604), org.glassfish.jersey.client.InvocationInterceptorStages.access$400(InvocationInterceptorStages.java:64), org.glassfish.jersey.client.InvocationInterceptorStages$PostInvocationInterceptorStage.afterRequestWithException(InvocationInterceptorStages.java:222), org.glassfish.jersey.client.InvocationInterceptorStages$PostInvocationInterceptorStage.afterRequestWithException(InvocationInterceptorStages.java:219), org.glassfish.jersey.client.InvocationInterceptorStages$PostInvocationInterceptorStage.afterRequest(InvocationInterceptorStages.java:243), org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:311), org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662), org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697), org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691), org.glassfish.jersey.internal.Errors.process(Errors.java:292), org.glassfish.jersey.internal.Errors.process(Errors.java:274), org.glassfish.jersey.internal.Errors.process(Errors.java:205), org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390), org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691), org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661), org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:413), org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313), com.oracle.osc.signals.utils.FARest.core.FARest.getFAResponse(FARest.java:275), com.oracle.osc.signals.utils.FARest.core.FARest.getRestResponse(FARest.java:151), com.oracle.osc.signals.utils.FARest.core.FARest$Proxy$_$$_WeldSubclass.getRestResponse$$super(Unknown Source), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:568), org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51), org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78), io.helidon.servicecommon.restcdi.InterceptionRunnerImpl.run(InterceptionRunnerImpl.java:102), io.helidon.servicecommon.restcdi.HelidonInterceptor$WithPostCompletion.aroundInvocation(HelidonInterceptor.java:179), io.helidon.servicecommon.restcdi.HelidonInterceptor$Base.aroundInvoke(HelidonInterceptor.java:136), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method), java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:568), org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73), org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84), org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72), org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56), org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79), org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68), com.oracle.osc.signals.utils.FARest.core.FARest$Proxy$_$$_WeldSubclass.getRestResponse(Unknown Source), com.oracle.osc.signals.utils.FARest.core.FARest$Proxy$_$$_WeldClientProxy.getRestResponse(Unknown Source), `

**Comment by spericas** [comment]
@lakshmi-bhat `ProcessingException` is a base class for exceptions in the API. Why are you registering when the client is built?

Regardless, the exception wrapping that I'm able to verify is as shown below, were `SocketTimeoutException` is wrapped by `ProcessingException` (don't really know if that has changed and it is the real cause of your problem).

```
2023.05.31 14:54:00 INFO io.helidon.common.HelidonFeatures Thread[#68,features-thread,5,main]: Helidon MP 3.2.1-SNAPSHOT features: [CDI, Config, Fault Tolerance, Health, JAX-RS, Metrics, Open API, REST Client, Security, Server, Tracing]
jakarta.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:270)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:675)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:674)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:422)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:318)
        at io.helidon.examples.quickstart.mp.MainTest.testHelloWorld(MainTest.java:56)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
        at io.helidon.examples.quickstart.mp.MainTest$Proxy$_$$_WeldClientProxy.testHelloWorld(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:117)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
        at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
        at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
        at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:273)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:299)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:258)
        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:313)
        at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:386)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:365)
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:828)
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:760)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1672)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:380)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:268)
        ... 88 more
2023.05.31 14:54:16 INFO io.helidon.webserver.NettyWebServer Thread[#67,nioEventLoopGroup-2-1,10,main]: Channel '@default' closed: [id: 0x2f926ce7, L:/[0:0:0:0:0:0:0:0]:60979]
```

**Comment by spericas** [comment]
Closing as there has been no follow-up in 2 weeks. Likely already resolved.
