### ISSUE TITLE
intermittent package test failure io.helidon.tests.integration.nativeimage.mp1.Mp1Main

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#6904]
Happens with either JAR packaging or JLink packaging.

```
FATAL: Endpoint /static/resource.txtshould return "classpath-resource-text", but returned ""
        at class io.helidon.tests.integration.nativeimage.mp1.Mp1Main
 	at io.helidon.common@3.2.1-SNAPSHOT/io.helidon.common.Errors.checkValid(Errors.java:183) Tests finished in 3236 millis 
	at helidon.tests.nimage.mp@3.2.1-SNAPSHOT/io.helidon.tests.integration.nativeimage.mp1.Mp1Main.testBean(Mp1Main.java:265)
 	at helidon.tests.nimage.mp@3.2.1-SNAPSHOT/io.helidon.tests.integration.nativeimage.mp1.Mp1Main.main(Mp1Main.java:103)
```

**Comment by romain-grecourt** [comment]
We may want to enable fine logging for `io.helidon.webserver.staticcontent` to start troubleshooting.

**Comment by romain-grecourt** [comment]
The test code is as follows:

```java
if (response.getStatus() == OK_200.code()) {
    String entity = response.readEntity(String.class);
    if (!expected.equals(entity)) {
        collector.fatal("Endpoint " + path + "should return \"" + expected + "\", but returned \"" + entity + "\"");
    }
} 
```

It's unlikely that a different server is answering as the log shows the process is able to listen on `7001`. Also the test code shows that we effectively got a `200` with an empty body.

When serving content from class-path the following is done:
- the requested class-path resources are extracted into temporary files during the first access
- the response payload is served from the temporary file (`Path` instance)

The empty payload could mean that when the temporary is read there is no content.

The following is used to extract the JAR entry:

```java
Files.copy(is, tempFile, StandardCopyOption.REPLACE_EXISTING);
```

The assumption is that when the statement above completes, the file content is available and ready to be used.
Could this assumption be false on some file systems ?

We could check that the number of bytes written matches the file size.

```java
long size = Files.copy(is, tempFile, StandardCopyOption.REPLACE_EXISTING);
if (Files.size(tempFile) != size) {
    throw new HttpException("Extracted size mismatch");
}
LOGGER.finest(() -> "Successfully extracted JAR entry, size: " + size);
```

**Comment by barchetta** [comment]
I just saw this on a PR validation run.

**Comment by tomas-langer** [comment]
Closing, as last update is 3 years ago
