### ISSUE TITLE
Helidon JEP290 filter should merge with already programmatically configured one

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6919]
Right now, if 3rd party library sets serialization filter over official API before Helidon sets its own, Helidons configuration is ignored.

## Environment Details
* Helidon Version: 3.x, 4.x

**Comment by tomas-langer** [comment]
I have just tried with Helidon 3 and it fails as expected:
in `main` of my quickstart:
```java
ObjectInputFilter filter = ObjectInputFilter.Config.createFilter("io.examples.helidon.nima.TheType");
ObjectInputFilter.Config.setSerialFilter(filter);
```

When I start webserver:
```
Exception in thread "main" java.lang.IllegalStateException: Custom JDK Serialization Filter is not configured to reject all classes. Helidon can only run with allow-list. Please add '!*' as the last pattern.
	at io.helidon.common.SerializationConfig.handleBadFilter(SerializationConfig.java:283)
	at io.helidon.common.SerializationConfig.validateExistingFilter(SerializationConfig.java:254)
	at io.helidon.common.SerializationConfig.doConfigure(SerializationConfig.java:217)
	at io.helidon.common.SerializationConfig.configureDefaults(SerializationConfig.java:138)
	at io.helidon.common.SerializationConfig.configureRuntime(SerializationConfig.java:129)
	at io.helidon.webserver.NettyWebServer.start(NettyWebServer.java:218)
	at me.tomas.se.quickstart.Main.startServer(Main.java:57)

```

**Comment by tomas-langer** [comment]
In helidon 4, we do not configureRuntime from Níma webserver, that need to be added
