### ISSUE TITLE
3.x intermittent test io.helidon.media.common.ReadableByteChannelPublisherTest.chunky

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#6950]
```java
Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.199 s <<< FAILURE! - in io.helidon.media.common.ReadableByteChannelPublisherTest
Error:  io.helidon.media.common.ReadableByteChannelPublisherTest.chunky  Time elapsed: 0.148 s  <<< FAILURE!
java.lang.AssertionError: 
Executor should have been shut down
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.media.common.ReadableByteChannelPublisherTest.chunky(ReadableByteChannelPublisherTest.java:92)
```

**Comment by barchetta** [comment]
Saw it on 3.x pipeline today.

**Comment by romain-grecourt** [comment]
https://github.com/helidon-io/helidon/actions/runs/5789611824/job/15691993480?pr=7328

**Comment by tomas-langer** [comment]
Closing as last update is 3 years ago
