### ISSUE TITLE
2.x:  Intermittent SubscriberPublMsgToPaylRetComplVoidBean test failure

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#6976]
## Environment Details
* Helidon Version: 2.6.2-SNAPSHOT
* Helidon MP
* JDK version: 2.x PR validation pipeline
----------

## Problem Description

I've seen this test fail on the 2.x pipeline. Maybe related to #4490 ?

```
 [INFO] Running io.helidon.microprofile.messaging.inner.ChannelTest
Error:  Tests run: 105, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.533 s <<< FAILURE! - in io.helidon.microprofile.messaging.inner.ChannelTest
Error:  io.helidon.microprofile.messaging.inner.ChannelTest.innerChannelBeanTest(CdiTestCase)[9]  Time elapsed: 0.075 s  <<< FAILURE!
java.lang.AssertionError: 
Result doesn't match at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToPaylRetComplVoidBean.assertValid(SubscriberPublMsgToPaylRetComplVoidBean.java:61)
Expected: is <[TEst2, tESt3, teST1]>
     but: was <[]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.microprofile.messaging.AssertableTestBean.assertWithOrigin(AssertableTestBean.java:60)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToPaylRetComplVoidBean.assertValid(SubscriberPublMsgToPaylRetComplVoidBean.java:61)
	at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToPaylRetComplVoidBean$Proxy$_$$_WeldClientProxy.assertValid(Unknown Source)
```

**Comment by barchetta** [comment]
Still seeing intermittently on 2.x pipeline.

```
17:35:07,265 [INFO] Running io.helidon.microprofile.messaging.inner.ChannelTest
Error: 2,684 [ERROR] Tests run: 105, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.412 s <<< FAILURE! - in io.helidon.microprofile.messaging.inner.ChannelTest
Error: 2,685 [ERROR] io.helidon.microprofile.messaging.inner.ChannelTest.innerChannelBeanTest(CdiTestCase)[38]  Time elapsed: 0.06 s  <<< FAILURE!
java.lang.AssertionError: 
Result doesn't match at io.helidon.microprofile.messaging.inner.subscriber.SubscriberPublMsgToPaylRetComplVoidBean.assertValid(SubscriberPublMsgToPaylRetComplVoidBean.java:61)
Expected: is <[TEst2, tESt3, teST1]>
     but: was <[TEst2, tESt3]>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.microprofile.messaging.AssertableTestBean.assertWithOrigin(AssertableTestBean.java:60)
```
