### ISSUE TITLE
io.helidon.messaging.connectors.jms.AckMpTest randomly fails

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#7011]
I saw this test failure several times, restarting the job usually helps.
```
[INFO] Running io.helidon.messaging.connectors.jms.AckMpTest
2023.06.15 09:57:15 INFO io.helidon.microprofile.cdi.HelidonContainerImpl Thread[#22,helidon-cdi-shutdown-hook,5,main]: Shutdown requested by JVM shutting down
2023.06.15 09:57:15 INFO io.helidon.nima.webserver.ServerListener Thread[#27,server-@default-listener,5,main]: [0x75af79bc] @default socket closed.
2023.06.15 09:57:15 INFO io.helidon.nima.webserver.LoomServer Thread[#22,helidon-cdi-shutdown-hook,5,main]: Níma server stopped all channels.
2023.06.15 09:57:15 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#22,helidon-cdi-shutdown-hook,5,main]: Server stopped in 8 milliseconds.
2023.06.15 09:57:15 INFO io.helidon.microprofile.cdi.HelidonContainerImpl Thread[#22,helidon-cdi-shutdown-hook,5,main]: Shutdown finished
[INFO] Async process complete, exit value = 0 for: [java, --enable-preview, -jar, /tmp/maven-exec15510170939562921931.jar, -classpath]
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.693 s <<< FAILURE! - in io.helidon.messaging.connectors.jms.AckMpTest
Error:  io.helidon.messaging.connectors.jms.AckMpTest.resendAckTestPart2(SeContainer)  Time elapsed: 5.185 s  <<< FAILURE!
java.lang.AssertionError: 
Not all 3 items delivered in time.
Expected: iterable containing ["NO_ACK-1", "NO_ACK-2", "NO_ACK-3"]
     but: item 0: was "NO_ACK-2"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.messaging.connectors.mock.MockOutgoing.awaitData(MockOutgoing.java:166)
	at io.helidon.messaging.connectors.mock.MockOutgoing.awaitPayloads(MockOutgoing.java:194)
	at io.helidon.messaging.connectors.jms.AckMpTest.resendAckTestPart2(AckMpTest.java:116)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:117)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```
Last time I saw it in PR #6959
https://github.com/helidon-io/helidon/actions/runs/5277095950/jobs/9544670221?pr=6959

Tested locally on the same branch (from PR) and test passed.

**Comment by jbescos** [comment]
`NO_ACK-1` is lost, but we still receive `NO_ACK-2, NO_ACK-3`. I don't know the details, but my first guess is that message with `NO_ACK-1` is sent and there is no handler registered yet to process it.

**Comment by tomas-langer** [comment]
Same problem...

**Comment by tjquinno** [comment]
+1 for me just now

**Comment by barchetta** [comment]
Still seeing this fail pretty often on the 4.0.x maintenance release branches.

**Comment by barchetta** [comment]
Still seeing this in the 4.1.x maintenance release branch.

**Comment by barchetta** [comment]
Still seeing this in `helidon-3.x` branch

**Comment by tomas-langer** [comment]
Moving to triage, as this is blocking too many builds.

**Comment by romain-grecourt** [comment]
Looking at the post merge jobs on the commit history of the main branch, this test fails quite often.

**Comment by tomas-langer** [comment]
Failed again:
```
Error:  io.helidon.messaging.connectors.jms.AckMpTest.resendAckTestPart2(SeContainer)  Time elapsed: 5.172 s  <<< FAILURE!
java.lang.AssertionError: 
Not all 3 items delivered in time.
Expected: iterable containing ["NO_ACK-1", "NO_ACK-2", "NO_ACK-3"]
     but: item 0: was "NO_ACK-2"
```

**Comment by tomas-langer** [comment]
And once again today.

**Comment by ljnelson** [comment]
Same

**Comment by jbescos** [comment]
Issue is that the JMS connector is stopped in between, and NO_ACK-1 is lost:

```
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockConnector Thread[#1,main,5,main]: Creating mock outgoing for channel: mock-conn-channel
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#1,main,5,main]: Requesting 6 items
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#92,jms-poll-1,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@2597fc4
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#92,jms-poll-1,5,main]: Received 0
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#92,jms-poll-1,5,main]: Acked 0
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#92,jms-poll-1,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@59a05cb6
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#93,jms-poll-2,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@1769512c
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#93,jms-poll-2,5,main]: Received 1
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#93,jms-poll-2,5,main]: Acked 1
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#93,jms-poll-2,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@1d913a5c
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#92,jms-poll-1,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@4a72bc16
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#92,jms-poll-1,5,main]: Received 2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#92,jms-poll-1,5,main]: Acked 2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#92,jms-poll-1,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@614ec186
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#98,jms-poll-3,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@18adfef4
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#98,jms-poll-3,5,main]: Received NO_ACK-1
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#98,jms-poll-3,5,main]: NOT Acked NO_ACK-1
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#98,jms-poll-3,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@575719aa
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#93,jms-poll-2,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@5ae6d85
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#93,jms-poll-2,5,main]: Received NO_ACK-2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#93,jms-poll-2,5,main]: NOT Acked NO_ACK-2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#93,jms-poll-2,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@7d568f02
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#99,jms-poll-4,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@6837e06a
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#99,jms-poll-4,5,main]: Received NO_ACK-3
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#99,jms-poll-4,5,main]: NOT Acked NO_ACK-3
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#99,jms-poll-4,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@62cf8b1a
**2025.08.04 08:21:22 INFO io.helidon.messaging.connectors.jms.JmsConnector Thread[#1,main,5,main]: JMS Connector gracefully stopped.**
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockConnector Thread[#1,main,5,main]: Creating mock outgoing for channel: mock-conn-channel
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#134,jms-poll-1,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@131306da
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#134,jms-poll-1,5,main]: Received NO_ACK-2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#134,jms-poll-1,5,main]: NOT Acked NO_ACK-2
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#1,main,5,main]: Requesting 9,223,372,036,854,775,807 items
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#1,main,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@57ce2898
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#1,main,5,main]: Requesting 3 items
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.JmsConnector Thread[#134,jms-poll-1,5,main]: Received message: io.helidon.messaging.connectors.jms.shim.JakartaTextMessage@5ce9f0f3
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#134,jms-poll-1,5,main]: Received NO_ACK-3
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.jms.AckMpTest Thread[#134,jms-poll-1,5,main]: NOT Acked NO_ACK-3
2025.08.04 08:21:22 FINE io.helidon.messaging.connectors.mock.MockSubscriber Thread[#134,jms-poll-1,5,main]: Received item: io.helidon.messaging.connectors.jms.JmsTextMessage@6d7faaf8
2025.08.04 08:21:27 INFO io.helidon.messaging.connectors.jms.JmsConnector Thread[#1,main,5,main]: JMS Connector gracefully stopped.
```

**Comment by jbescos** [comment]
I am debugging this, and the ACK stuff happens within ActiveMQ. I upgraded the version and I am running the test tens of times and it looks the error is not happening so far. I will keep it running for some hours and lets see.

**Comment by tjquinno** [comment]
+1

**Comment by ljnelson** [comment]
Just hit this [today](https://github.com/helidon-io/helidon/actions/runs/17134550314/job/48607621726?pr=10584#step:3:1109)

**Comment by ljnelson** [comment]
And again

**Comment by tjquinno** [comment]
Back again. https://github.com/helidon-io/helidon/actions/runs/19249220028/job/55109127877?pr=10823#step:3:1100

**Comment by danielkec** [comment]
Finally I know what is happening here! Ack of `1` gets dealyed beond reception of `NO_ACK-1` and because ActiveMQ using offset mechanism `NO_ACK-1` gets acked too!
```
got0
acked 0
got1
acked 1
got2
gotNO_ACK-1
acked 2
gotNO_ACK-2
gotNO_ACK-3
```
