### ISSUE TITLE
[4.x] gRPC broken class loading when specifying protobuf package name

### ISSUE THREAD

**Issue by edvardfagerholmsc** [helidon-io/helidon#7016]
The following test program:

```java
package io.github.efagerho.loom;

import static io.helidon.nima.grpc.webserver.ResponseHelper.complete;

import io.github.efagerho.loom.grpc.Echo;
import io.github.efagerho.loom.grpc.HelloRequest;
import io.github.efagerho.loom.grpc.HelloResponse;
import io.grpc.stub.StreamObserver;
import io.helidon.logging.common.LogConfig;
import io.helidon.nima.grpc.webserver.GrpcRouting;
import io.helidon.nima.webserver.WebServer;

public class ServerMain {

    private static void hello(HelloRequest request, StreamObserver<HelloResponse> observer) {
        System.out.println("Handler called");
        String name = request.getName();
        complete(observer, HelloResponse.newBuilder().setResponse(String.format("Hello %s", name)).build());
    }

    public static void main(String[] args) {
        LogConfig.configureRuntime();

        WebServer ws = WebServer
            .builder()
            .port(8080)
            .addRouting(GrpcRouting.builder().unary(Echo.getDescriptor(), "EchoService", "Hello", ServerMain::hello)).build();

        System.out.format("gRPC endpoint configured with tls = %b\n", ws.hasTls());
        ws.start();
    }
}
```

Works with the .proto file below:

```
syntax = "proto3";

option java_multiple_files = true;
option java_package = "io.github.efagerho.loom.grpc";

service EchoService {
  rpc Hello (HelloRequest) returns (HelloResponse) {}
}

message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string response = 1;
}
```

Some gRPC libraries like Rust's Tonic require a package name for the proto. However, if I modify the proto file by adding a `package echo;` declaration, then the Helidon Java server will fail to start with the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Failed to load class "io.github.efagerho.loom.grpc.echo$HelloRequest" for grpc
        at io.helidon.nima.grpc.webserver.Grpc.load(Grpc.java:141)
        at io.helidon.nima.grpc.webserver.Grpc.grpc(Grpc.java:122)
        at io.helidon.nima.grpc.webserver.Grpc.unary(Grpc.java:53)
        at io.helidon.nima.grpc.webserver.GrpcRouting$Builder.unary(GrpcRouting.java:125)
        at io.github.efagerho.loom.ServerMain.main(ServerMain.java:27)
Caused by: java.lang.ClassNotFoundException: io.github.efagerho.loom.grpc.echo$HelloRequest
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.helidon.nima.grpc.webserver.Grpc.load(Grpc.java:139)
        ... 4 more
``` 

It looks like protobuf package name is appended to the classpath before loading. Is there a way to work around as otherwise it's impossible to interoperate with certain clients? Integration tests all use the "string.proto" file which does not specify a package name either.

**Comment by edvardfagerholmsc** [comment]
The problem here is that without th proto package specification, the gRPC URI for Hello is:

/EchoService/Hello

If you add "package echo;" to the proto file, then the URI becomes:

/echo.EchoService/Hello

so just maintaining separate .proto files with and without the package definition for different languages when compiling is not a solution.

**Comment by efagerho** [comment]
Had time in the evening to look at the code. The following [code](https://github.com/helidon-io/helidon/blob/main/nima/grpc/webserver/src/main/java/io/helidon/nima/grpc/webserver/Grpc.java#LL111C19-L111C19) is used to load the class:

```java
Descriptors.ServiceDescriptor svc = proto.findServiceByName(serviceName);
Descriptors.MethodDescriptor mtd = svc.findMethodByName(methodName);
String pkg = proto.getOptions().getJavaPackage();
pkg = "".equals(pkg) ? proto.getPackage() : pkg;
String outerClass = getOuterClass(proto);

Class<ReqT> requestType = load(pkg + "." + outerClass + mtd.getInputType().getFullName().replace('.', '$'));
Class<ResT> responsetype = load(pkg + "." + outerClass + mtd.getOutputType().getFullName().replace('.', '$'));
```

I wrote the following test:

```java
Descriptors.FileDescriptor proto = Echo.getDescriptor();
Descriptors.ServiceDescriptor svcName = proto.findServiceByName("EchoService");
Descriptors.MethodDescriptor mtd = svcName.findMethodByName("Hello");

String pkg = proto.getOptions().getJavaPackage();
System.out.println("pkg: " + pkg);
String outerClass = getOuterClass(proto);
System.out.println("outerClass: " + outerClass);
String inputTypeName = mtd.getInputType().getName();
System.out.println("inputTypeName: " + inputTypeName);
String inputTypeFullName = mtd.getInputType().getFullName();
System.out.println("inputTypeFullName: " + inputTypeFullName);
```

which prints:

```
pkg: io.github.efagerho.loom.grpc
outerClass: 
inputTypeName: HelloRequest
inputTypeFullName: echo.HelloRequest
```

A potential fix would be to call `getName()` instead of `getFullName()`, since it produces the correct Java package name. However, I'm not sure if it might break some other common case.

**Comment by efagerho** [comment]
The above small PR should fix the problem. I didn't have time to setup importing of my own fork in my build system to test it out, so the code is completely untested. Hopefully, someone on your end can do a proper patch, since this is blocking me at the moment.

**Comment by efagerho** [comment]
Now tested by compiling 4.0.0-SNAPSHOT with the above patch applied and it does fix the issue.
