### ISSUE TITLE
HelidonContainerInitializer#addPackages is not picking the beans

### ISSUE THREAD

**Issue by jbescos** [helidon-io/helidon#7017]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.0-SNAPSHOT
* Helidon MP
* JDK version: Java(TM) SE Runtime Environment (build 20.0.1+9-29)
* OS: Linux

----------

## Problem Description

Many CDI TCKs are failing because of this.

In the next test, the method `packages()` doesn't work:
```
public class ReproducerTest {

    @Test
    public void packages() {
        try (SeContainer container = SeContainerInitializer
                .newInstance()
                .addPackages(true, Car.class)
                .initialize();) {
            Car car = container.select(Car.class).get();
            assertNotNull(car);
        }
    }

    @Test
    public void bean() {
        try (SeContainer container = SeContainerInitializer
                .newInstance()
                .addBeanClasses(Car.class)
                .initialize();) {
            Car car = container.select(Car.class).get();
            assertNotNull(car);
        }
    }
}
```

## Steps to reproduce
```
git clone https://github.com/jbescos/Questions.git
cd Questions/helidon-addPackages
mvn clean install
```

Output:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.124 s <<< FAILURE! -- in com.example.issue.ReproducerTest
[ERROR] com.example.issue.ReproducerTest.packages -- Time elapsed: 0.155 s <<< ERROR!
org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type Car with qualifiers  
	at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:251)
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113)
	at com.example.issue.ReproducerTest.packages(ReproducerTest.java:19)
```

**Comment by jbescos** [comment]
I am debugging this and there is one difference. For `addPackages` it searches for annotations in the beans (the test Car.class is not annotated) in case the `beans.xml` is `annotated`. So that test is fixed annotating the `Car.class` or adding `all` in the `beans.xml`.

However in some TCK tests it is failing. I am investigating it further.

**Comment by jbescos** [comment]
It seems it is not an issue
