### ISSUE TITLE
OpenApi AOT fails with Graal GraalVM 22.x.r19

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#7036]
Reproduced after being reported by @mraible in https://github.com/helidon-io/helidon/issues/6284#issuecomment-1595792574

## Environment Details
* Helidon Version: 3.2.1
* Helidon MP
* JDK version: 22.3.1.r19-grl
* OS: Ubuntu 23.04 - 6.2.0-23.23-generic 6.2.12

----------

## Problem Description
```shell
Error: Classes that should be initialized at run time got initialized during image building:
 com.sun.beans.TypeResolver was unintentionally initialized at build time. To see why com.sun.beans.TypeResolver got initialized use --trace-class-initialization=com.sun.beans.TypeResolver
To see how the classes got initialized, use --trace-class-initialization=com.sun.beans.TypeResolver
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```
With `--trace-class-initialization=com.sun.beans.TypeResolver`:
```shell
Error: Classes that should be initialized at run time got initialized during image building:
 com.sun.beans.TypeResolver was unintentionally initialized at build time. io.helidon.openapi.ExpandedTypeDescription$SchemaTypeDescription caused initialization of this class with the following trace: 
        at com.sun.beans.TypeResolver.<clinit>(TypeResolver.java:47)
        at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:391)
        at java.beans.PropertyDescriptor.findPropertyType(PropertyDescriptor.java:681)
        at java.beans.PropertyDescriptor.setReadMethod(PropertyDescriptor.java:281)
        at java.beans.PropertyDescriptor.<init>(PropertyDescriptor.java:141)
        at io.helidon.openapi.ExpandedTypeDescription$SchemaTypeDescription.preparePropertyDescriptor(ExpandedTypeDescription.java:286)
        at io.helidon.openapi.ExpandedTypeDescription$SchemaTypeDescription.<clinit>(ExpandedTypeDescription.java:255)

```

## Steps to reproduce
```bash
helidon init --flavor MP --groupid com.okta.rest \
  --artifactid helidon --package com.okta.rest
```
```
mvn package -Pnative-image
```

**Comment by danielkec** [comment]
Workaround:
```diff
Index: helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties b/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties
--- a/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties	(revision 1536ded03974fc455762ee4ae3fbf09d4a1d29cb)
+++ b/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties	(date 1687349409382)
@@ -1,1 +1,3 @@
-Args=--initialize-at-build-time=com.okta.rest
+Args=--trace-class-initialization=com.sun.beans.TypeResolver \
+  --initialize-at-build-time=com.okta.rest \
+  --initialize-at-run-time=io.helidon.openapi.ExpandedTypeDescription
```

**Comment by mraible** [comment]
@danielkec I just discovered it only fixes the problem if I remove the dependencies as you did in https://github.com/oktadev/auth0-java-rest-api-examples/pull/2. Is it possible to keep these dependencies and have compilation succeed on Java 19 and 20?

**Comment by danielkec** [comment]
@mraible Yes with this compilation succeeds with all the features in on 22.3.1.r19-grl:
```diff
Index: helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties b/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties
--- a/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties	(revision 1536ded03974fc455762ee4ae3fbf09d4a1d29cb)
+++ b/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties	(date 1687348599487)
@@ -1,1 +1,3 @@
-Args=--initialize-at-build-time=com.okta.rest
+Args=--initialize-at-build-time=com.okta.rest \
+  --initialize-at-run-time=io.helidon.openapi.ExpandedTypeDescription \
+  --report-unsupported-elements-at-runtime
\ No newline at end of file

```

**Comment by mraible** [comment]
@danielkec You are correct. Thank you!
