### ISSUE TITLE
Error handling of invalid content-type

### ISSUE THREAD

**Issue by janotav** [helidon-io/helidon#7053]
## Environment Details
* Helidon Version: 2.6.0
* Helidon SE
* JDK version: 17
* OS: Linux
* Docker version (if applicable):

----------

## Problem Description
Sending POST request  with invalid content-type `%{bad actor}`

Leads to  `java.lang.IllegalArgumentException` in the server log and on the client side the observed behaviour is:
* 400 Bad Request
* content: `Could not parse &#x27;%{bad actor}&#x27;`

## Expected  behaviour

We would like to:
* be able to control response status & content
* avoid  `Unexpected error occurred during routing!` exception in our server log

Is that currently possible? If not, can this be added?

**Comment by tomas-langer** [comment]
To create a custom response for "pre-routing" errors, such as bad request, you can add a `DirectHandler`.
See `WebServer.Builder.directHandler(DirectHandler handler, DirectHandler.EvenType... types)`

You direct hanlder will get as much information as could be retrieved from the request, and you can create a customized response to be sent back.

**Comment by tomas-langer** [comment]
For the part about not seeing the error in your logs, could you share the stacktrace of that exception please (I plan to split it into a new issue, so if you are OK with creating a new issue specifically for the error in the logs, it would be nice).

Thanks

**Comment by janotav** [comment]
Here is full stack:

```
java.lang.IllegalArgumentException: Could not parse '%{#context['com.opensymphony.xwork2.dispatcher.HttpServletResponse'].addHeader('X-Tenable','rtgKIzqK')}.multipart/form-data'
at io.helidon.common.http.MediaType.parse(MediaType.java:360)
at java.base/java.util.Optional.map(Optional.java:260)
at io.helidon.webserver.HashRequestHeaders.contentType(HashRequestHeaders.java:82)
at io.helidon.webserver.Request.<init>(Request.java:90)
at io.helidon.webserver.RequestRouting$RoutedRequest.<init>(RequestRouting.java:255)
at io.helidon.webserver.RequestRouting.route(RequestRouting.java:86)
at io.helidon.webserver.ForwardingHandler.lambda$channelReadHttpRequest$17(ForwardingHandler.java:470)
at io.helidon.webserver.RequestContext.lambda$runInScope$4(RequestContext.java:77)
at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
at io.helidon.webserver.RequestContext.runInScope(RequestContext.java:75)
at io.helidon.webserver.ForwardingHandler.channelReadHttpRequest(ForwardingHandler.java:470)
at io.helidon.webserver.ForwardingHandler.lambda$channelRead0$3(ForwardingHandler.java:166)
at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:165)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.IllegalStateException: Unexpected character: /
at io.helidon.common.http.Tokenizer.checkState(Tokenizer.java:173)
at io.helidon.common.http.Tokenizer.consumeCharacter(Tokenizer.java:109)
at io.helidon.common.http.MediaType.parse(MediaType.java:326) ... 44 more

```

**Comment by tomas-langer** [comment]
Example of a direct handler that maps bad requests to not found:
```
DirectHandler badRequestHandler = (transportRequest, eventType, responseStatus, message) -> DirectHandler.TransportResponse.builder()
                .status(Http.Status.NOT_FOUND_404)
                .entity("Endpoint not found")
                .build();
```

The exception is still written to the log, As that error is handled elsewhere, the message should not be printed. I will create an issue for it.

**Comment by tomas-langer** [comment]
Submitted an issue for the logging problem. I will close this one as I have answered how to customize the response for bad requests.
