### ISSUE TITLE
4.x Nima WebClient Response did not contain HTTP status line. Line: HTTP/1.1

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7223]
* Helidon Version: 4.0.0-M1

----------

Reproducer:

```java
Http1Client client = Http1Client.builder()
        .baseUri("http://localhost:8080")
        .build();
WebServer.builder()
        .port(8080)
        .routing(it -> it
                .get("/status/{code}", ((req, res) -> {
                    int code = Integer.parseInt(req.path().pathParameters().value("code"));
                    res.status(code);
                    res.send();
                }))
                .get("/{code}", (req, res) -> {
                    int code = Integer.parseInt(req.path().pathParameters().value("code"));
                    try (Http1ClientResponse clientRes = client.get("/status/" + code).request()) {
                        res.send("got : " + clientRes.status().code());
                    }
                }))
        .build()
        .start();
```

```bash
curl -vv http://localhost:8080/210       
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /210 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 18 Jul 2023 21:59:42 -0700
< Connection: keep-alive
< Content-Length: 453
< Content-Type: text/plain
< 
HTTP Response did not contain HTTP status line. Line: HTTP/1.1
+--------+-------------------------------------------------+----------------+
|   index|  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |            data|
+--------+-------------------------------------------------+----------------+
|00000000| 32 31 30                                        |210             |
+--------+-------------------------------------------------+----------------+
* Connection #0 to host localhost left intact
```

Server logs:
```
Jul 18, 2023 9:59:43 PM io.helidon.nima.webserver.http.DirectHandlers handle
WARNING: Internal server error
io.helidon.common.http.RequestException: HTTP Response did not contain HTTP status line. Line: HTTP/1.1
+--------+-------------------------------------------------+----------------+
|   index|  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |            data|
+--------+-------------------------------------------------+----------------+
|00000000| 32 31 30                                        |210             |
+--------+-------------------------------------------------+----------------+

	at io.helidon.common.http.RequestException$Builder.build(RequestException.java:139)
	at io.helidon.nima.webserver.http.ErrorHandlers.unhandledError(ErrorHandlers.java:201)
	at io.helidon.nima.webserver.http.ErrorHandlers.lambda$handleError$1(ErrorHandlers.java:181)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
	at io.helidon.nima.webserver.http.ErrorHandlers.handleError(ErrorHandlers.java:180)
	at io.helidon.nima.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:118)
	at io.helidon.nima.webserver.http.Filters.filter(Filters.java:77)
	at io.helidon.nima.webserver.http.HttpRouting.route(HttpRouting.java:108)
	at io.helidon.nima.webserver.http1.Http1Connection.route(Http1Connection.java:263)
	at io.helidon.nima.webserver.http1.Http1Connection.handle(Http1Connection.java:145)
	at io.helidon.nima.webserver.ConnectionHandler.run(ConnectionHandler.java:107)
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
	at io.helidon.nima.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:305)
	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:177)
	at java.base/jdk.internal.vm.Continuation.enter0(Continuation.java:327)
	at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:320)
Caused by: java.lang.IllegalStateException: HTTP Response did not contain HTTP status line. Line: HTTP/1.1
+--------+-------------------------------------------------+----------------+
|   index|  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |            data|
+--------+-------------------------------------------------+----------------+
|00000000| 32 31 30                                        |210             |
+--------+-------------------------------------------------+----------------+

	at io.helidon.nima.webclient.http1.Http1StatusParser.readStatus(Http1StatusParser.java:85)
	at io.helidon.nima.webclient.http1.HttpCallEntityChain.doProceed(HttpCallEntityChain.java:86)
	at io.helidon.nima.webclient.http1.HttpCallChainBase.proceed(HttpCallChainBase.java:81)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.invokeServices(ClientRequestImpl.java:416)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.invokeRequestWithEntity(ClientRequestImpl.java:354)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.invokeWithFollowRedirectsEntity(ClientRequestImpl.java:302)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.submit(ClientRequestImpl.java:200)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.request(ClientRequestImpl.java:191)
	at io.helidon.nima.webclient.http1.ClientRequestImpl.request(ClientRequestImpl.java:52)
	at io.helidon.examples.quickstart.se.Main.lambda$main$1(Main.java:69)
	at io.helidon.nima.webserver.http.HttpRouting$RoutingExecutor.doRoute(HttpRouting.java:553)
	at io.helidon.nima.webserver.http.HttpRouting$RoutingExecutor.call(HttpRouting.java:512)
	at io.helidon.nima.webserver.http.HttpRouting$RoutingExecutor.call(HttpRouting.java:490)
	at io.helidon.nima.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
	... 11 more
```

**Comment by tomas-langer** [comment]
This is actually a problem with the `Http.Status.create(int)`, where we have an empty reason phrase (as 210 is not part of our enum)

**Comment by tomas-langer** [comment]
Fixing in `Http1ServerResposne.nonEntityByte()`, where we just sent code without reason phrase in this case
