### ISSUE TITLE
4.x: Flaky TracingPropagationTest.testTracingSuccess test

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#7369]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: main

----------

## Problem Description
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.161 s <<< FAILURE! - in io.helidon.tests.integration.webclient.TracingPropagationTest
Error:  io.helidon.tests.integration.webclient.TracingPropagationTest.testTracingSuccess  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: 
There should be 2 spans reported
Expected: a collection with size <2>
     but: collection size was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.tests.integration.webclient.TracingPropagationTest.testTracingSuccess(TracingPropagationTest.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:118)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
```

**Comment by danielkec** [comment]
![image](https://github.com/helidon-io/helidon/assets/1773630/faa3a095-5e5a-4c57-b075-d75694f91c2e)

**Comment by barchetta** [comment]
I am still seeing this failure in the pipeline. I see the above PR was closed and not merged. Was that intentional?

```
[INFO] Running io.helidon.webclient.tests.TracingPropagationTest
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.154 s <<< FAILURE! - in io.helidon.webclient.tests.TracingPropagationTest
Error:  io.helidon.webclient.tests.TracingPropagationTest.testTracingSuccess  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.AssertionError: 
There should be 2 spans reported
Expected: a collection with size <2>
     but: collection size was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at io.helidon.webclient.tests.TracingPropagationTest.testTracingSuccess(TracingPropagationTest.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestMethod(InvocationInterceptor.java:118)
	at 
```

**Comment by dalexandrov** [comment]
Looks like my previous commit was somehow not included in `main`. Another PR submitted.

**Comment by danielkec** [comment]
Still there 
![image](https://github.com/helidon-io/helidon/assets/1773630/f5d1d1b8-9703-44c6-a594-62c0644b27f1)

**Comment by dalexandrov** [comment]
Please approve https://github.com/helidon-io/helidon/pull/7489
