### ISSUE TITLE
ConcurrentModificationException in Http2ClientConnection.writeWindowsUpdate

### ISSUE THREAD

**Issue by Tomas-Kraus** [helidon-io/helidon#7385]
I saw this as random test failure:
```
Error:  Errors: 
Error:    Http2WebClientTest.multiplexParallelStreamsGet:286 » Execution java.util.ConcurrentModificationException
```
And whole stack trace is here:
```
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at io.helidon.nima.http2.webclient.Http2WebClientTest.multiplexParallelStreamsGet(Http2WebClientTest.java:286)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        ...
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1633)
	at io.helidon.nima.http2.webclient.Http2ClientConnection.writeWindowsUpdate(Http2ClientConnection.java:269)
	at io.helidon.nima.http2.WindowSizeImpl$Strategy$Simple.windowUpdate(WindowSizeImpl.java:297)
	at io.helidon.nima.http2.WindowSizeImpl$Inbound.incrementWindowSize(WindowSizeImpl.java:114)
	at io.helidon.nima.http2.FlowControlImpl$Inbound.incrementWindowSize(FlowControlImpl.java:117)
	at io.helidon.nima.http2.webclient.Http2ClientStream.data(Http2ClientStream.java:149)
	at io.helidon.nima.http2.webclient.Http2ClientStream.readOne(Http2ClientStream.java:296)
	at io.helidon.nima.http2.webclient.Http2ClientStream.read(Http2ClientStream.java:210)
	at io.helidon.nima.http2.webclient.Http2ClientStream.read(Http2ClientStream.java:205)
	at io.helidon.nima.http2.webclient.Http2CallChainBase$RequestingInputStream.ensureBuffer(Http2CallChainBase.java:291)
	at io.helidon.nima.http2.webclient.Http2CallChainBase$RequestingInputStream.read(Http2CallChainBase.java:279)
	at java.base/java.io.InputStream.read(InputStream.java:220)
	at io.helidon.nima.http2.webclient.Http2ClientResponseImpl.readBytes(Http2ClientResponseImpl.java:94)
	at io.helidon.nima.http.media.ReadableEntityBase$RequestingInputStream.ensureBuffer(ReadableEntityBase.java:238)
	at io.helidon.nima.http.media.ReadableEntityBase$RequestingInputStream.read(ReadableEntityBase.java:226)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:412)
	at io.helidon.nima.http2.webclient.Http2WebClientTest.lambda$multiplexParallelStreamsGet$16(Http2WebClientTest.java:268)
	at io.helidon.nima.http2.webclient.Http2WebClientTest.lambda$multiplexParallelStreamsGet$18(Http2WebClientTest.java:283)
```

**Comment by Tomas-Kraus** [comment]
https://github.com/helidon-io/helidon/actions/runs/5878010877/job/15939237180?pr=6959

**Comment by jbescos** [comment]
To reproduce it easily, add the next Thread.sleep in `Http2ClientConnection#writeWindowsUpdate`:
```
    private void writeWindowsUpdate(int streamId, Http2WindowUpdate windowUpdateFrame) {
        if (streamId == 0){
            writer.write(windowUpdateFrame.toFrameData(serverSettings, streamId, Http2Flag.NoFlags.create()));
            return;
        }
        if (streamId < lastStreamId) {
            for (var s : streams.values()) {
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                if (s.streamId() > streamId && s.streamState() != Http2StreamState.IDLE) {
                    // RC against parallel newer streams, data already buffered at client being read
                    // There is no need to do request for more data as stream is no more usable
                    return;
                }
            }
        }
        Http2ClientStream stream = stream(streamId);
        if (stream != null && !stream.streamState().equals(Http2StreamState.CLOSED)) {
            writer.write(windowUpdateFrame.toFrameData(serverSettings, streamId, Http2Flag.NoFlags.create()));
        }
    }
```

**Comment by jbescos** [comment]
https://github.com/helidon-io/helidon/pull/7395 merged
