### ISSUE TITLE
4.x: small archetype issues

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7446]
Minor issues found while testing the 4.0 archetypes:

database-mp
- [x] README says "that uses the dbclient API". This uses JPA.

quickstart-se
- [x] README: health URL uses `PORT` instead of 8080. This is different from all other urls in the README
- [x] pom has two copies of dependencies for helidon-webserver-observe-health and helidon-health-checks
- [x] Exception when test runs:
```
2023.08.24 11:05:46.430 Attempt to start in unexpected state state STARTED; ignored
java.lang.IllegalStateException
        at io.helidon.metrics.PeriodicExecutor.lambda$startExecutor$1(PeriodicExecutor.java:139)
        at io.helidon.metrics.PeriodicExecutor.sync(PeriodicExecutor.java:175)
        at io.helidon.metrics.PeriodicExecutor.startExecutor(PeriodicExecutor.java:124)
        at io.helidon.metrics.PeriodicExecutor.start(PeriodicExecutor.java:91)
        at io.helidon.metrics.RegistryFactory.start(RegistryFactory.java:199)
        at io.helidon.webserver.observe.metrics.MetricsFeature.beforeStart(MetricsFeature.java:166)
```

**Comment by tvallin** [comment]
Fixed by #7459
