### ISSUE TITLE
Gradle jandex fails when using Enums

### ISSUE THREAD

**Issue by DaveO-Home** [helidon-io/helidon#7659]
## Environment Details
* Helidon Version: 4.0.0-m2
* Helidon SE or Helidon MP - MP
* JDK version: 21
* OS: Linux - Fedora
* Docker version (if applicable):

----------

## Problem Description
When using an Enum like:
```
private enum DbTypes {
        POSTGRES("postgres"), SQLITE3("sqlite3"), CUBRID("cubrid"), MARIADB("mariadb"), IBMDB2(
                "ibmdb2"), CASSANDRA("cassandra"), FIREBASE("firebase"), NEO4J("neo4j");

        final String db;

        DbTypes(String db) {
            this.db = db;
        }
    }
```

`gradlew clean run --stacktrace` produces:
```
 at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: java.lang.NullPointerException: Cannot read the array length because "bytes" is null
        at org.jboss.jandex.IndexWriterV2.writeByteTable(IndexWriterV2.java:259)
        at org.jboss.jandex.IndexWriterV2.write(IndexWriterV2.java:200)
        at org.jboss.jandex.IndexWriter.write(IndexWriter.java:102)
        at org.jboss.jandex.IndexWriter.write(IndexWriter.java:66)
        at org.kordamp.gradle.plugin.jandex.tasks.JandexWorkAction.execute(JandexWorkAction.groovy:70)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
``` 
By removing the Enum the Service starts as expected. Note, running `helidon dev` or `mvn package` works.

Can be easily reproduce by including an Enum in any class.

## Steps to reproduce
Simply include an enum in code

Same error with either and with both commented;
```
runtimeOnly "io.smallrye:jandex"
runtimeOnly 'org.jboss:jandex:3.1.3'
```
however the plugin always uses `jboss`.

**Comment by DaveO-Home** [comment]
This may be resolved by including in build.gradle
```
jandex {
    version = '3.1.5'
}
```
