### ISSUE TITLE
[4.x] NPE in HelidonFeatures at startup on uberjar'ed & AOT http-server (clj)

### ISSUE THREAD

**Issue by mpenet** [helidon-io/helidon#7782]
## Problem Description

This is from a "simple" hello world example using https://github.com/mpenet/mina (that depends on RC1), built as a uberjar, AOT'ed.

That build of mina has the following dependencies

(lots of clj/EDN coming, sorry)

```edn
 :deps {org.clojure/clojure {:mvn/version "1.12.0-alpha1"}
        com.github.strojure/zmap {:mvn/version "1.3.26"}
        io.helidon.http/helidon-http {:mvn/version "4.0.0-RC1"}
        io.helidon.webserver/helidon-webserver {:mvn/version "4.0.0-RC1"}
        io.helidon.webserver/helidon-webserver-websocket {:mvn/version "4.0.0-RC1"}
        io.helidon.webserver/helidon-webserver-http2 {:mvn/version "4.0.0-RC1"}}
```

We see the following npe in the logs on startup. 

```
Oct 12, 2023 7:37:07 AM io.helidon.common.features.HelidonFeatures features
INFO: Helidon SE 4.0.0-RC1 has no registered features
Oct 12, 2023 7:37:07 AM io.helidon.webserver.ServerListener start
INFO: [0x4bf77642] http://0.0.0.0:8080/ bound for socket '@default'
Exception in thread "features-thread" java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "java.util.Map.get(Object)" is null
	at io.helidon.common.features.HelidonFeatures.features(HelidonFeatures.java:217)
	at io.helidon.common.features.HelidonFeatures.lambda$print$0(HelidonFeatures.java:92)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Oct 12, 2023 7:37:07 AM io.helidon.webserver.LoomServer startIt
INFO: Started all channels in 82 milliseconds. 1245 milliseconds since JVM startup. Java 21+35-2513
```

Looking at the stacktrace it seems there's a nil guard missing here (well, likely before, but it pops there) https://github.com/helidon-io/helidon/blob/release-4.0.0-RC1/common/features/features/src/main/java/io/helidon/common/features/HelidonFeatures.java#L217

Steps to repro (copied from https://github.com/mpenet/mina/issues/11) :

- deps.edn:
  ```edn
  {:paths ["src"]
   :deps {com.s-exp/mina {:mvn/version "0.1.23"}}
   :aliases {:build {:deps {io.github.clojure/tools.build {:git/tag "v0.9.6" :git/sha "8e78bcc"}}
                     :ns-default build}}}

  ```
- build.clj:
  ```clojure
  (ns build
    (:require [clojure.tools.build.api :as b]))
  
  (def uber-file "foo.jar")
  
  (defn clean
    [_]
    (b/delete {:path "target"})
    (b/delete {:path uber-file}))
  
  (defn uber
    [_]
    (let [basis (b/create-basis {:project "deps.edn"})
          class-dir "target/classes"
          src-dirs ["src"]]
      (clean nil)
      (b/write-pom {:class-dir class-dir
                    :lib 'bar/foo
                    :version "0.1.0"
                    :basis basis
                    :src-dirs src-dirs})
      (b/copy-dir {:src-dirs (conj src-dirs "resources")
                   :target-dir class-dir})
      (b/compile-clj {:basis basis
                      :src-dirs src-dirs
                      :class-dir class-dir
                      :ns-compile '[foo.main]
                      :java-cmd (or (System/getenv "JAVA_CMD") "java")
                      :compile-opts {:direct-linking true}})
      (b/uber {:class-dir class-dir
               :uber-file uber-file
               :basis basis
               :main 'foo.main})))

  ```
- src/foo/main.clj:
  ```clojure
  (ns foo.main
    (:require
     [s-exp.mina :as mina])
    (:gen-class))
  
  (defn -main
    [& _args]
    (mina/start! (fn [_req]
                   {:status 200
                    :body "Hello"})
                 {:port 8080
                  :host "0.0.0.0"}))

  ```
- build the uberjar: `clojure -T:build uber`
- Run the jar: `java -jar foo.jar` to see the NPE occur but things work as expected. Running without AOT with `clojure -M -m foo.main` doesn't seem to have this issue.

## Environment Details
* Helidon Version: 4.0.0-RC1
* JDK version: openjdk 21 2023-09-19
* OS: Darwin wintermute2.lan 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64 

----------

**Comment by barchetta** [comment]
Looks like there are two things to investigate:
1. The NPE. There is a null check earlier in the code (it logs the "no registered features" message), but execution continues.
2. Features are not discovered in the user's scenario (which may or may not be a bug)

**Comment by tomas-langer** [comment]
The problem with NPE is fixed.
Features "feature" in Helidon is not designed to work in uberjar, so it will never report correct list of features
