### ISSUE TITLE
[3.x] Helidon app fails to start with Java 21 after compiling to native with GraalVM

### ISSUE THREAD

**Issue by mraible** [helidon-io/helidon#7784]
## Environment Details
* Helidon Version: 3.2.2
* Helidon MP
* JDK version: 21
* OS: macOS
----------

## Problem Description

I upgraded my [auth0-java-rest-api-examples](https://github.com/oktadev/auth0-java-rest-api-examples/pull/32) to use Java 21 and the latest versions of Micronaut, Quarkus, and Spring Boot. I did not upgrade Helidon because the last time I updated (in mid-August), it was using the same version. 

After upgrading to Java 21 and compiling with GraalVM, I get the following error when running `./target/helidon`:

```
2023.10.12 15:23:02 INFO io.helidon.common.LogConfig Thread[#1,main,5,main]: Logging at runtime configured using classpath: /logging.properties
Exception in thread "main" org.jboss.weld.exceptions.DeploymentException
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:38)
        at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:510)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:298)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:250)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
        at java.base@21/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: jakarta.enterprise.event.ObserverException
        at java.base@21/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base@21/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base@21/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304)
        at java.base@21/java.lang.Class.newInstance(DynamicHub.java:725)
        at org.jboss.weld.security.NewInstanceAction.run(NewInstanceAction.java:33)
        at java.base@21/java.security.AccessController.executePrivileged(AccessController.java:114)
        at java.base@21/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:40)
        at org.jboss.weld.injection.Exceptions.rethrowException(Exceptions.java:86)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:105)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
        ... 8 more
Caused by: java.lang.NoSuchMethodException: class io.helidon.microprofile.health.HealthCdiExtension, method: clearAnnotationInfo, paramTypes: [interface jakarta.enterprise.inject.spi.AfterDeploymentValidation]
        at org.jboss.weld.security.MethodLookupAction.lookupMethod(MethodLookupAction.java:55)
        at org.jboss.weld.injection.SecurityActions.lookupMethod(SecurityActions.java:77)
        at org.jboss.weld.injection.VirtualMethodInjectionPoint.getMethod(VirtualMethodInjectionPoint.java:69)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        ... 22 more
```

## Steps to reproduce

```
git clone -b october-2023 https://github.com/oktadev/auth0-java-rest-api-examples.git
cd auth0-java-rest-api-examples/helidon
mvn package -Pnative-image
./target/helidon
```

I did have to make changes to [`native-image.properties`](https://github.com/oktadev/auth0-java-rest-api-examples/blob/main/helidon/src/main/resources/META-INF/native-image/com.okta.rest/helidon/native-image.properties) in order for it to work with Java 20. Maybe similar changes need to be made for Java 21?

**Comment by mraible** [comment]
FWIW, everything works just fine with Java 20:

```
sdk use java 20.0.2-graalce
```

When using `sdk use java 21-graalce`, this error happens.

**Comment by tomas-langer** [comment]
GraalVM is introducing quite a lot of backward incompatible changes, esp. in the regions of reflection and reachability at build time.
We support specific versions of GraalVM with each Helidon version, as it is not simple to support newer ones.
Helidon 4 will run on the latest GraalVM and Java 21.

**Comment by fniephaus** [comment]
> GraalVM is introducing quite a lot of backward incompatible changes, esp. in the regions of reflection and reachability at build time.

I'm not sure I agree with that statement. Yes, we don't have the best track record regarding backward compatibility, but we are working on that and I think we already have improved the situation quite a bit (e.g., introduction of `--strict-image-heap`). In this particular case, I'm not sure GraalVM is to blame.

I don't know how Helidon generates metadata for GraalVM Native Image, but I found this comment, which does not make any sense to me:

https://github.com/helidon-io/helidon/blob/18d39d4c05ccfdd3fca089262956dc25a1dc68e7/service-common/rest-cdi/src/main/java/io/helidon/servicecommon/restcdi/HelidonRestCdiExtension.java#L119

The visibility of a method should not influence whether it is registered for reflection or not. My feeling is that this method was previously registered for reflection accidentally, maybe due to an imprecision in the static analysis of Native Image. We usually fix imprecisions to further reduce overall file size, but then of course, we also break code that accidentally worked before.

With a `reflect-config.json` containing the content below, I was able to get past the error. Unfortunately, I immediately hit a different error (see below as well), so maybe you indeed need to wait for Helidon 4.

**reflect-config.json**
```json
[
    {
        "name": "io.helidon.servicecommon.restcdi.HelidonRestCdiExtension",
        "methods": [
            {
              "name": "clearAnnotationInfo",
              "parameterTypes": ["jakarta.enterprise.inject.spi.AfterDeploymentValidation"]
            },
            {
              "name": "observeManagedBeans",
              "parameterTypes": ["jakarta.enterprise.inject.spi.ProcessManagedBean"]
            },
            {
              "name": "registerService",
              "parameterTypes": [
                "java.lang.Object",
                "jakarta.enterprise.inject.spi.BeanManager",
                "io.helidon.microprofile.server.ServerCdiExtension"
              ]
            }
        ]
      }
]
```

**New error**
```
$ ./target/helidon 
2023.10.16 11:25:31 INFO io.helidon.common.LogConfig Thread[#1,main,5,main]: Logging at runtime configured using classpath: /logging.properties
2023.10.16 11:25:31 INFO io.helidon.microprofile.security.SecurityCdiExtension Thread[#1,main,5,main]: Authorization provider is missing from security configuration, but security extension for microprofile is enabled (requires providers configuration at key security.providers). ABAC provider is configured for authorization.
2023.10.16 11:25:31 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: Registering JAX-RS Application: HelloApplication
Exception in thread "main" MultiException stack 1 of 1
java.lang.NoSuchMethodException: Could not find a suitable constructor in org.glassfish.jersey.jsonb.JsonBindingFeature class.
	at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:168)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:157)
	at org.jvnet.hk2.internal.Utilities.justCreate(Utilities.java:1043)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.create(ServiceLocatorImpl.java:984)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1088)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1080)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createAndInitialize(AbstractHk2InjectionManager.java:199)
...
```

**Comment by tomas-langer** [comment]
Closing this issue, as we will not change our support model for older versions of Helidon. Only a single major release of GraalVM was supported for a specific major version of Helidon.
