### ISSUE TITLE
Unable to enable Access logging

### ISSUE THREAD

**Issue by plouj** [helidon-io/helidon#8040]
## Environment Details
* Helidon Version: 4.0.0
* Helidon SE
* JDK version: 21.0.1
* OS: Linux
* Podman version: 3.4.4

----------

## Problem Description
After following the instructions under the "Access Log" section (which doesn't have an anchor in the table of contents btw) on https://helidon.io/docs/v4/#/se/webserver, I'm unable to get access logging to work.

## Steps to reproduce
I start with a sample project:
```
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=4.0.0 \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
```
As instructed in https://helidon.io/docs/v4/#/se/webserver I add:
```
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-access-log</artifactId>
</dependency>
```
to my `pom.xml`

Finally I add:
```
  features:
    access-log:
      format: "%h %l %u %t %r %s %b %{Referer}i"
```
to `src/main/resources/application.yaml`.
After `mvn package -DskipTests` I run `java -Xdiag -jar helidon-quickstart-se.jar` and it aborts with:
```
Exception in thread "main" io.helidon.common.config.ConfigException: Unknown provider configured. Expected providers with types: [access-log], but only the following providers are supported: [cors, context, observe], provider interface: io.helidon.webserver.spi.ServerFeatureProvider, configured service: io.helidon.webserver.spi.ServerFeature
	at io.helidon.builder.api.ProvidedUtil.servicesFromObject(ProvidedUtil.java:231)
	at io.helidon.builder.api.ProvidedUtil.discoverServices(ProvidedUtil.java:168)
	at io.helidon.builder.api.Prototype$ConfiguredBuilder.discoverServices(Prototype.java:122)
	at io.helidon.webserver.WebServerConfig$BuilderBase.preBuildPrototype(WebServerConfig.java:427)
	at io.helidon.webserver.WebServerConfig$Builder.buildPrototype(WebServerConfig.java:639)
	at io.helidon.webserver.WebServerConfig$Builder.build(WebServerConfig.java:646)
	at io.helidon.examples.quickstart.se.Main.main(Main.java:43)
```

**Comment by tomas-langer** [comment]
we are missing a provides in our module-info.java.
Workaround:
create a META-INF/services/io.helidon.webserver.spi.ServerFeatureProvider with content:
```
io.helidon.webserver.accesslog.AccessLogFeatureProvider
```
