### ISSUE TITLE
[4.x] Strict heap size parameter doesn't work (native image)

### ISSUE THREAD

**Issue by lprimak** [helidon-io/helidon#8095]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.1
* Helidon SE or Helidon MP - MP
* JDK version: 21.0.1-graalce
* OS: Mac

----------

## Problem Description
When compiling native image with the latest GraalVM, it prints out the following:
 Recommendations:
[INFO] [stdout]  INIT: Adopt '--strict-image-heap' to prepare for the next GraalVM release.
[INFO] [stdout]  HEAP: Set max heap for improved and more predictable memory usage.

However, when I run with `--strict-image-heap` parameter, native compilation fails:

```
[WARNING] [stderr] Fatal error: org.graalvm.compiler.debug.GraalError: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[WARNING] [stderr] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[WARNING] [stderr] 
[WARNING] [stderr] You now have two options to resolve this:
[WARNING] [stderr] 
[WARNING] [stderr] 1) If it is intended that objects of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' are persisted in the image heap, add 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[WARNING] [stderr] 
[WARNING] [stderr] 2) If these objects should not be stored in the image heap, you can use 
[WARNING] [stderr] 
[WARNING] [stderr]     '--trace-object-instantiation=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-run-time=<culprit>'
[WARNING] [stderr] 
[WARNING] [stderr] to prevent the instantiation of the object.
[WARNING] [stderr] 
[WARNING] [stderr] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[WARNING] [stderr] To fix this, include '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[WARNING] [stderr] Please address this problem to be prepared for future releases of GraalVM.
[WARNING] [stderr] 
[WARNING] [stderr] The following detailed trace displays from which field in the code the object was reached.
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
[WARNING] [stderr] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapInstance.readFieldValue(ImageHeapInstance.java:110)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.onObjectReachable(ImageHeapScanner.java:472)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.onObjectReachable(SVMImageHeapScanner.java:156)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$markReachable$5(ImageHeapScanner.java:452)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$14(ImageHeapScanner.java:695)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:187)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:171)
[WARNING] [stderr] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[WARNING] [stderr] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[WARNING] [stderr] 	at java.base/java.util.concurrent.ForkJoinPool.externalHelpQuiesce(ForkJoinPool.java:2260)
[WARNING] [stderr] 	at java.base/java.util.concurrent.ForkJoinPool.helpQuiescePool(ForkJoinPool.java:2297)
[WARNING] [stderr] 	at java.base/java.util.concurrent.ForkJoinPool.awaitQuiescence(ForkJoinPool.java:3565)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.complete(CompletionExecutor.java:237)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.doTypeflow(PointsToAnalysis.java:529)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.finish(PointsToAnalysis.java:517)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:783)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:592)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:538)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
[INFO] [stdout] ------------------------------------------------------------------------------------------------------------------------
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
[WARNING] [stderr] Caused by: org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[WARNING] [stderr] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[WARNING] [stderr] 
[WARNING] [stderr] You now have two options to resolve this:
[WARNING] [stderr] 
[WARNING] [stderr] 1) If it is intended that objects of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' are persisted in the image heap, add 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[WARNING] [stderr] 
[WARNING] [stderr] 2) If these objects should not be stored in the image heap, you can use 
[WARNING] [stderr] 
[WARNING] [stderr]     '--trace-object-instantiation=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-run-time=<culprit>'
[WARNING] [stderr] 
[WARNING] [stderr] to prevent the instantiation of the object.
[WARNING] [stderr] 
[WARNING] [stderr] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[WARNING] [stderr] To fix this, include '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[WARNING] [stderr] Please address this problem to be prepared for future releases of GraalVM.
[WARNING] [stderr] 
[WARNING] [stderr] The following detailed trace displays from which field in the code the object was reached.
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.setException(AnalysisFuture.java:49)
[WARNING] [stderr] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:322)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.getOrCreateImageHeapConstant(ImageHeapScanner.java:212)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.heap.SVMImageHeapScanner.getOrCreateImageHeapConstant(SVMImageHeapScanner.java:109)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapConstant(ImageHeapScanner.java:186)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createFieldValue(ImageHeapScanner.java:364)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$createImageHeapInstance$4(ImageHeapScanner.java:294)
[WARNING] [stderr] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[WARNING] [stderr] 	... 24 more
[WARNING] [stderr] Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: An object of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
[WARNING] [stderr] This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
[WARNING] [stderr] 
[WARNING] [stderr] You now have two options to resolve this:
[WARNING] [stderr] 
[WARNING] [stderr] 1) If it is intended that objects of type 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' are persisted in the image heap, add 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
[WARNING] [stderr] 
[WARNING] [stderr] 2) If these objects should not be stored in the image heap, you can use 
[WARNING] [stderr] 
[WARNING] [stderr]     '--trace-object-instantiation=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate'
[WARNING] [stderr] 
[WARNING] [stderr] to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with 
[WARNING] [stderr] 
[WARNING] [stderr]     '--initialize-at-run-time=<culprit>'
[WARNING] [stderr] 
[WARNING] [stderr] to prevent the instantiation of the object.
[WARNING] [stderr] 
[WARNING] [stderr] If you are seeing this message after enabling '--strict-image-heap', this means that some objects ended up in the image heap without their type being marked with --initialize-at-build-time.
[WARNING] [stderr] To fix this, include '--initialize-at-build-time=io.helidon.config.mp.MpConfigProviderResolver$ConfigDelegate' in your configuration. If the classes do not originate from your code, it is advised to update all library or framework dependencies to the latest version before addressing this error.
[WARNING] [stderr] Please address this problem to be prepared for future releases of GraalVM.
[WARNING] [stderr] 
[WARNING] [stderr] The following detailed trace displays from which field in the code the object was reached.
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:186)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:616)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:296)
[WARNING] [stderr] 	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readArrayElement(AnalysisConstantReflectionProvider.java:158)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObjectArray(ImageHeapScanner.java:267)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.createImageHeapObject(ImageHeapScanner.java:251)
[WARNING] [stderr] 	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$getOrCreateImageHeapConstant$2(ImageHeapScanner.java:205)
[WARNING] [stderr] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[WARNING] [stderr] 	... 31 more
[INFO] [stdout]                         3.3s (7.0% of total time) in 75 GCs | Peak RSS: 0.75GB | CPU load: 2.67
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
Add `<arg>--strict-image-heap</arg>` to native image build section in pom.xml

**Comment by lprimak** [comment]
I believe this is due to Hibernate Validator or it's dependencies not being compatible

**Comment by lprimak** [comment]
Strict image parameter is no longer supported and is the default in the latest GraalVM release
