### ISSUE TITLE
4.x Database example - application does not start with Oracle DB

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#8156]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version: 21
* OS: MacOS
* Docker version (if applicable):

----------

## Problem Description

Application does not start.

## Steps to reproduce

```bash
cd examples/dbclient/jdbc
docker run --rm --name xe -p 1521:1521 -p 8888:8080 -e ORACLE_PWD=oracle wnameless/oracle-xe-11g-r2
java -jar target/helidon-examples-dbclient-jdbc.jar
```

Exception:

```bash
Exception in thread "main" io.helidon.dbclient.DbClientException: Failed to create a connection to jdbc:oracle:thin:@localhost:1521/XE
        at io.helidon.dbclient.hikari.HikariConnectionPool.connection(HikariConnectionPool.java:70)
        at io.helidon.dbclient.jdbc.JdbcStatement.prepareStatement(JdbcStatement.java:111)
        at io.helidon.dbclient.jdbc.JdbcStatement.prepareStatement(JdbcStatement.java:100)
        at io.helidon.dbclient.jdbc.JdbcStatementDml.doExecute(JdbcStatementDml.java:73)
        at io.helidon.dbclient.jdbc.JdbcStatementDml.lambda$execute$0(JdbcStatementDml.java:54)
        at io.helidon.dbclient.DbStatementBase.doExecute(DbStatementBase.java:97)
        at io.helidon.dbclient.jdbc.JdbcStatementDml.execute(JdbcStatementDml.java:52)
        at io.helidon.dbclient.DbExecute.namedDml(DbExecute.java:341)
        at io.helidon.examples.dbclient.jdbc.PokemonService.<init>(PokemonService.java:34)
        at io.helidon.examples.dbclient.jdbc.JdbcExampleMain.lambda$setupServer$0(JdbcExampleMain.java:72)
        at io.helidon.webserver.WebServerConfigSupport$ListenerCustomMethods.routing(WebServerConfigSupport.java:158)
        at io.helidon.webserver.ListenerConfig$BuilderBase.routing(ListenerConfig.java:231)
        at io.helidon.examples.dbclient.jdbc.JdbcExampleMain.setupServer(JdbcExampleMain.java:72)
        at io.helidon.examples.dbclient.jdbc.JdbcExampleMain.main(JdbcExampleMain.java:50)
Caused by: java.sql.SQLTransientConnectionException: oracle - Connection is not available, request timed out after 2005ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at io.helidon.dbclient.hikari.HikariConnectionPool.connection(HikariConnectionPool.java:67)
        ... 13 more
Caused by: java.sql.SQLRecoverableException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
  (CONNECTION_ID=DwqnoEH6QAyt4j7c8gw1Sg==)
        at oracle.jdbc.driver.T4CConnection.handleLogonNetException(T4CConnection.java:872)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:677)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:1039)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:90)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:728)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:649)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733)
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: oracle.net.ns.NetException: Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor
  (CONNECTION_ID=DwqnoEH6QAyt4j7c8gw1Sg==)
        at oracle.net.ns.NSProtocolNIO.createRefusePacketException(NSProtocolNIO.java:816)
        at oracle.net.ns.NSProtocolNIO.handleConnectPacketResponse(NSProtocolNIO.java:396)
        at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:207)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:350)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1969)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:642)
        ... 14 more
```

**Comment by tvallin** [comment]
This issue happened with MacOS arch64 and rancher desktop. A workaround for me was to use `Colima` and it works as expected. So this is not a Helidon issue and closing this issue
