### ISSUE TITLE
OCI integration using Instance Principal fails

### ISSUE THREAD

**Issue by klustria** [helidon-io/helidon#8191]
## Environment Details
* Helidon Version: 4x
* Helidon MP

----------

## Problem Description
OCI Instance Principal Authentication fails with this error:

```
023.12.19 04:29:17 SEVERE io.helidon.inject.runtime.AbstractServiceProvider Thread[#1,main,5,main]: unable to activate: io.helidon.integrations.oci.sdk.runtime.OciAuthenticationDetailsProvider$$Injection$$Activator
java.util.NoSuchElementException: No instances of com.oracle.bmc.auth.AbstractAuthenticationDetailsProvider available for use. Verify your configuration named: oci
        at io.helidon.integrations.oci.sdk.runtime.OciAuthenticationDetailsProvider.select(OciAuthenticationDetailsProvider.java:123)
        at io.helidon.integrations.oci.sdk.runtime.OciAuthenticationDetailsProvider.first(OciAuthenticationDetailsProvider.java:94)
        at io.helidon.inject.runtime.AbstractServiceProvider.first(AbstractServiceProvider.java:338)
        at io.helidon.inject.runtime.AbstractServiceProvider.get(AbstractServiceProvider.java:324)
        at io.helidon.integrations.oci.sdk.runtime.OciExtension.lambda$ociAuthenticationProvider$4(OciExtension.java:203)
        at io.helidon.integrations.oci.sdk.cdi.OciExtension.lambda$installAdps$2(OciExtension.java:861)
        at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$CreateCallback.create(BeanConfiguratorImpl.java:372)
        at org.jboss.weld.bootstrap.events.configurator.BeanConfiguratorImpl$ImmutableBean.create(BeanConfiguratorImpl.java:511)
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        ...
        ...
        ...
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:256)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

## Steps to reproduce
1.  Generate the latest Helidon MP 4 Quickstart with OCI using `helidon` tool.
2.  Build and deploy the app to an OCI instance. 
3.  Make sure that the home directory where the app is deployed does not have an oci config, i.e. no `~/.oci` directory.
4.  Run the application and the error will be reproduced

**Comment by klustria** [comment]
Will fixed via https://github.com/helidon-io/helidon/pull/8197

**Comment by klustria** [comment]
Closed as PR https://github.com/helidon-io/helidon/pull/8197 is merged
