### ISSUE TITLE
4.x `WebClientSecurity` throws NPE trying to use current span in security context as parent for new span

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8192]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
(derived from an internal user Slack message)

In at least some circumstances, the `WebClientSecurity#handle` method throws an NPE as it sets up a new tracing span. It tries to use the span in the current security context as the parent for the new span but does not check to see if the context actually contains a span first.

```
java.lang.NullPointerException: Cannot invoke "io.helidon.tracing.SpanContext.asParent(io.helidon.tracing.Span$Builder)" because "spanContext" is null
        at io.helidon.tracing.providers.opentelemetry.OpenTelemetrySpanBuilder.parent(OpenTelemetrySpanBuilder.java:43)
        at io.helidon.tracing.providers.opentelemetry.OpenTelemetrySpanBuilder.parent(OpenTelemetrySpanBuilder.java:27)
        at io.helidon.webclient.security.WebClientSecurity.handle(WebClientSecurity.java:111)
        at io.helidon.webclient.api.ServiceChainImpl.proceed(ServiceChainImpl.java:32)
        at io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:395)
        at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeWithServices(Http1ClientRequestImpl.java:205)
        at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeRequestWithEntity(Http1ClientRequestImpl.java:195)
        at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:46)
        at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:37)
        at io.helidon.webclient.http1.Http1ClientRequestImpl.doSubmit(Http1ClientRequestImpl.java:111)
        at io.helidon.webclient.http1.Http1ClientRequestImpl.doSubmit(Http1ClientRequestImpl.java:37)
        at io.helidon.webclient.api.ClientRequestBase.validateAndSubmit(ClientRequestBase.java:452)
        at io.helidon.webclient.api.ClientRequestBase.submit(ClientRequestBase.java:266)
        at io.helidon.webclient.api.HttpClientRequest.doSubmit(HttpClientRequest.java:79)
        at io.helidon.webclient.api.ClientRequestBase.validateAndSubmit(ClientRequestBase.java:452)
        at io.helidon.webclient.api.ClientRequestBase.request(ClientRequestBase.java:257)
        at io.helidon.lra.coordinator.client.narayana.NarayanaClient.lambda$startInternal$3(NarayanaClient.java:115)
        at io.helidon.faulttolerance.RetryImpl.invoke(RetryImpl.java:62)
        at io.helidon.lra.coordinator.client.narayana.NarayanaClient.startInternal(NarayanaClient.java:106)
        at io.helidon.lra.coordinator.client.narayana.NarayanaClient.start(NarayanaClient.java:92)
```

**Comment by jvissers** [comment]
There also seems to be a relation of this issue and `helidon-connector`. If you don't have this dependency on the path, the above issue does not occur. I initially tried this in our migration from H3 to H4, but it turned out that I actually need `helidon-connector` for HTTP PATCH operation support. Without `helidon-connector` I would have to start using ugly workaround, requiring me to fiddle with `add-opens` (that workaround is talked about here: https://stackoverflow.com/questions/22355235/patch-request-using-jersey-client)

**Comment by spericas** [comment]
@jvissers In the stack trace above, I just see Narayana and WebClient calls, which eventually result in the NPE. There's no Helidon connector code or Jakarta REST Client code at all. So are you saying that just having the connector in the classpath results in the NPE even though the connector code is not even on the stack trace? Or is there some other stack trace that we haven't seen yet?

**Comment by jvissers** [comment]
@spericas you are correct there is no Helidon connector in this stack. The only thing that I have noticed was that this problem goes away when you don't include the helidon-connector on the path. Sorry, if this make no sense. When I have time available, I'll try to get more information for you.

**Comment by spericas** [comment]
@jvissers Thanks, yes, some more information on how to reproduce the problem would be useful.

**Comment by spericas** [comment]
I've tried adding tracing dependencies to some existing connector tests and I haven't seen any issues so far. We definitely need to spend time on a reproducible first.

**Comment by tjquinno** [comment]
@jvissers Jan, a bit of background, a request for you, and a conjecture as to the root cause of this.

## Background
The `helidon-webclient-tracing` component is what makes tracing and span information available to web clients automatically via the `WebClientTracing` web client service.

`WebClientSecurity` is also a web client service. 

The `HelidonConnector` class in `helidon-connector` code builds a `WebClient` instance. Although that code does not explicitly add `WebClientTracing` it does leave auto-discovery of web client services _on_. This means that, if the `WebClientTracing` service is on the class path, it should be auto-discovered and incorporated into the `WebClient` which `HelidonConnector` is creating.

## Request
Now, the request for you: Can you please double-check these:
1. Make sure the `helidon-webclient-tracing` component is on the class path.
2. Make sure the configuration does not disable web client.

TBH, I am almost positive that both of those will turn out to be OK because you did tell us that things work if `helidon-connector` is not present (assuming that when you add `helidon-connector` you do not also _remove_ `helidon-webclient-tracing`).

## Conjecture as to the root cause

1. `HelidonConnector` is correctly using auto-discovery to add both `WebClientTracing` and `WebClientSecurity` as services to its new `WebClient`.
2. Because neither `WebClientTracing` nor `WebClientSecurity` declares a weight they both have the default weight, meaning that the order in which they are added and therefore the order in which their `handle` methods are invoked is indeterminate and, in the error case, `WebClientSecurity` is being invoked before `WebClientTracing`. The expect span information is missing so we see the NPE.

If my conjecture is correct, then a fix could be for Helidon to declare an explicit weight on `WebClientTracing` weight that is higher than the default (in particular, higher than `WebClientSecurity`'s weight).

**Comment by jvissers** [comment]
@tjquinno - thank you for this detailed analysis. I think the hypothesis is valid, and reflects what I did see when I did preparations for H4 migration.
