### ISSUE TITLE
WsClient fails to resolve hostname to IPv6 address

### ISSUE THREAD

**Issue by 4e6** [helidon-io/helidon#8205]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.2
* Helidon SE
* JDK version: openjdk 21.0.1
* OS: Archlinux
* Docker version (if applicable): -

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

`WsClient` fails with `java.net.ConnectException: Connection refused` when trying to connect to WebSocket server on IPv6 interface:

```
Exception in thread "main" java.io.UncheckedIOException: java.net.ConnectException: Connection refused
	at io.helidon.webclient.api@4.0.2/io.helidon.webclient.api.Proxy$ProxyType$2.connect(Proxy.java:546)
	at io.helidon.webclient.api@4.0.2/io.helidon.webclient.api.Proxy.tcpSocket(Proxy.java:283)
	at io.helidon.webclient.api@4.0.2/io.helidon.webclient.api.TcpClientConnection.connect(TcpClientConnection.java:114)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1ConnectionCache.keepAliveConnection(Http1ConnectionCache.java:144)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1ConnectionCache.connection(Http1ConnectionCache.java:77)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1CallChainBase.obtainConnection(Http1CallChainBase.java:292)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1CallChainBase.proceed(Http1CallChainBase.java:133)
	at io.helidon.webclient.api@4.0.2/io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:395)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1ClientRequestImpl.invokeWithServices(Http1ClientRequestImpl.java:205)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1ClientRequestImpl.invokeRequestWithEntity(Http1ClientRequestImpl.java:195)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:46)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:37)
	at io.helidon.webclient.http1@4.0.2/io.helidon.webclient.http1.Http1ClientRequestImpl.upgrade(Http1ClientRequestImpl.java:138)
	at io.helidon.webclient.websocket@4.0.2/io.helidon.webclient.websocket.WsClientImpl.connect(WsClientImpl.java:120)
	at WebSocket@1.0-SNAPSHOT/org.apidesign.WebSocket.main(WebSocket.java:45)
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

For testing I was using [joewalnes/websocketd](https://github.com/joewalnes/websocketd) server listening on `::1` (IPv6 address of localhost).

Create an `echo-program.bash` (needed to start websocketd)
```bash
$ cat /tmp/echo-program.bash
#!/bin/bash

while read line
do
  echo $line
done
```
Make sure it is executable
```bash
$ chmod +x /tmp/echo-program.bash
```
Start `websocketd` server on `::1` address
```bash
$ websocketd --loglevel=trace --address=[::1] --port=1234 /tmp/echo-program.bash
```
Verify that `websocketd` is listening on `::1:1234`
```bash
$ sudo netstat -tlpn
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 ::1:1234                :::*                    LISTEN      6412/websocketd
```

Connection to `ws://localhost:1234` results in `java.net.ConnectException: Connection refused`.
```java
var client = io.helidon.webclient.websocket.WsClient.builder()
            .addHeader("Connection", "Upgrade")
            .build();
var uri = new java.net.URI("ws://localhost:1234");
var listener = new io.helidon.websocket.WsListener() {};

client.connect(uri, listener);
```

Connection to IPv6 address directly `ws://[::1]:1234` is successful.

**Comment by spericas** [comment]
@4e6 Is your environment resolving "localhost" to ipv4 127.0.0.1?

**Comment by spericas** [comment]
Had a closer look at how this is resolved now ... we currently rely on the order of addresses returned by Java (by default) and  will only try the first one, which for `localhost` would be 127.0.0.1 (ipv4) even if ::1 (ipv6) is also there. This is done by the underlying `WebClient` used by `WsClient`. 

Perhaps some other clients try all addresses until they succeed, but the our current implementation does not (was that your expectation?). 

It is possible to override this behavior and introduce a custom `io.helidon.webclient.spi.DnsResolver` that would return ipv6 addresses and ignore ipv4 ones.

**Comment by spericas** [comment]
Here is an example of how to use your own `DnsResolver`:

```
public class Ipv6DnsResolver implements DnsResolver {
    @Override
    public InetAddress resolveAddress(String hostname, DnsAddressLookup dnsAddressLookup) {
        try {
            InetAddress[] addresses = InetAddress.getAllByName(hostname);
            addresses = Arrays.stream(addresses)
                    .filter(a -> a.getAddress().length == 16)
                    .toArray(InetAddress[]::new);
            if (addresses.length > 0) {
                return addresses[0];
            }
        } catch (Exception e) {
            // falls through
        }
        throw new IllegalArgumentException("Cannot resolve host " + hostname);
    }
}

public class Ipv6DnsResolverProvider implements DnsResolverProvider {
    @Override
    public String resolverName() {
        return "ipv6 only";
    }

    @Override
    public DnsResolver createDnsResolver() {
        return new Ipv6DnsResolver();
    }
}
```

Finally, the provider needs to be registered with Java services mechanism.
