### ISSUE TITLE
4.x: outputStreamAndContentLengthTest.testOutputStreamChunked failing in validation builds

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8246]
I've started seening this test failing during PR validation. It passes locally:

```
22:26:11,233 [INFO] Running io.helidon.webserver.tests.OutputStreamAndContentLengthTest
Error: 2,053 [ERROR] Tests run: 4, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.818 s <<< FAILURE! - in io.helidon.webserver.tests.OutputStreamAndContentLengthTest
Error: 2,053 [ERROR] io.helidon.webserver.tests.OutputStreamAndContentLengthTest.testOutputStreamChunked  Time elapsed: 0.094 s  <<< ERROR!
java.lang.NegativeArraySizeException: -131060
	at io.helidon.common.buffers.FixedBufferData.<init>(FixedBufferData.java:33)
	at io.helidon.common.buffers.BufferData.create(BufferData.java:44)
	at io.helidon.webclient.http1.Http1CallOutputStreamChain$ClientConnectionOutputStream.writeChunked(Http1CallOutputStreamChain.java:329)
	at io.helidon.webclient.http1.Http1CallOutputStreamChain$ClientConnectionOutputStream.write(Http1CallOutputStreamChain.java:262)
	at java.base/java.io.ByteArrayInputStream.transferTo(ByteArrayInputStream.java:213)
	at io.helidon.webserver.tests.OutputStreamAndContentLengthTest.lambda$testOutputStreamChunked$0(OutputStreamAndContentLengthTest.java:83)
	at io.helidon.webclient.http1.Http1CallOutputStreamChain.doProceed(Http1CallOutputStreamChain.java:89)
	at io.helidon.webclient.http1.Http1CallChainBase.proceed(Http1CallChainBase.java:149)
	at io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:395)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeWithServices(Http1ClientRequestImpl.java:205)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.doOutputStream(Http1ClientRequestImpl.java:126)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.doOutputStream(Http1ClientRequestImpl.java:37)
	at io.helidon.webclient.api.ClientRequestBase.outputStream(ClientRequestBase.java:273)
	at io.helidon.webclient.api.HttpClientRequest.doOutputStream(HttpClientRequest.java:84)
	at io.helidon.webclient.api.ClientRequestBase.outputStream(ClientRequestBase.java:273)
	at io.helidon.webclient.api.ClientRequest.outputStream(ClientRequest.java:329)
	at io.helidon.webserver.tests.OutputStreamAndContentLengthTest.testOutputStreamChunked(OutputStreamAndContentLengthTest.java:81)
```

```
Error: 0,338 [ERROR] Errors: 
Error: 0,338 [ERROR]   OutputStreamAndContentLengthTest.testOutputStreamChunked:81->lambda$testOutputStreamChunked$0:83 » NegativeArraySize -131060
Error: 0,338 [ERROR]   OutputStreamAndContentLengthTest.testOutputStreamOutOfOrder:111->lambda$testOutputStreamOutOfOrder$2:113 » NegativeArraySize -131060
Error: 0,338 [ERROR]   OutputStreamAndContentLengthTest.testOutputStreamWithContentLength:96->lambda$testOutputStreamWithContentLength$1:98 » NegativeArraySize -131060
22:26:30,338 [INFO] 
```

**Comment by barchetta** [comment]
Duplicate of #8250
