### ISSUE TITLE
"io.helidon.http.RequestException: Failed to wait for pipeline"

### ISSUE THREAD

**Issue by imrafaelmerino** [helidon-io/helidon#8317]
## Environment Details
* Helidon Version:  4.0.1 
* Helidon SE or Helidon MP: Helidon SE 4.0.1 features: [Config, Encoding, Health, Media, Observe, WebServer]
* JDK version: 21-oracle
* OS: MAC
* Docker version: 

----------

## Problem Description
I'm facing this exception while doing some testing with Helidon

```text
12:54:08.857 DEBUG io.helidon.webserver.http1.Http1LoggingConnectionListener.send [0x502383db 0x127f2e3b] send status: 500 Internal Server Error
12:54:08.857 DEBUG io.helidon.webserver.http1.Http1LoggingConnectionListener.send [0x502383db 0x127f2e3b] send headers: 
Connection: keep-alive
Content-Length: 27
Content-Type: text/plain

12:54:08.857 DEBUG io.helidon.webserver.ConnectionHandler [0x502383db 0x7d4d310d] socket closed
12:54:08.857 WARN  io.helidon.webserver.http1.Http1Connection Internal server error
io.helidon.http.RequestException: Failed to wait for pipeline
	at io.helidon.http.RequestException$Builder.build(RequestException.java:139) ~[helidon-http-4.0.1.jar:4.0.1]
	at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:425) ~[helidon-webserver-4.0.1.jar:4.0.1]
	at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:187) ~[helidon-webserver-4.0.1.jar:4.0.1]
	at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165) ~[helidon-webserver-4.0.1.jar:4.0.1]
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47) ~[helidon-common-task-4.0.1.jar:4.0.1]
	at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239) ~[helidon-webserver-4.0.1.jar:4.0.1]
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1100) ~[?:?]
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230) ~[?:?]
	at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:418) ~[helidon-webserver-4.0.1.jar:4.0.1]
	... 5 more
```

What does that exception and message mean?

Thanks in advance!

**Comment by tomas-langer** [comment]
This means that the entity was not consumed, and the thread was interrupted. I have discovered an issue here, where if the header `Connection: close` is set, this may happen even if nothing went wrong. 
Do you have a way to reproduce this problem?

**Comment by tomas-langer** [comment]
I have added a PR with a fix for the problem I discovered.

**Comment by tomas-langer** [comment]
Hello @imrafaelmerino - I will close this issue, as I have fixed the bug I could find without a reproducer. If you see this again after we release 4.0.6 (that should be the version this fix will be inclulded in), kindly re-open this issue, ideally with steps to reproduce, so I can get to the root of the problem.
Thanks
