### ISSUE TITLE
4.x: DNS resolver test with IPv6 fails on local computer

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#8330]
Test fails on local machine:

```
[INFO] Running io.helidon.webclient.api.DefaultDnsResolverTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.042 s <<< FAILURE! - in io.helidon.webclient.api.DefaultDnsResolverTest
[ERROR] io.helidon.webclient.api.DefaultDnsResolverTest.testIpv6Resolution  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is "0:0:0:0:0:0:0:1"
     but: was "127.0.0.1"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at io.helidon.webclient.api.DefaultDnsResolverTest.testIpv6Resolution(DefaultDnsResolverTest.java:38)
```

Output of `ifconfig` for loopback interface:

```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 10692858  bytes 2787182180 (2.7 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10692858  bytes 2787182180 (2.7 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Ouput of `ip a`:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
```

**Comment by tomas-langer** [comment]
On pipeline:
```
nslookup localhost
  
Server:		127.0.0.53
Address:	[12](https://github.com/helidon-io/helidon/actions/runs/7787021574/job/21233183205?pr=8331#step:4:13)7.0.0.53#53

Non-authoritative answer:
Name:	localhost
Address: 127.0.0.1
Name:	localhost
Address: ::1
```

On localhost:
```
nslookup localhost
Server:         127.0.0.53
Address:        127.0.0.53#53

Name:   localhost
Address: 127.0.0.1
```

**Comment by tomas-langer** [comment]
Solution:
`/etc/hosts` must be updated to contain the following line (or similar one):
```
::1     ip6-localhost ip6-loopback localhost
```
