### ISSUE TITLE
Secured Async response is missing Helidon context when invoked from unsupported executor

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#8416]
Secured Async response is missing Helidon context. 
`Context must be available in Jersey`

## Environment Details
* Helidon Version: 4.0.5
* Helidon MP
* JDK version: 21.0.1+12-29
* OS: Ubuntu 23.10 6.5.0-17-generic

----------

## Problem Description
```
INFO: Helidon MP 4.0.5 features: [CDI, Config, Fault Tolerance, Health, Metrics, Open API, REST Client, Security, Server]
Feb 23, 2024 12:16:32 PM org.glassfish.jersey.server.ServerRuntime$Responder process
WARNING: An exception mapping did not successfully produce and processed a response. Logging the exception propagated to the default exception mapper.
java.lang.IllegalStateException: Context must be available in Jersey
	at io.helidon.microprofile.security.SecurityFilter.lambda$filter$3(SecurityFilter.java:188)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.microprofile.security.SecurityFilter.filter(SecurityFilter.java:188)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:172)
	at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:139)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:383)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:375)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:905)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:937)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:893)
	at me.daniel.mp.quickstart.TestResource.lambda$defaultProvider$0(TestResource.java:10)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

```

## Steps to reproduce
```bash
helidon init --batch --version 4.0.5 -Dpackage=me.test  -Dflavor=mp -Dapp-type=custom -Dsecurity=yes && \ 
cd ./custom-mp && \
cat <<EOT >> ./src/test/java/me/test/TestResource.java
package me.test;
import java.util.concurrent.CompletableFuture;
import io.helidon.microprofile.testing.junit5.HelidonTest;
import io.helidon.security.annotations.Authenticated;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.container.*;
import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

@HelidonTest
@Path("/tst")
public class TestResource {

    @Inject
    private WebTarget t;


    @GET
    @Authenticated(value = false)
    public void defaultProvider(@Suspended AsyncResponse ar) {
        CompletableFuture.runAsync(() -> ar.resume("test"));
    }

    @Test
    public void test(){
        assertThat(t.path("/tst").request().get().getStatus(), is(200));
    }
}
EOT
```

```bash
mvn test
```

**Comment by danielkec** [comment]
Simple workaround is:
```java
    @GET
    @Authenticated(value = false)
    public void defaultProvider(@Suspended AsyncResponse ar) {
        CompletableFuture.runAsync(() -> ar.resume("test"), ThreadPoolSupplier.builder().build().get());
    }
```

But can't we provide more use friendly approach?

**Comment by rlubke** [comment]
For what it's worth, I've just hit this issue while migrating [the coherence-helidon-sockshop](https://github.com/oracle/coherence-helidon-sockshop-sample).   This error will be raised when testing any of the async resources.
