### ISSUE TITLE
Unable to perform operation: resolve on io.helidon.microprofile.telemetry.HelidonTelemetryClientFilter

### ISSUE THREAD

**Issue by yyyyike** [helidon-io/helidon#8475]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.5
* Helidon SE or Helidon MP: Helidon MP
* JDK version: jdk-21
* OS: macOS Sonoma 14.3
* Docker version (if applicable): 

----------

## Problem Description
Unit test failed due to unable to resolve on io.helidon.microprofile.telemetry.HelidonTelemetryClientFilter

```
MultiException stack 4 of 4
java.lang.IllegalStateException: Unable to perform operation: resolve on io.helidon.microprofile.telemetry.HelidonTelemetryClientFilter
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:422)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:300)
	at org.glassfish.jersey.internal.inject.Providers.getAllRankedProviders(Providers.java:183)
	at org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:267)
	at org.glassfish.jersey.client.ClientFilteringStages.createRequestFilteringStage(ClientFilteringStages.java:57)
	at org.glassfish.jersey.client.ClientRuntime.<init>(ClientRuntime.java:111)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:472)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834)
	at org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181)
	at org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38)
	at oracle.apps.financials.shared.erpintegrationcore.utils.TestRestClientUtil.getRequestBuilder(TestRestClientUtil.java:131)
	at oracle.apps.financials.shared.erpintegrationcore.utils.TestRestClientUtil.testInvokePostRequestOnRestAPI(TestRestClientUtil.java:75)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

## Steps to reproduce
```Java
import jakarta.ws.rs.client.*;
import jakarta.ws.rs.core.HttpHeaders;
import jakarta.ws.rs.core.Response;

    @Test
    public void dummyTest() {
        Invocation.Builder request = getRequestBuilder(DUMMY_URL, DUMMY_PATH);
    }

    public Invocation.Builder getRequestBuilder(String url, String path) {
        Client client = ClientBuilder.newBuilder()
                .connectTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .build();
        WebTarget target = client.target(url).path(path);
        Invocation.Builder request = target.request();
        request.header(HttpHeaders.CONTENT_TYPE, application/json);
        return request;
    }
```

**Comment by barchetta** [comment]
This user was migrating from an earlier version of Helidon. Very possible dependencies are messed up.

**Comment by yyyyike** [comment]
{"logger":"com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder","message":"Attempt 6 - Rest call to get region from metadata service failed \norg.glassfish.hk2.api.MultiException: A MultiException has 4 exceptions.  They are:\n1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_5 for injection at SystemInjecteeImpl(requiredType=Tracer,parent=HelidonTelemetryClientFilter,qualifiers={},position=0,optional=false,self=false,unqualified=null,438660480)\n2. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_5 for injection at SystemInjecteeImpl(requiredType=OpenTelemetry,parent=HelidonTelemetryClientFilter,qualifiers={},position=1,optional=false,self=false,unqualified=null,1916139819)\n3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of io.helidon.microprofile.telemetry.HelidonTelemetryClientFilter errors were found\n4. java.lang.IllegalStateException: Unable to perform operation: resolve on io.helidon.microprofile.telemetry.HelidonTelemetryClientFilter\n\n\tat org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:249) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:387) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[hk2-locator-3.0.5.jar:?]\n\tat org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[hk2-utils-3.0.5.jar:?]\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]\n\tat org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[hk2-utils-3.0.5.jar:?]\n\tat org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[hk2-utils-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67) ~[hk2-locator-3.0.5.jar:?]\n\tat org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136) ~[jersey-hk2-3.1.5.jar:?]\n\tat java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]\n\tat java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1249) ~[?:?]\n\tat java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]\n\tat java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]\n\tat java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]\n\tat java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]\n\tat java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]\n\tat org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140) ~[jersey-hk2-3.1.5.jar:?]\n\tat org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30) ~[jersey-hk2-3.1.5.jar:?]\n\tat org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:300) ~[jersey-common-3.1.5.jar:?]\n\tat org.glassfish.jersey.internal.inject.Providers.getAllRankedProviders(Providers.java:183) ~[jersey-common-3.1.5.jar:?]\n\tat org.glassfish.jersey.internal.inject.Providers.getAllProviders(Providers.java:267) ~[jersey-common-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.ClientFilteringStages.createRequestFilteringStage(ClientFilteringStages.java:57) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.ClientRuntime.<init>(ClientRuntime.java:111) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:472) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317) ~[jersey-common-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:834) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.ClientRequest.getClientRuntime(ClientRequest.java:181) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.JerseyWebTarget.onBuilder(JerseyWebTarget.java:371) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:199) ~[jersey-client-3.1.5.jar:?]\n\tat org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:38) ~[jersey-client-3.1.5.jar:?]\n\tat com.oracle.bmc.http.client.jersey3.Jersey3HttpRequest.execute(Jersey3HttpRequest.java:233) ~[oci-java-sdk-common-httpclient-jersey3-3.18.0.jar:?]\n\tat com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.fetchRegion(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:366) [oci-java-sdk-common-3.18.0.jar:?]\n\tat com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.executeInstanceFallback(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:408) [oci-java-sdk-common-3.18.0.jar:?]\n\tat com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectEndpointUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:266) [oci-java-sdk-common-3.18.0.jar:?]\n\tat com.oracle.bmc.auth.AbstractFederationClientAuthenticationDetailsProviderBuilder.autoDetectUsingMetadataUrl(AbstractFederationClientAuthenticationDetailsProviderBuilder.java:253) [oci-java-sdk-common-3.18.0.jar:?]\n\tat com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider$InstancePrincipalsAuthenticationDetailsProviderBuilder.build(InstancePrincipalsAuthenticationDetailsProvider.java:102) [oci-java-sdk-common-3.18.0.jar:?]\n\tat oracle.apps.financials.shared.erpintegrationsutilities.common.OciClientManager.<init>(OciClientManager.java:42) [erp-integrations-utilities.jar:?]\n\tat oracle.apps.financials.shared.erpintegrationsutilities.common.OciObjectStorageManager.<init>(OciObjectStorageManager.java:53) [erp-integrations-utilities.jar:?]\n\tat oracle.apps.financials.shared.erpintegrationsutilities.common.OciObjectStorageManager.getInstance(OciObjectStorageManager.java:63) [erp-integrations-utilities.jar:?]\n\tat oracle.apps.financials.shared.erpintegrationsutilities.main.FileUploader.main(FileUploader.java:74) [erp-integrations-utilities.jar:?]\nCaused by: org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_5 for injection at SystemInjecteeImpl(requiredType=Tracer,parent=HelidonTelemetryClientFilter,qualifiers={},position=0,optional=false,self=false,unqualified=null,438660480)\n\tat org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:52) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:197) ~[hk2-locator-3.0.5.jar:?]\n\tat org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:214) ~[hk2-locator-3.0.5.jar:?]\n\t... 44 more\n","threadId":1,"threadName":"main","span-id":"0000000000000000","trace-id":"00000000000000000000000000000000"}

**Comment by tjquinno** [comment]
@yyyyike This is not a full reproducer. The code supplied does not compile, and beyond that without the `pom.xml` we have no idea of your environment.

We could help you better if you could please create an actual reproducer project and attach it.

**Comment by yyyyike** [comment]
Hi Tim, thanks for checking. 

This issue was resolved.

Root cause: 
In our dependency tree, we have transitive SE dependency "telemetry-jfr-helidon" introduced. Maven found this first over the MP dependency "telemetry-jfr-mp-helidon".  After excluding this SE dependency, code is running without issue.
