### ISSUE TITLE
`examples/webserver/streaming` fails to start

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8477]
## Environment Details
* Helidon Version: 4.0.6,  3.2.6, 2.6.6
* Helidon SE 
* JDK version: java 21.0.2 2024-01-16 LTS

----------

## Problem Description

If you build  `examples/webserver/streaming` and run it with `java -jar` it fails with:

```
# This is from Helidon 4.0.6 example
$ java -jar target/helidon-examples-webserver-streaming.jar
Exception in thread "main" java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:156)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:142)
	at java.base/java.nio.file.Path.of(Path.java:209)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at io.helidon.examples.webserver.streaming.StreamingService.<init>(StreamingService.java:45)
	at io.helidon.examples.webserver.streaming.Main.routing(Main.java:37)
	at io.helidon.webserver.WebServerConfigSupport$ListenerCustomMethods.routing(WebServerConfigSupport.java:158)
	at io.helidon.webserver.ListenerConfig$BuilderBase.routing(ListenerConfig.java:231)
	at io.helidon.examples.webserver.streaming.Main.main(Main.java:47)
```

Also, the README for the 4.x example looks wrong as it mentions `Subscriber<DataChunk>` and `Producer<DataChunk>`

And I wonder if it makes more sense for the file to come from the filesystem and not a (jar) resource.

**Comment by Captain1653** [comment]
PR for this issue was merged 3 weeks ago. The problem was solved. Should this issue be closed?
