### ISSUE TITLE
Deployed pod crash with "java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_1,1,1299612725) has been shut down" error

### ISSUE THREAD

**Issue by yyyyike** [helidon-io/helidon#8542]
Hi Team, we're trying to migrate from H3 MP to H4 MP. In the testing stage, sometimes pod crash with this error, the other times, pods are running fine; we didn't change any code between deployments, any pointer on what could cause this issue and how to debug it? Thanks!

`{"level":"INFO","logger":"org.jboss.weld.Bootstrap","message":"WELD-ENV-002001: Weld SE container STATIC_INSTANCE shut down","threadId":1,"threadName":"main","span-id":"0000000000000000","trace-id":"00000000000000000000000000000000"}
java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_1,1,1299612725) has been shut down
	at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2399)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1012)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:217)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$InjectionManagerInjectedCdiTarget.inject(CdiComponentProvider.java:680)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
	at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:321)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:260)
	at io.helidon.microprofile.server.ServerImpl.start(ServerImpl.java:78)
	at oracle.apps.financials.shared.erpintegration.main.Main.startServer(Main.java:145)
	at oracle.apps.financials.shared.erpintegration.main.Main.main(Main.java:64)`
	

Any points on what could cause this issue? Thanks

**Comment by ljnelson** [comment]
I'd like to confirm that I understand:

* The stack trace shows your program is starting.
* While the program is starting, an observer method that observes the `@Initialized(ApplicationScoped.class) Object x` event is being invoked.
* In order to invoke the observer method, CDI needs to create the "receiver" (the bean whose method it is). While CDI is attempting to create the receiver, it defers to HK2 for some reason that is probably wrong and bad, but I don't know (we never see HK2 issues because it doesn't handle injection in Helidon).
* HK2 reports that it was shut down, probably because Kubernetes sent the process a `SIGINT` and some shutdown hook somewhere running by definition on another thread fired and your program is in the process of dying
* You want to know why all of this is the case. (Obviously I can't tell you very much with just the information presented.)

Is that correct?

**Comment by yyyyike** [comment]
Hi Laird,

Yes, we're on Helidon 4.0.5 MP.

Turns out we didn't properly inject/initialize an object inside that class. So, instead of putting the object creation inside the observer method, having a constructor outside the observer method resolves the issue. 

Thanks
