### ISSUE TITLE
`/webclient/standalone` example builds OK but running the separate client as in the `README.md` fails

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#8589]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
The `/webclient/standalone` app builds and tests successfully, but it includes both a server and a client. When you start the server and then run the client per the instructions in the `README.md` file the client reports a failure in the redirection step.

## Steps to reproduce
In the `helidon-examples` repo clone:
```
cd examples/webclient/standalone
mvn clean package
java -jar target/helidon-examples-webclient-standalone.jar
```
Note the port number displayed (XXX).
In another terminal window:
```
java -cp "target/classes:target/libs/*" io.helidon.examples.webclient.standalone.ClientMain XXX
```
You get output with a few successes and then a failure at the redirection step:
```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalStateException: Follow redirection failed!
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.helidon.common.reactive.Awaitable.await(Awaitable.java:54)
	at io.helidon.examples.webclient.standalone.ClientMain.main(ClientMain.java:103)
Caused by: java.lang.IllegalStateException: Follow redirection failed!
	at io.helidon.examples.webclient.standalone.ClientMain.lambda$followRedirects$7(ClientMain.java:132)
```

**Comment by senivam** [comment]
fixed by [36](https://github.com/helidon-io/helidon-examples/pull/36)
