### ISSUE TITLE
Helidon 4.0.7: Parameters.first(String)  generates java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by hrstoyanov** [helidon-io/helidon#8710]
## Environment Details
* Helidon Version: 4.0.7
* Helidon SE 
* JDK version: 21.0.2
* OS: MacOS

The implementation of ```Parameters.first(String)```  has some issues: As it returns an optional value, it should never fail:

```java
       var content = req.content();
        if(content.hasEntity()){
            var params = content.as(Parameters.class);
            var q = params.first("q");
            if(q.isPresent()) {
                ...
            }
        }
```

... and here is the failure stack trace:

```java
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at io.helidon.common.parameters@4.0.7/io.helidon.common.parameters.ParametersMap.get(ParametersMap.java:70)
	at io.helidon.common.parameters@4.0.7/io.helidon.common.parameters.ParametersMap.first(ParametersMap.java:101)
```
If you follow the stack trace, you will see the problem. My current workaround is to convert to a Map:

```java
var content = req.content();
if(content.hasEntity()) {
     var params = content.as(Parameters.class).toMap();
      ...
}
```

**Comment by talios** [comment]
I hit something similar to this the other day and worked around it with:

```
var query = req.query();
if (!query.isEmpty() && query.get("period") instanceof String period) {
```

Having to check the `isEmpty` is kind-of a pain.  Tho the out-of-bounds you got seems worse.

**Comment by talios** [comment]
@hrstoyanov That works nicely - even better using `.as(Period::parse)` to map to the desired type. Much cleaner - cheers!

**Comment by tomas-langer** [comment]
Reason for this bug is that the implementation did not expect an empty list as a value in the map used to create it.
The place we introduced this (I think the only one) is in URI Query, where we handle the case of a parameter without a follow-up `=` as a name without a value - so `contains` returns true, but there is no value.
So we were missing a validation of the map for the assumption of the implementation, and a change once we decided to support it.
The only sloppiness I see here is the lack of test for a query parameter without a value...

**Comment by jbescos** [comment]
Merged

**Comment by jbescos** [comment]
I am running one test I have created:
```
    @Test
    public void testFormNoEntity() {
        try (Http1ClientResponse res = client.post("/form/content").request()) {
            Parameters received = res.as(Parameters.class);
            assertThat(received.first(NO_VALUE).isEmpty(), is(true));
        }
    }
```
And I am hitting the exception with the next stacktrace:
```
System Thread [[0x7ee4364d 0x4afac8ea] WebServer socket] (Suspended)	
	io.helidon.http.media.ReadableEntityBase$EmptyReadableEntity.as(java.lang.Class<T>) line: 255	
	io.helidon.webclient.tests.GreetService.formContent(io.helidon.webserver.http.ServerRequest, io.helidon.webserver.http.ServerResponse) line: 193	
	io.helidon.webclient.tests.GreetService$$Lambda.0x00007f02fc228250.handle(io.helidon.webserver.http.ServerRequest, io.helidon.webserver.http.ServerResponse) line: not available	
	io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.doRoute(io.helidon.webserver.ConnectionContext, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: 165	
	io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call() line: 124	
	io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call() line: 102	
	io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(io.helidon.webserver.ConnectionContext, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse, java.util.concurrent.Callable<java.lang.Void>) line: 75	
	io.helidon.webserver.http.Filters$FilterChainImpl.proceed() line: 121	
	io.helidon.webserver.security.SecurityContextFilter.filter(io.helidon.webserver.http.FilterChain, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: 88	
	io.helidon.webserver.http.Filters$FilterChainImpl.proceed() line: 119	
	io.helidon.webserver.observe.tracing.TracingObserver$TracingFilter$$Lambda.0x00007f02fc2c8f10.run() line: not available	
	io.helidon.common.context.Contexts.runInContext(io.helidon.common.context.Context, java.lang.Runnable) line: 117	
	io.helidon.webserver.observe.tracing.TracingObserver$TracingFilter.filter(io.helidon.webserver.http.FilterChain, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: 247	
	io.helidon.webserver.http.Filters$FilterChainImpl.proceed() line: 119	
	io.helidon.webserver.context.ContextRoutingFeature$$Lambda.0x00007f02fc2c1918.run() line: not available	
	io.helidon.common.context.Contexts.runInContext(io.helidon.common.context.Context, java.lang.Runnable) line: 117	
	io.helidon.webserver.context.ContextRoutingFeature.filter(io.helidon.webserver.http.FilterChain, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: 50	
	io.helidon.webserver.context.ContextRoutingFeature$$Lambda.0x00007f02fc222ee0.filter(io.helidon.webserver.http.FilterChain, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: not available	
	io.helidon.webserver.http.Filters$FilterChainImpl.proceed() line: 119	
	io.helidon.webserver.http.Filters.executeFilters(io.helidon.webserver.http.FilterChain) line: 87	
	io.helidon.webserver.http.Filters.lambda$filter$0(io.helidon.webserver.http.FilterChain) line: 83	
	io.helidon.webserver.http.Filters$$Lambda.0x00007f02fc2c14d8.call() line: not available	
	io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(io.helidon.webserver.ConnectionContext, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse, java.util.concurrent.Callable<java.lang.Void>) line: 75	
	io.helidon.webserver.http.Filters.filter(io.helidon.webserver.ConnectionContext, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse, java.util.concurrent.Callable<java.lang.Void>) line: 83	
	io.helidon.webserver.http.HttpRoutingImpl.route(io.helidon.webserver.ConnectionContext, io.helidon.webserver.http.RoutingRequest, io.helidon.webserver.http.RoutingResponse) line: 73	
	io.helidon.webserver.http1.Http1Connection.route(io.helidon.http.HttpPrologue, io.helidon.http.WritableHeaders<?>) line: 357	
	io.helidon.webserver.http1.Http1Connection.handle(java.util.concurrent.Semaphore) line: 194	
	io.helidon.webserver.ConnectionHandler.run() line: 165	
	io.helidon.webserver.ConnectionHandler(io.helidon.common.task.InterruptableTask<T>).call() line: 47	
	io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture<T>.run() line: 239	
	java.lang.VirtualThread.runWith(java.lang.Object, java.lang.Runnable) line: 341	
	java.lang.VirtualThread.run(java.lang.Runnable) line: 311	
	java.lang.VirtualThread$VThreadContinuation$1.run() line: 192	
	java.lang.VirtualThread$VThreadContinuation(jdk.internal.vm.Continuation).enter0() line: 320	
	jdk.internal.vm.Continuation.enter(jdk.internal.vm.Continuation, boolean) line: 312	
```
The exception is explicitly thrown in this line:
https://github.com/helidon-io/helidon/blob/61bfe3ec6de4abcbd3fd05ced2f702eff3377c35/http/media/media/src/main/java/io/helidon/http/media/ReadableEntityBase.java#L255

The question is whether we can return an empty value instead of failing. Lets wait for @tomas-langer to review it.
