### ISSUE TITLE
MicroProfile Config 3.1

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8724]
Upgrade MicroProfile Config to version 3.1

* [3.1 Specification](https://github.com/eclipse/microprofile-config/releases/tag/3.1)
* [Overview Slide](https://docs.google.com/presentation/d/1A3Hbr-O7QFepUP5M0X2hKfqFiO1PZgnBWWhMyovu9JU/edit#slide=id.p9)

**Comment by barchetta** [comment]
The [most significant change ](https://download.eclipse.org/microprofile/microprofile-config-3.1/microprofile-config-spec-3.1.html#release_notes_31)is clarifying precedence for sources when using profiles plus the addition of a new TCK test. When run against Helidon 4 this new test fails:

```
[INFO] Running TestSuite
[ERROR] Tests run: 373, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 10.437 s <<< FAILURE! - in TestSuite
[ERROR] org.eclipse.microprofile.config.tck.profile.OverrideConfigProfileTest.testConfigProfileWithDevAndOverride  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.AssertionError:

Expected: is "dummy"
     but: was "foo"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at org.eclipse.microprofile.config.tck.profile.OverrideConfigProfileTest.testConfigProfileWithDevAndOverride(OverrideConfigProfileTest.java:74)
```

**Comment by barchetta** [comment]
Our implementation is not correctly handling per property overriding precedence when config profiles ([spec](https://download.eclipse.org/microprofile/microprofile-config-3.1/microprofile-config-spec-3.1.html#_how_config_profile_works)) are used.  Note that this is not a change from 3.0 -- just a clarification.  And the test that is failing is a new test to verify the clarified behavior.

The proper behavior is that a profile-specific property only overrides the vanilla property per config source. Therefore if I specify the vanilla property in a config source with a high ordinal, it will trump any profile specific property from a config source at a lower level. Our implementation appears to always place a higher precedence on the profile-specific property.

**Comment by barchetta** [comment]
See also #8737
