### ISSUE TITLE
[4.0.10] Please stop using SnakeYml 2.0

### ISSUE THREAD

**Issue by hrstoyanov** [helidon-io/helidon#8981]
## Environment Details
* Helidon Version: 4.0.10
* Helidon SE or Helidon MP: SE
* JDK version: 22.01
* OS: MacOS
----------

## Problem Description

Please stop using SnakeYml 2.0 in Helidon SE 4 - **instead, switch to** [SnakeYml-Engine](https://github.com/snakeyaml/snakeyaml-engine?tab=readme-ov-file).

```
|    \--- io.helidon.config:helidon-config-yaml:4.0.10
|         +--- io.helidon.config:helidon-config:4.0.10 (*)
|         +--- io.helidon.common:helidon-common:4.0.10
|         \--- org.yaml:snakeyaml:2.0
```

SnakeYml requires **java.desktop** internal JDK module (via **java.beans** package dependency, it seems), which is quite inappropriate for server apps based on Helidon, especially if you want your Helidon container images to be small. Without including **java.desktop** module (via the jlink utility) in your container builds, one gets a nasty runtime surprise:

```java
Exception in thread "main" java.lang.NoClassDefFoundError: java/beans/IntrospectionException
	at org.yaml.snakeyaml@2.0/org.yaml.snakeyaml.representer.BaseRepresenter.getPropertyUtils(BaseRepresenter.java:234)
	at org.yaml.snakeyaml@2.0/org.yaml.snakeyaml.Yaml.initDumperOptions(Yaml.java:119)
	at org.yaml.snakeyaml@2.0/org.yaml.snakeyaml.Yaml.<init>(Yaml.java:111)
	at org.yaml.snakeyaml@2.0/org.yaml.snakeyaml.Yaml.<init>(Yaml.java:101)
	at io.helidon.config.yaml@4.0.10/io.helidon.config.yaml.YamlConfigParser.toMap(YamlConfigParser.java:117)
	at io.helidon.config.yaml@4.0.10/io.helidon.config.yaml.YamlConfigParser.parse(YamlConfigParser.java:101)
	at io.helidon.config@4.0.10/io.helidon.config.spi.ConfigParser.parse(ConfigParser.java:91)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.lambda$get$0(ConfigSourceRuntimeImpl.java:477)
	at java.base/java.util.Optional.map(Unknown Source)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.get(ConfigSourceRuntimeImpl.java:460)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourceRuntimeImpl$ParsableConfigSourceReloader.get(ConfigSourceRuntimeImpl.java:443)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourceRuntimeImpl.initialLoad(ConfigSourceRuntimeImpl.java:218)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourceRuntimeImpl.load(ConfigSourceRuntimeImpl.java:173)
	at io.helidon.config@4.0.10/io.helidon.config.ConfigSourcesRuntime.load(ConfigSourcesRuntime.java:153)
	at io.helidon.config@4.0.10/io.helidon.config.ProviderImpl.newConfig(ProviderImpl.java:90)
	at io.helidon.config@4.0.10/io.helidon.config.BuilderImpl.build(BuilderImpl.java:350)
	at io.helidon.config@4.0.10/io.helidon.config.BuilderImpl.build(BuilderImpl.java:53)
	at insbiz.webapp/insbiz.webapp.App.main(App.java:67)
Caused by: java.lang.ClassNotFoundException: java.beans.IntrospectionException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
```

**Comment by tomas-langer** [comment]
A bit of analysis:
- the good thing is that the engine does not have a package split
- the slightly worse thing is that we do need snake yaml with the full feature set for some of our features (such as OpenAPI), so we would end up with both on the classpath

Regarding CVEs reported against SnakeYAML (up to this point in time) - we have upgraded to latest version, we use safe constructor, we never use it to parse untrusted sources. As a result, we are not impacted by these "false positives" that are often triggered by tools. 

So even though I understand this issue (to limit the dependency to the stuff that is really required), it would also actually increase the surface of possible attacks, as we would depend on both the full library and the engine. I am hoping that eventually the engine will be used as a base for the full version - if that happens, we would get rid of all the negative effects of applying this change.

**Comment by Captain1653** [comment]
Looks like In [snakeyaml 2.3](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes) problem with `java.desktop` was solved. This change can be found [here](https://github.com/snakeyaml/snakeyaml/pull/12).

<img width="1125" alt="Image" src="https://github.com/user-attachments/assets/bc1ac745-d012-4b4c-9ace-bbd21c17cc78" />

After this [update to 2.4 in helidon](https://github.com/helidon-io/helidon/issues/9826) this issue can be closed. 

Did I miss something?

**Comment by rjeberhard** [comment]
@tomas-langer, I propose that we close this issue. I've verified that SnakeYAML 2.5 (the version in use on main) does not depend on the java.desktop module. Separately, I concur that there isn't a justification yet for moving to use snakeyaml-engine as the published benchmarks are the same and the dependencies are sufficiently similar.

**Comment by tomas-langer** [comment]
I am closing this issue, as there is nothing to do for now - the original  problem is gone (required `java.desktop`).
