### ISSUE TITLE
4.x  - Http1ConnectionCache polling races with socket monitor thread

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#9012]
## Environment Details
* Helidon Version: 4.0.10
* Helidon SE

----------

## Problem Description

When `Http1ConnectionCache` polls its queue to find reusable connections, there is no guaranty that the underlying socket monitor thread has successfully read one byte:

https://github.com/helidon-io/helidon/blob/e763230b9fe24d26f2761eee955168d3cab33a2e/webclient/http1/src/main/java/io/helidon/webclient/http1/Http1ConnectionCache.java#L134

`TcpClientConnection.isConnected()` uses `HelidonSocket.isConnected()` which is based on `IdleInputStream.closed`.

If `IdleInputStream.closed` is set to `false` after the call to `connection.isConnected()`, then we effectively hand-off a bad connection that fails on the first read.

---

### History

This bug has existed since the introduction of closed connection detection (#7398) and was made more apparent recently with the automatic drain of client response entities #8943.

Prior to #8943 client responses that didn't fully read the entity would result in closed connections, with automatic drain such code would attempt to reuse existing connections. 

---

### Example Scenario

An `HTTP1Client` instance is used to make a request, the server responds but closes the connection without the `Connection: close` header (E.g. unhandled exception).

The next client request fails at `Http1ClientRequest.request()`:

```
java.lang.RuntimeException: Exception in socket monitor thread.
	at io.helidon.common.socket.IdleInputStream.endIdle(IdleInputStream.java:126)
	at io.helidon.common.socket.IdleInputStream.read(IdleInputStream.java:71)
	at java.base/java.io.InputStream.read(InputStream.java:220)
	at io.helidon.common.socket.PlainSocket.get(PlainSocket.java:142)
	at io.helidon.common.socket.PlainSocket.get(PlainSocket.java:32)
	at io.helidon.common.buffers.DataReader.pullData(DataReader.java:81)
	at io.helidon.common.buffers.DataReader.ensureAvailable(DataReader.java:111)
	at io.helidon.common.buffers.DataReader.findNewLine(DataReader.java:367)
	at io.helidon.webclient.http1.Http1StatusParser.readStatus(Http1StatusParser.java:48)
	at io.helidon.webclient.http1.Http1CallChainBase.readResponse(Http1CallChainBase.java:218)
	at io.helidon.webclient.http1.Http1CallEntityChain.doProceed(Http1CallEntityChain.java:66)
	at io.helidon.webclient.http1.Http1CallChainBase.proceed(Http1CallChainBase.java:149)
	at io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:395)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeWithServices(Http1ClientRequestImpl.java:205)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.invokeRequestWithEntity(Http1ClientRequestImpl.java:195)
	at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:49)
	at io.helidon.webclient.http1.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:40)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.doSubmit(Http1ClientRequestImpl.java:111)
	at io.helidon.webclient.http1.Http1ClientRequestImpl.doSubmit(Http1ClientRequestImpl.java:37)
	at io.helidon.webclient.api.ClientRequestBase.validateAndSubmit(ClientRequestBase.java:452)
	at io.helidon.webclient.api.ClientRequestBase.submit(ClientRequestBase.java:266)
	at io.helidon.webclient.api.HttpClientRequest.doSubmit(HttpClientRequest.java:80)
	at io.helidon.webclient.api.ClientRequestBase.validateAndSubmit(ClientRequestBase.java:452)
	at io.helidon.webclient.api.ClientRequestBase.request(ClientRequestBase.java:257)
       // redacted
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.net.SocketException: Connection reset
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.helidon.common.socket.IdleInputStream.endIdle(IdleInputStream.java:122)
	... 95 more
Caused by: java.io.UncheckedIOException: java.net.SocketException: Connection reset
	at io.helidon.common.socket.IdleInputStream.handle(IdleInputStream.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1093)
	at io.helidon.common.socket.IdleInputStream.handle(IdleInputStream.java:110)
	... 3 more
```

---

### Potential Fix

A possible solution is to block for the monitor thread task in the cache polling loop instead of during the next read.

E.g.

```java
TcpClientConnection connection;
while ((connection = connectionQueue.poll()) != null) {
    if (connection.isConnected()) {
        try {
            HelidonSocket socket = connection.helidonSocket();
            socket.endIdle();
            if (socket.isConnected()) {
                break;
            }
            if (LOGGER.isLoggable(DEBUG)) {
                LOGGER.log(DEBUG, String.format("[%s] client connection closed %s",
                        connection.channelId(),
                        Thread.currentThread().getName()));
            }
        } catch (RuntimeException ex) {
            if (LOGGER.isLoggable(DEBUG)) {
                LOGGER.log(DEBUG,
                        String.format("[%s] client connection severed %s",
                                connection.channelId(),
                                Thread.currentThread().getName()),
                        ex);
            }
        }
    }
}
```

This solution exposes a new method `HelidonSocket.endIdle()` to block  for the monitor thread.

## Steps to reproduce

Here is a potential unit test in `webclient/tests/http1/src/test/java/io/helidon/webclient/http1/Http1ClientTest.java`:

```java
@Test
void testConnectionClosed() throws IOException {
    Future<?> serverFuture = null;
    try (ServerSocket serverSocket = new ServerSocket(0);
            ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor()) {

        // A server that accepts a single connection closed after a delay
        // The delay ensures that the closed connection detection is blocked upon when polling the cache
        serverFuture = executor.submit(() -> {
            try {
                Socket socket = serverSocket.accept();
                Thread.sleep(1000);
                socket.close();
            } catch (IOException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        });

        Http1ClientImpl client = (Http1ClientImpl) Http1Client.create();
        ClientRequestHeaders headers = ClientRequestHeaders.create(WritableHeaders.create());
        ClientUri uri = ClientUri.create().port(serverSocket.getLocalPort());
        Http1ConnectionCache cache = Http1ConnectionCache.create();

        Supplier<ClientConnection> supplier = () -> cache.connection(
                client, Duration.ZERO, null, Proxy.noProxy(), uri, headers, true);

        // get the 1st connection, and release it for re-use
        ClientConnection conn1 = supplier.get();
        conn1.releaseResource();

        // get the 2nd connection, it should create a new one
        // otherwise we get a "bad" connection
        ClientConnection conn2 = supplier.get();

        assertThat(conn1, is(not(conn2)));
    } finally {
        if (serverFuture != null) {
            serverFuture.cancel(true);
        }
    }
}
```

**Comment by romain-grecourt** [comment]
`Http1ConnectionCache.keepAliveConnection` does race against `IdleInputStream.closed` (via `HelidonSocket.isConnected`) by design.

Blocking on the monitor task in `Http1ConnectionCache.keepAliveConnection` only works when the connection is closed, if it's still connected the code will be blocked forever on a read.

There seems to be no realistic way to improve the closed connection detection mechanism without bad trade-offs.
E.g. Returning re-usable connections to the cache with a delay would increase the number of connections created.

Instead this design assumes a proper HTTP server that does not close a connection marked as `keepAlive`.
If a server does indeed close a keepAlive connection, the next request will fail because the connection is bad, blame the server, not the closed detection mechanism.

---

The scenario described above makes Helidon close the connection after sending a keepAlive response, this is server side bug.
