### ISSUE TITLE
OpenAPI and OpenAPI issue with Exception Mapper

### ISSUE THREAD

**Issue by botsteve** [helidon-io/helidon#9091]
## Environment Details
* Helidon Version: 4.0.10
* Helidon MP
* JDK version: 21.0.3
* OS: MacOS
* Docker version (if applicable):

----------

## Problem Description
The openapi and openapi/ui paths are not routed correctly when the paths start with the jax-rs application path.  This issue occurs only when an exception mapper is defined in order to catch the jax-rs WebApplicationException and return a formated response. 

## Steps to reproduce
Define an exception mapper: 
`java
@Provider
public class JerseyExceptionMapper implements ExceptionMapper<WebApplicationException> {
.....
}
`

Override the path properties to add the application-path prefix: 
`
mp:
  openapi:
    web-context: /test/openapi
    services:
      ui:
        web-context: /test/openapi/ui
`

Jax-RS app:
`
@ApplicationPath("/test")
`
> 2024.08.02 17:48:59 FINE io.helidon.webserver.http1.Http1LoggingConnectionListener.recv VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: [0x7f87696e 0x2709f449] recv prologue: HttpPrologue[protocol=HTTP, protocolVersion=1.1, method=GET, uriPath=/test/openapi, query=, fragment=]
2024.08.02 17:48:59 FINE io.helidon.webserver.http1.Http1LoggingConnectionListener.recv VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: [0x7f87696e 0x2709f449] recv headers: 
Accept: application/json,*/*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Cookie: Idea-ea554b41=d611476d-cfc1-4cf2-99c4-11f1e7d3e9a7; Writerside-f614e51d=477e4310-ed31-4509-a056-96f85d23d60f; Idea-ea554f01=5e3e9dd3-ec91-4cb7-828f-762b94735f61; userToken=49gv95visnwkkqireoj7nc; OAuth_Token_Request_State=d4a4fbf4-9534-43ad-a838-4e6893d019f4
Host: localhost:8081
Referer: http://localhost:8081/test/openapi/ui/index.html
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0
Connection: keep-alive
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
DNT: 1
Priority: u=4
Sec-Fetch-Dest: empty
2024.08.02 17:48:59 FINER io.helidon.microprofile.server.JaxRsService VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: [0x7f87696e 0x2709f449] Handling in Jersey started
2024.08.02 17:48:59 FINER org.glassfish.jersey.server.ServerRuntime$Responder VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: Starting mapping of the exception.
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
	at io.helidon.microprofile.server.JaxRsService.doHandle(JaxRsService.java:228)
	at io.helidon.microprofile.server.JaxRsService.lambda$handle$2(JaxRsService.java:185)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.microprofile.server.JaxRsService.handle(JaxRsService.java:185)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.doRoute(HttpRoutingImpl.java:165)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:124)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:102)
	at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:121)
	at io.helidon.webserver.observe.metrics.MetricsFeature.lambda$configureVendorMetrics$2(MetricsFeature.java:90)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.webserver.context.ContextRoutingFeature.filter(ContextRoutingFeature.java:50)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
	at io.helidon.webserver.http.Filters.executeFilters(Filters.java:87)
	at io.helidon.webserver.http.Filters.lambda$filter$0(Filters.java:83)
	at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
	at io.helidon.webserver.http.Filters.filter(Filters.java:83)
	at io.helidon.webserver.http.HttpRoutingImpl.route(HttpRoutingImpl.java:73)
	at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:357)
	at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:194)
	at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165)
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
	at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
2024.08.02 17:48:59 FINE org.glassfish.jersey.server.ServerRuntime$Responder VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: WebApplicationException (WAE) with no entity thrown and no ExceptionMappers have been found for this WAE. Response with status 404 is directly generated from the WAE.
jakarta.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
	at io.helidon.microprofile.server.JaxRsService.doHandle(JaxRsService.java:228)
	at io.helidon.microprofile.server.JaxRsService.lambda$handle$2(JaxRsService.java:185)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.microprofile.server.JaxRsService.handle(JaxRsService.java:185)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.doRoute(HttpRoutingImpl.java:165)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:124)
	at io.helidon.webserver.http.HttpRoutingImpl$RoutingExecutor.call(HttpRoutingImpl.java:102)
	at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:121)
	at io.helidon.webserver.observe.metrics.MetricsFeature.lambda$configureVendorMetrics$2(MetricsFeature.java:90)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.webserver.context.ContextRoutingFeature.filter(ContextRoutingFeature.java:50)
	at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119)
	at io.helidon.webserver.http.Filters.executeFilters(Filters.java:87)
	at io.helidon.webserver.http.Filters.lambda$filter$0(Filters.java:83)
	at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75)
	at io.helidon.webserver.http.Filters.filter(Filters.java:83)
	at io.helidon.webserver.http.HttpRoutingImpl.route(HttpRoutingImpl.java:73)
	at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:357)
	at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:194)
	at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165)
	at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47)
	at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
2024.08.02 17:48:59 FINEST org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: [DEBUG] Released scope instance Instance{id=abd9ea0c-8338-4208-8ab0-7ab8ac5ae919, referenceCounter=0, store size=0} on thread [0x7f87696e 0x2709f449] WebServer socket
2024.08.02 17:48:59 FINE io.helidon.cors.CorsSupportHelper VirtualThread[#86,[0x7f87696e 0x2709f449] WebServer socket]/runnable@ForkJoinPool-1-worker-9: Request RequestAdapterSe{path=/test/openapi, method=GET, headers=Accept: application/json,*/*

this happens only if i change the openapi and openapi/ui properties by adding as prefix the jersey application path. If i use the default values namely
`
mp.openapi.web-context=/openapi
mp.openapi.services.ui.web-context=/openapi/ui
`
or any other path for these properties that doesn’t start with the Application path , the issue doesn’t occur anymore and the NotFound exception is not thrown anymore since the response is reseted and rerouted next.

Related piece of code: https://github.com/helidon-io/helidon/blob/helidon-4.0.11/microprofile/server/src/main/java/io/helidon/microprofile/server/JaxRsService.java#L224-L246

**Comment by botsteve** [comment]
Hi @arjav-desai, any updates on this?

**Comment by botsteve** [comment]
Managed to apply a quick workaround with the related issue: https://github.com/helidon-io/helidon/issues/7959#issuecomment-2148368597
