### ISSUE TITLE
4.x: Intermittent test failure in `io.helidon.webserver.tests.http2.FlowControlTest`

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#9122]
io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInOut  Time elapsed: 0.402 s  <<< FAILURE!
java.lang.AssertionError: 

```
Expected: is "Helidon!!..."
but: was ""
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInOut(FlowControlTest.java:177)

io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInbound  Time elapsed: 30.003 s  <<< ERROR!
io.helidon.webclient.http2.StreamTimeoutException: No data received on stream 3 within the timeout PT30S
	at io.helidon.webclient.http2.StreamBuffer.poll(StreamBuffer.java:47)
	at io.helidon.webclient.http2.Http2ClientStream.readOne(Http2ClientStream.java:387)
	at io.helidon.webclient.http2.Http2ClientStream.readHeaders(Http2ClientStream.java:363)
	at io.helidon.webclient.http2.Http2CallChainBase.readResponse(Http2CallChainBase.java:188)
	at io.helidon.webclient.http2.Http2CallEntityChain.doProceed(Http2CallEntityChain.java:77)
	at io.helidon.webclient.http2.Http2CallChainBase.proceed(Http2CallChainBase.java:124)
	at io.helidon.webclient.api.ClientRequestBase.invokeServices(ClientRequestBase.java:406)
	at io.helidon.webclient.http2.Http2ClientRequestImpl.invokeWithServices(Http2ClientRequestImpl.java:177)
	at io.helidon.webclient.http2.Http2ClientRequestImpl.invokeEntity(Http2ClientRequestImpl.java:167)
	at io.helidon.webclient.http2.RedirectionProcessor.invokeWithFollowRedirects(RedirectionProcessor.java:60)
	at io.helidon.webclient.http2.Http2ClientRequestImpl.doSubmit(Http2ClientRequestImpl.java:104)
	at io.helidon.webclient.http2.Http2ClientRequestImpl.doSubmit(Http2ClientRequestImpl.java:30)
	at io.helidon.webclient.api.ClientRequestBase.validateAndSubmit(ClientRequestBase.java:463)
	at io.helidon.webclient.api.ClientRequestBase.request(ClientRequestBase.java:261)
	at io.helidon.webclient.http2.Http2ClientRequestImpl.request(Http2ClientRequestImpl.java:30)
	at io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInbound(FlowControlTest.java:189)
```

**Comment by danielkec** [comment]
Hard to reproduce
![image](https://github.com/user-attachments/assets/78bc2f06-2b41-4055-9d67-c3f96bec274b)

**Comment by tomas-langer** [comment]
This should now be closed in `main`

**Comment by danielkec** [comment]
Another occurrence of this intermittent happened in CI for PR #12065.

Failed job:
https://github.com/helidon-io/helidon/actions/runs/26853605359/job/79192008594?pr=12065

This was run attempt 1 for head SHA `74d1f998df2e9fcb94b46ac3875efe994b11ae0b`.

Relevant CI logs:

```text
Job: tests/core-windows
Step: Run ./.github/actions/common

mvn ${MVN_ARGS} \
  -DreactorRule=tests \
  -DmoduleSet=core \
  -Dsurefire.reportNameSuffix=windows \
  verify
```

```text
[INFO] Helidon WebServer Tests HTTP/2 ..................... FAILURE [ 40.781 s]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.0:test
[ERROR] on project helidon-webserver-tests-http2
```

Surefire report excerpt:

```text
Test set: io.helidon.webserver.tests.http2.FlowControlTest
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.47 s

io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInOut
Time elapsed: 30.071 s <<< ERROR!

java.util.concurrent.ExecutionException:
io.helidon.webclient.http2.StreamTimeoutException:
No data received on stream 1 within the timeout PT30S
    at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:124)
    at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:207)
    at io.helidon.webserver.tests.http2.FlowControlTest.awaitFirstBodyRead(FlowControlTest.java:195)
    at io.helidon.webserver.tests.http2.FlowControlTest.flowControlWebClientInOut(FlowControlTest.java:169)
Caused by: io.helidon.webclient.http2.StreamTimeoutException:
No data received on stream 1 within the timeout PT30S
    at io.helidon.webclient.http2.Http2ClientStream.readHeaders(Http2ClientStream.java:500)
    at io.helidon.webclient.http2.Http2CallOutputStreamChain$ClientOutputStream.sendHeader(Http2CallOutputStreamChain.java:266)
    at io.helidon.webclient.http2.Http2CallOutputStreamChain$ClientOutputStream.write(Http2CallOutputStreamChain.java:193)
```

The same workflow run was rerun at the same head SHA, and `tests/core-windows` passed on attempt 2:

```text
Job: tests/core-windows
Job id: 79255430372
FlowControlTest: Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.21 s
flowControlWebClientInOut: 0.319 s
```

So this still appears to occur intermittently in CI after the recent `main` fix/closure note.
