### ISSUE TITLE
MetaConfig is used implicitly when nothing is configured

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#9218]
## Environment Details
* Helidon Version: 4.1.0
* Helidon SE

----------

This issue is filed against 4.1.0, however the same can be observed with 3.2.8 and 2.6.7.

## Problem Description

When there are no config sources, meta config is used which leads to bad behaviors.

See https://github.com/helidon-io/helidon/blob/90274ad4359a74e61f685ddefd37f404398c74c7/config/config/src/main/java/io/helidon/config/BuilderImpl.java#L433

---

The javadoc of `Config.just` states:
> Creates a new Config loaded from the specified ConfigSources. No other sources will be included.

We'd expect `Config.just()` to create an empty instance.
However if there a file called `config-profile.yaml` or `meta-config.yaml` in the current directory it will be picked up.

This also occurs with code that is effectively similar to `Config.just`:

```java
Config.builder()
    .disableSystemPropertiesSource()
    .disableEnvironmentVariablesSource()
    .build();
```

---

When using Helidon MP with `-Dio.helidon.config.mp.meta-config=config-profile.yaml`, any code that builds an effectively empty SE config instance will load the file, however MP meta config and SE meta config are not compatible so this is guaranteed to fail.

E.g.
If there is no property prefixed with `metrics.` and `mp.metrics.` in the configuration, then `MetricsCdiExtension` will build a config instance with no config sources.

 https://github.com/helidon-io/helidon/blob/5bd8681d69278e910645dd71f32e6a021647cd80/microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java#L449

```
Exception in thread "main" java.lang.IllegalArgumentException: Config source of type properties is not supported. Supported types: [file, prefixed, classpath, system-properties, directory, inlined, url, environment-variables]
	at io.helidon.config.MetaProviders.lambda$configSource$7(MetaProviders.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config.MetaConfig.configSource(MetaConfig.java:201)
	at io.helidon.config.MetaConfig.lambda$configSources$1(MetaConfig.java:239)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.helidon.config.MetaConfig.lambda$configSources$2(MetaConfig.java:239)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.config.MetaConfig.configSources(MetaConfig.java:239)
	at java.base/java.util.Optional.map(Optional.java:260)
	at io.helidon.config.MetaConfig.configSources(MetaConfig.java:249)
	at io.helidon.config.BuilderImpl.buildConfigSources(BuilderImpl.java:434)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:334)
	at io.helidon.config.BuilderImpl.build(BuilderImpl.java:53)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.componentConfig(MetricsCdiExtension.java:458)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.configure(MetricsCdiExtension.java:551)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.registerService(MetricsCdiExtension.java:321)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:311)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:258)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
	at io.helidon.microprofile.cdi.CdiStartupProvider.start(CdiStartupProvider.java:39)
	at io.helidon.Main.main(Main.java:85)
```

## Steps to reproduce

```java
class ConfigEmptyTest {

    @Test
    void testJustEmpty() {
        Config config = Config.just();
        assertThat(config.get("foo").asString().orElse("bar"), is("bar"));
    }
    
    @Test
    void testDisableBuiltInSources() {
        Config config = Config.builder()
                .disableSystemPropertiesSource()
                .disableEnvironmentVariablesSource()
                .build();
        assertThat(config.get("foo").asString().orElse("bar"), is("bar"));
    }
}
```

src/test/resources/meta-config.yaml:

```yaml
sources:
  - type: "inlined"
    properties:
      foo: "not-bar"
```

**Comment by tomas-langer** [comment]
I am modifying the behavior of the builder to only use meta-configuration in case it is requested by the user.

There are two cases where this should happen:
1. when calling `Config.create()`
2. when calling `Config.builder.metaConfig()` 

All other cases will no longer use meta-configuration. This fixes all the problems described here.

**Comment by tomas-langer** [comment]
I am modifying the behavior of the builder to only use meta-configuration in case it is requested by the user.

There are two cases where this should happen:
1. when calling `Config.create()`
2. when calling `Config.builder.metaConfig()` 

All other cases will no longer use meta-configuration. This fixes all the problems described here.
