### ISSUE TITLE
4.x - GlobalConfig.config() should be configured when using Helidon MP

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#9220]
## Environment Details
* Helidon Version: 4.1.0
* Helidon MP

----------

## Problem Description

If not configured, `GlobalConfig` initializes a default config using `Config.create()` via `io.helidon.config.HelidonConfigProvider`.

`Config.create()` loads meta-config by default, if there a file called `config-profile.yaml` or `meta-config.yaml` in the current directory it will be picked up.

However MP meta config and SE meta config are not compatible so this is guaranteed to fail.

```
2024.08.28 17:09:40 INFO io.helidon.config.MetaConfigFinder Thread[#1,main,5,main]: Found meta configuration file: /private/tmp/quickstart-mp/meta-config.yaml
Exception in thread "main" java.lang.IllegalArgumentException: Config source of type properties is not supported. Supported types: [file, prefixed, classpath, system-properties, directory, inlined, url, environment-variables]
	at io.helidon.config.MetaProviders.lambda$configSource$7(MetaProviders.java:116)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config.MetaProviders.configSource(MetaProviders.java:116)
	at io.helidon.config.MetaConfig.configSource(MetaConfig.java:201)
	at io.helidon.config.BuilderImpl.lambda$config$3(BuilderImpl.java:378)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at io.helidon.config.BuilderImpl.lambda$config$4(BuilderImpl.java:378)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.common.mapper.OptionalValue.ifPresent(OptionalValue.java:188)
	at io.helidon.config.BuilderImpl.config(BuilderImpl.java:378)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.helidon.config.Config$Builder.metaConfig(Config.java:1639)
	at io.helidon.config.Config.create(Config.java:321)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.config.HelidonConfigProvider.create(HelidonConfigProvider.java:40)
	at io.helidon.common.config.GlobalConfig.lambda$static$0(GlobalConfig.java:49)
	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118)
	at io.helidon.common.config.GlobalConfig.config(GlobalConfig.java:73)
	at io.helidon.metrics.api.MetricsConfigSupport$BuilderDecorator.decorate(MetricsConfigSupport.java:85)
	at io.helidon.metrics.api.MetricsConfig$BuilderBase.preBuildPrototype(MetricsConfig.java:602)
	at io.helidon.metrics.api.MetricsConfig$Builder.buildPrototype(MetricsConfig.java:809)
	at io.helidon.metrics.api.MetricsConfig.create(MetricsConfig.java:86)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig$BuilderBase.<init>(MetricsObserverConfig.java:88)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig$Builder.<init>(MetricsObserverConfig.java:422)
	at io.helidon.webserver.observe.metrics.MetricsObserverConfig.builder(MetricsObserverConfig.java:46)
	at io.helidon.webserver.observe.metrics.MetricsObserver.builder(MetricsObserver.java:71)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.configure(MetricsCdiExtension.java:553)
	at io.helidon.microprofile.metrics.MetricsCdiExtension.registerService(MetricsCdiExtension.java:321)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$DefaultMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:144)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:126)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:311)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
	at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:258)
	at io.helidon.microprofile.cdi.Main.main(Main.java:80)
	at io.helidon.microprofile.cdi.CdiStartupProvider.start(CdiStartupProvider.java:39)
	at io.helidon.Main.main(Main.java:85)
```

---

Instead it should be configured with the MicroProfile config wrapped as a Helidon Config.

I.e.
```java
MpConfig.toHelidonConfig(ConfigProvider.getConfig());
```

## Steps to reproduce

```shell
# generate project
helidon init --version 4.1.0 --batch -Dflavor=mp -DappType=quickstart

# build
cd quickstart-mp
mvn clean install -DskipTests

# generate a MP meta-config file named meta-config.yaml
cat <<EOF > meta-config.yaml                                         
add-default-sources: true
sources:
  - type: "properties"
    optional: true
    path: "foo.properties"
EOF

# start the app with the meta config
java -Dio.helidon.config.mp.meta-config=meta-config.yaml -jar target/quickstart-mp.jar
```

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
