### ISSUE TITLE
Helidon gives internal server error for an invalid host header

### ISSUE THREAD

**Issue by balajirajan01** [helidon-io/helidon#9270]
## Environment Details
* Helidon Version: 4.0.8
* Helidon SE or Helidon MP : Helidon MP
* JDK version: jdk 21
* OS: 
* Docker version (if applicable):

----------

curl -v http://localhost:8080/api/v1/oci/secret/full -H 'Host: w.localhost:808a'

Stack trace - 

```
Internal server error io.helidon.http.RequestException: For input string: "808a"
    at io.helidon.http.RequestException$Builder.build(RequestException.java:139) ~[helidon-http-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.unhandledError(ErrorHandlers.java:203) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.lambda$handleError$1(ErrorHandlers.java:182) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at java.util.Optional.ifPresentOrElse(Optional.java:198) ~[?:?]
    at io.helidon.webserver.http.ErrorHandlers.handleError(ErrorHandlers.java:181) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:118) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.filter(Filters.java:83) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.HttpRoutingImpl.route(HttpRoutingImpl.java:73) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1Connection.route(Http1Connection.java:357) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1Connection.handle(Http1Connection.java:194) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.ConnectionHandler.run(ConnectionHandler.java:165) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.task.InterruptableTask.call(InterruptableTask.java:47) ~[helidon-common-task-4.0.8.jar:4.0.8]
    at io.helidon.webserver.ThreadPerTaskExecutor$ThreadBoundFuture.run(ThreadPerTaskExecutor.java:239) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at java.lang.VirtualThread.run(VirtualThread.java:329) ~[?:?]\nCaused by: java.lang.NumberFormatException: For input string: "808a"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
    at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
    at io.helidon.common.uri.UriBuilderSupport$UriInfoCustomMethods.authority(UriBuilderSupport.java:69) ~[helidon-common-uri-4.0.8.jar:4.0.8]
    at io.helidon.common.uri.UriInfo$BuilderBase.authority(UriInfo.java:115) ~[helidon-common-uri-4.0.8.jar:4.0.8]
    at io.helidon.http.RequestedUriDiscoveryContext$Builder$RequestedUriDiscoveryContextImpl.uriInfo(RequestedUriDiscoveryContext.java:344) ~[helidon-http-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1ServerRequest.createUriInfo(Http1ServerRequest.java:226) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118) ~[helidon-common-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http1.Http1ServerRequest.requestedUri(Http1ServerRequest.java:215) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.security.SecurityContextFilter.filter(SecurityContextFilter.java:63) ~[helidon-webserver-security-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.common.context.Contexts.runInContext(Contexts.java:117) ~[helidon-common-context-4.0.8.jar:4.0.8]
    at io.helidon.webserver.context.ContextRoutingFeature.filter(ContextRoutingFeature.java:50) ~[helidon-webserver-context-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters$FilterChainImpl.proceed(Filters.java:119) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.executeFilters(Filters.java:87) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.Filters.lambda$filter$0(Filters.java:83) ~[helidon-webserver-4.0.8.jar:4.0.8]
    at io.helidon.webserver.http.ErrorHandlers.runWithErrorHandling(ErrorHandlers.java:75) ~[helidon-webserver-4.0.8.jar:4.0.8]
```

Seems like it is not possible to intercept this call in the filters to validate the request. None of the ExceptionMappers are also getting called.

**Comment by tomas-langer** [comment]
You can add a filter that can handle such a request, but the bad header cannot be fixed - i.e. if the host header is not correct, you must return some kind of error message and cannot continue.

As in your stack trace we can see the problem comes from security feature, to be able to have a filter that gets to the information first, you need to create a feature that has higher weight than the security feature (which has a weight of `800`).
This is a Helidon WebServer feature, not a JAX-RS filter, so we must go a bit deeper level to handle this problem...

Implement the HTTP feature:
```java
  class CheckHostHeaderFeature implements HttpFeature, Weighted {
        @Override
        public void setup(HttpRouting.Builder routing) {
            routing.addFilter((chain, req, res) -> {
                try {
                    req.requestedUri();
                    chain.proceed();
                } catch (Exception e) {
                    throw new BadRequestException("Invalid host header", e);
                }
            });
        }

        @Override
        public double weight() {
            return 1000;
        }
    }
}
```

And then register the feature with the server:
```java
@ApplicationScoped
class myFeatureRegistrationBean {
        void register(@Observes @Initialized(ApplicationScoped.class) Object event, BeanManager bm) {
            bm.getExtension(ServerCdiExtension.class)
                    .serverRoutingBuilder()
                    .addFeature(new CheckHostHeaderFeature());
        }
}
```

**Comment by tomas-langer** [comment]
The problem is that the `Host` header is required by security. As it is invalid, security fails - and we return a 500, as this is not an expected state.
If there is a need to handle bad host headers in request, you can use a Helidon SE `HttpFeature` with a higher weight to return more appropriate response.

In MP, this would be achieved for example by adding the following bean to your project:
```java
@ApplicationScoped
    class CheckHostHeaderFeature implements HttpFeature, Weighted {
        void register(@Observes @Initialized(ApplicationScoped.class) Object event, BeanManager bm) {
            bm.getExtension(ServerCdiExtension.class)
                    .serverRoutingBuilder()
                    .addFeature(this); // add the feature to default HTTP routing of the webserver
        }
        @Override
        public void setup(HttpRouting.Builder routing) {
            routing.addFilter((chain, req, res) -> {
                try {
                    req.requestedUri(); // do validation of host header (this is just calling the method we know would fail)
                    chain.proceed();
                } catch (Exception e) {
                    throw new BadRequestException("Invalid host header", e);
                }
            });
        }

        @Override
        public double weight() {
            // security is 800, so this is sufficient
            return 1000;
        }
    }
```


Or in Helidon SE (you should remove the `@ApplicationScope` annotation and `register` method for SE):
```
routign.addFeature(new CheckHostHeaderFeature());
```

**Comment by al3xandru** [comment]
@tomas-langer according to https://www.rfc-editor.org/rfc/rfc7230#section-5.4

>   A server MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request message that lacks a Host header field and to any request message that contains more than one Host header field or a Host header field with an invalid field-value.

Would it make sense to return 400 instead of 500?

**Comment by tomas-langer** [comment]
Yes, we probably should validate the header earlier in processing, and fail immediately with a 400.

**Comment by tomas-langer** [comment]
I am working on a PR that will do a full validation of Host headers. 
The validation will be according to the spec (full validation).
