### ISSUE TITLE
Exception mapper did not get invoked when InternalServerErrorException was thrown from idcs-role-mapper or oidc security provider

### ISSUE THREAD

**Issue by wahuang** [helidon-io/helidon#9306]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.6.4
* Helidon SE or Helidon MP: Helidon MP
* JDK version: JDK 11
* OS: Generic Windows 11
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

For some special cases in security providers, we wanted to throw a custom exception, e.g., InternalServerErrorException so that in helidon MP application we can use an Exception Mapper to customize the response for such cases.
However, when InternalServerErrorException was thrown from idcs-role-mapper, the exception was somehow caught as Security Exception, so our custom Exception Mapper was never invoked. 

likewise, when InternalServerErrorException was thrown from oidc security provider, we could see from log that the exception was mapped by jersey InternalErrorMapper, and thus our custom Exception Mapper was never invoked either.

[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
Yes, the problem should be easily reproduced as described in the steps to reproduce section below

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

The problem can be easily reproduced by adding a throw statement to the enhance() method of idcs role mapper, as below

```
protected Single<Subject> enhance(ProviderRequest request,
            AuthenticationResponse previousResponse,
            Subject subject) {
...
new throw InternalServerErrorException("test custom internal server error");
}
```

or add the same to the authenticate() method of oidc security provider, as below

```
public CompletionStage<AuthenticationResponse> authenticate(ProviderRequest providerRequest) {
...
new throw InternalServerErrorException("test custom internal server error");
}
```
Here is the stack trace from oidc security provider
```
2024.09.30 13:41:36.872 FINE io.helidon.webserver.jersey.JerseySupport Thread[helidon-server-4,5,server]: Internal error thrown by Jersey
javax.ws.rs.InternalServerErrorException: TEST_EXCEPTION
	at io.helidon.security.providers.oidc.OidcCustomProvider.validateToken(OidcCustomProvider.java:773)
	at io.helidon.security.providers.oidc.OidcCustomProvider.authenticate(OidcCustomProvider.java:388)
	at io.helidon.security.AuthenticationClientImpl.authenticate(AuthenticationClientImpl.java:87)
	at java.base/java.util.Optional.map(Optional.java:265)
	at io.helidon.security.AuthenticationClientImpl.submit(AuthenticationClientImpl.java:47)
	at io.helidon.security.SecurityClient.get(SecurityClient.java:46)
	at io.helidon.security.SecurityClientBuilder.buildAndGet(SecurityClientBuilder.java:61)
	at io.helidon.security.integration.jersey.SecurityFilterCommon.processAuthentication(SecurityFilterCommon.java:182)
	at io.helidon.security.integration.jersey.SecurityFilterCommon.authenticate(SecurityFilterCommon.java:156)
	at io.helidon.security.integration.jersey.SecurityFilter.processSecurity(SecurityFilter.java:189)
	at io.helidon.security.integration.jersey.SecurityFilterCommon.doFilter(SecurityFilterCommon.java:132)
	at io.helidon.security.integration.jersey.SecurityFilter.filter(SecurityFilter.java:175)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:336)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
 
2024.09.30 13:41:36.876 FINER org.glassfish.jersey.server.ServerRuntime$Responder Thread[helidon-server-4,5,server]: Exception 'TEST_EXCEPTION' has been mapped by 'io.helidon.webserver.jersey.JerseySupport$InternalErrorMapper' to response 'Internal Server Error' (500:SERVER_ERROR). 
```

Below is the log when similar exception was thrown from idcs role mapper
`2024-10-01T01:11:41.924Z org.glassfish.jersey.server.ServerRuntime$Responder FINER 29468 Thread[helidon-1,5,helidon-thread-pool-1] Starting mapping of the exception. org.glassfish.
jersey.server.internal.process.MappableException: io.helidon.security.SecurityException: Failure while executing asynchronous security -> 	at org.glassfish.jersey.server.ContainerF
ilteringStage.apply(ContainerFilteringStage.java:110) -> 	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44) -> 	at org.glassfish.jersey.
process.internal.Stages.process(Stages.java:173) -> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:248) -> 	at org.glassfish.jersey.internal.Errors$1.call(E
rrors.java:248) -> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) -> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) -> 	at org.glassfish.jersey
.internal.Errors.process(Errors.java:274) -> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) -> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(
RequestScope.java:265) -> 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) -> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHand
ler.java:684) -> 	at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:336) -> 	at io.helidon.common.context.Contexts.runInContext(Contex
ts.java:117) -> 	at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154) -> 	at java.base/java.util.concurrent.ThreadPoolExecutor.run
Worker(ThreadPoolExecutor.java:1128) -> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) -> 	at java.base/java.lang.Thread.run(Thread.j
ava:834) -> Caused by: io.helidon.security.SecurityException: Failure while executing asynchronous security -> 	at io.helidon.security.SecurityResponse.get(SecurityResponse.java:66
) -> 	at io.helidon.security.SecurityClient.get(SecurityClient.java:46) -> 	at io.helidon.security.SecurityClientBuilder.buildAndGet(SecurityClientBuilder.java:61) -> 	at io.helido
n.security.integration.jersey.SecurityFilterCommon.processAuthentication(SecurityFilterCommon.java:182) -> 	at io.helidon.security.integration.jersey.SecurityFilterCommon.authentic
ate(SecurityFilterCommon.java:156) -> 	at io.helidon.security.integration.jersey.SecurityFilter.processSecurity(SecurityFilter.java:189) -> 	at io.helidon.security.integration.jers
ey.SecurityFilterCommon.doFilter(SecurityFilterCommon.java:132) -> 	at io.helidon.security.integration.jersey.SecurityFilter.filter(SecurityFilter.java:175) -> 	at org.glassfish.je
rsey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108) -> 	... 17 more -> Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.InternalServerErrorEx
ception: TEST_CUSTOM_EXCEPTION -> 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) -> 	at java.base/java.util.concurrent.Compl
etableFuture.get(CompletableFuture.java:2022) -> 	at io.helidon.security.SecurityResponse.get(SecurityResponse.java:62) -> 	... 25 more -> Caused by: javax.ws.rs.InternalServerErro
rException: TEST_CUSTOM_EXCEPTION -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperCustomProvider.checkSomething(IdcsMtRoleMapperCustomProvider.java:112
2) -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperCustomProvider.lambda$enhance$13(IdcsMtRoleMapperCustomProvider.java:372) -> 	at io.helidon.security.providers.c
ommon.EvictableCacheImpl.lambda$doComputeValue$5(EvictableCacheImpl.java:156) -> 	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) -> 	at io
.helidon.security.providers.common.EvictableCacheImpl.doComputeValue(EvictableCacheImpl.java:147) -> 	at io.helidon.security.providers.common.EvictableCacheImpl.computeValue(Evicta
bleCacheImpl.java:107) -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperCustomProvider.enhance(IdcsMtRoleMapperCustomProvider.java:372) -> 	at io.helidon.security.p
roviders.idcs.mapper.IdcsRoleMapperCustomProviderBase.lambda$map$2(IdcsRoleMapperCustomProviderBase.java:161) -> 	at io.helidon.common.reactive.SingleFlatMapSingle$FlatMapSubscribe
r.onNext(SingleFlatMapSingle.java:79) -> 	at io.helidon.common.reactive.SingleSubscription.request(SingleSubscription.java:50) -> 	at io.helidon.common.reactive.SingleFlatMapSingle
$FlatMapSubscriber.request(SingleFlatMapSingle.java:111) -> 	at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.request(MultiMapperPublisher.java:104) -> 	at io.he
lidon.common.reactive.SingleToFuture.onSubscribe(SingleToFuture.java:59) -> 	at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onSubscribe(MultiMapperPublisher.ja
va:62) -> 	at io.helidon.common.reactive.SingleFlatMapSingle$FlatMapSubscriber.onSubscribe(SingleFlatMapSingle.java:71) -> 	at io.helidon.common.reactive.SingleJust.subscribe(Singl
eJust.java:36) -> 	at io.helidon.common.reactive.SingleFlatMapSingle.subscribe(SingleFlatMapSingle.java:43) -> 	at io.helidon.common.reactive.SingleMapperPublisher.subscribe(Single
MapperPublisher.java:41) -> 	at io.helidon.common.reactive.CompletionSingle.toNullableStage(CompletionSingle.java:39) -> 	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:
118) -> 	at io.helidon.common.reactive.CompletionAwaitable.thenApply(CompletionAwaitable.java:50) -> 	at io.helidon.common.reactive.CompletionAwaitable.thenApply(CompletionAwaitabl
e.java:33) -> 	at io.helidon.security.AuthenticationClientImpl.mapSubject(AuthenticationClientImpl.java:66) -> 	at io.helidon.security.AuthenticationClientImpl.lambda$submit$1(Auth
enticationClientImpl.java:51) -> 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) -> 	at java.base/java.util.concurrent.Completable
Future.thenCompose(CompletableFuture.java:2235) -> 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143) -> 	at io.helidon.common.reactive.Co
mpletionAwaitable.thenCompose(CompletionAwaitable.java:236) -> 	at io.helidon.common.reactive.CompletionAwaitable.thenCompose(CompletionAwaitable.java:33) -> 	at io.helidon.securit
y.AuthenticationClientImpl.submit(AuthenticationClientImpl.java:50) -> 	... 25 more ->  ""
2024-10-01T01:11:41.926Z io.helidon.microprofile.server.JaxRsCdiExtension WARNING 29468 Thread[helidon-1,5,helidon-thread-pool-1] Internal server error io.helidon.security.Security
Exception: Failure while executing asynchronous security -> 	at io.helidon.security.SecurityResponse.get(SecurityResponse.java:66) -> 	at io.helidon.security.SecurityClient.get(Sec
urityClient.java:46) -> 	at io.helidon.security.SecurityClientBuilder.buildAndGet(SecurityClientBuilder.java:61) -> 	at io.helidon.security.integration.jersey.SecurityFilterCommon.
processAuthentication(SecurityFilterCommon.java:182) -> 	at io.helidon.security.integration.jersey.SecurityFilterCommon.authenticate(SecurityFilterCommon.java:156) -> 	at io.helido
n.security.integration.jersey.SecurityFilter.processSecurity(SecurityFilter.java:189) -> 	at io.helidon.security.integration.jersey.SecurityFilterCommon.doFilter(SecurityFilterComm
on.java:132) -> 	at io.helidon.security.integration.jersey.SecurityFilter.filter(SecurityFilter.java:175) -> 	at org.glassfish.jersey.server.ContainerFilteringStage.apply(Container
FilteringStage.java:108) -> 	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44) -> 	at org.glassfish.jersey.process.internal.Stages.proce
ss(Stages.java:173) -> 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:248) -> 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) -> 	at org.gl
assfish.jersey.internal.Errors$1.call(Errors.java:244) -> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) -> 	at org.glassfish.jersey.internal.Errors.process(Erro
rs.java:274) -> 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) -> 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) -> 	at
 org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235) -> 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684) -> 	at io.helid
on.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:336) -> 	at io.helidon.common.context.Contexts.runInContext(Contexts.java:117) -> 	at io.helido
n.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154) -> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.jav
a:1128) -> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) -> 	at java.base/java.lang.Thread.run(Thread.java:834) -> Caused by: java.u
til.concurrent.ExecutionException: javax.ws.rs.InternalServerErrorException: TEST_CUSTOM_EXCEPTION -> 	at java.base/java.util.concurrent.CompletableFuture.reportGet(Com
pletableFuture.java:395) -> 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022) -> 	at io.helidon.security.SecurityResponse.get(SecurityResponse.j
ava:62) -> 	... 25 more -> Caused by: javax.ws.rs.InternalServerErrorException: TEST_CUSTOM_EXCEPTION -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperC
ustomProvider.checkSomething(IdcsMtRoleMapperCustomProvider.java:1122) -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperCustomProvider.lambda$enhance$13(IdcsMtRoleM
apperCustomProvider.java:372) -> 	at io.helidon.security.providers.common.EvictableCacheImpl.lambda$doComputeValue$5(EvictableCacheImpl.java:156) -> 	at java.base/java.util.concurr
ent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908) -> 	at io.helidon.security.providers.common.EvictableCacheImpl.doComputeValue(EvictableCacheImpl.java:147) -> 	at io.heli
don.security.providers.common.EvictableCacheImpl.computeValue(EvictableCacheImpl.java:107) -> 	at io.helidon.security.providers.idcs.mapper.IdcsMtRoleMapperCustomProvider.enhance(I
dcsMtRoleMapperCustomProvider.java:372) -> 	at io.helidon.security.providers.idcs.mapper.IdcsRoleMapperCustomProviderBase.lambda$map$2(IdcsRoleMapperCustomProviderBase.java:161) ->
 	at io.helidon.common.reactive.SingleFlatMapSingle$FlatMapSubscriber.onNext(SingleFlatMapSingle.java:79) -> 	at io.helidon.common.reactive.SingleSubscription.request(SingleSubscri
ption.java:50) -> 	at io.helidon.common.reactive.SingleFlatMapSingle$FlatMapSubscriber.request(SingleFlatMapSingle.java:111) -> 	at io.helidon.common.reactive.MultiMapperPublisher$
MapperSubscriber.request(MultiMapperPublisher.java:104) -> 	at io.helidon.common.reactive.SingleToFuture.onSubscribe(SingleToFuture.java:59) -> 	at io.helidon.common.reactive.Multi
MapperPublisher$MapperSubscriber.onSubscribe(MultiMapperPublisher.java:62) -> 	at io.helidon.common.reactive.SingleFlatMapSingle$FlatMapSubscriber.onSubscribe(SingleFlatMapSingle.j
ava:71) -> 	at io.helidon.common.reactive.SingleJust.subscribe(SingleJust.java:36) -> 	at io.helidon.common.reactive.SingleFlatMapSingle.subscribe(SingleFlatMapSingle.java:43) -> 	
at io.helidon.common.reactive.SingleMapperPublisher.subscribe(SingleMapperPublisher.java:41) -> 	at io.helidon.common.reactive.CompletionSingle.toNullableStage(CompletionSingle.jav
a:39) -> 	at io.helidon.common.LazyValueImpl.get(LazyValueImpl.java:118) -> 	at io.helidon.common.reactive.CompletionAwaitable.thenApply(CompletionAwaitable.java:50) -> 	at io.heli
don.common.reactive.CompletionAwaitable.thenApply(CompletionAwaitable.java:33) -> 	at io.helidon.security.AuthenticationClientImpl.mapSubject(AuthenticationClientImpl.java:66) -> 	
at io.helidon.security.AuthenticationClientImpl.lambda$submit$1(AuthenticationClientImpl.java:51) -> 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Completabl
eFuture.java:1106) -> 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) -> 	at java.base/java.util.concurrent.CompletableFuture.thenComp
ose(CompletableFuture.java:143) -> 	at io.helidon.common.reactive.CompletionAwaitable.thenCompose(CompletionAwaitable.java:236) -> 	at io.helidon.common.reactive.CompletionAwaitabl
e.thenCompose(CompletionAwaitable.java:33) -> 	at io.helidon.security.AuthenticationClientImpl.submit(AuthenticationClientImpl.java:50) -> 	... 25 more ->  ""
2024-10-01T01:11:41.929Z org.glassfish.jersey.server.ServerRuntime$Responder FINER 29468 Thread[helidon-1,5,helidon-thread-pool-1] Exception 'Failure while executing asynchronous s
ecurity' has been mapped by 'io.helidon.microprofile.server.JaxRsCdiExtension$2' to response 'Internal Server Error' (500:SERVER_ERROR).  ""`

**Comment by spericas** [comment]
Could you please include more details about how your exception mapper is defined?

**Comment by wahuang** [comment]
Hi Santiago @spericas , please see sample code of exception mapper below. Thank you.

`@Provider
public class InternalServerErrorExceptionMapper implements ExceptionMapper<InternalServerErrorException>{

	Logger logger = Logger.getLogger(InternalServerErrorExceptionMapper.class.getName());


	@Override
	public Response toResponse(InternalServerErrorException e) {
		logger.log(Level.INFO, e.getMessage());

		return Response.status(INTERNAL_SERVER_ERROR)
				.entity(JSON.createObjectBuilder()
						.add("o:errorCode", "Internal Server Error")
						.add("status", INTERNAL_SERVER_ERROR.getStatusCode())
						.add("title", INTERNAL_SERVER_ERROR.getReasonPhrase())
						.add("detail", e.getMessage())
						.build())
				.build();
	}
}`

**Comment by spericas** [comment]
@wahuang The one in the role mapper is difficult to resolve, and likely works a designed at this time. The one in the security provider is a bit more interesting: it clearly matches the internal mapper provided by Helidon with a low USER + 1000 priority. I'm not quite sure why it is ignoring yours.  

Are you certain that your mapper is properly registered? Default priority should be USER which is higher. It should be possible to increase logging in package `io.helidon.microprofile.server` to verify if mapper is found.

**Comment by spericas** [comment]
Please see last comment @wahuang

**Comment by wahuang** [comment]
Hi Santiago @spericas , I enabled the logging as you advised like below,
`io.helidon.microprofile.server=FINEST`

but there are no additional logs between those logs entries that we found earlier. Did we miss anything?
```
2024.10.14 17:49:26.305 FINE io.helidon.webserver.jersey.JerseySupport Thread[helidon-server-1,5,server]: Internal error thrown by Jersey
javax.ws.rs.InternalServerErrorException: TEST_EXCEPTION
        at io.helidon.security.providers.oidc.OidcOhipProvider.validateToken(OidcOhipProvider.java:780)
        at io.helidon.security.providers.oidc.OidcOhipProvider.authenticate(OidcOhipProvider.java:388)
        at io.helidon.security.AuthenticationClientImpl.authenticate(AuthenticationClientImpl.java:87)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.helidon.security.AuthenticationClientImpl.submit(AuthenticationClientImpl.java:47)
        at io.helidon.security.SecurityClient.get(SecurityClient.java:46)
        at io.helidon.security.SecurityClientBuilder.buildAndGet(SecurityClientBuilder.java:61)
        at io.helidon.security.integration.jersey.SecurityFilterCommon.processAuthentication(SecurityFilterCommon.java:182)
        at io.helidon.security.integration.jersey.SecurityFilterCommon.authenticate(SecurityFilterCommon.java:156)
        at io.helidon.security.integration.jersey.SecurityFilter.processSecurity(SecurityFilter.java:189)
        at io.helidon.security.integration.jersey.SecurityFilterCommon.doFilter(SecurityFilterCommon.java:132)
        at io.helidon.security.integration.jersey.SecurityFilter.filter(SecurityFilter.java:175)
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
        at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
        at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
        at io.helidon.webserver.jersey.JerseySupport$JerseyHandler.lambda$doAccept$4(JerseySupport.java:336)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.common.context.ContextAwareExecutorImpl.lambda$wrap$7(ContextAwareExecutorImpl.java:154)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)
 "5cdef3e9-413a-395f-46be-8254d5b18e23"
2024.10.14 17:49:26.306 FINER org.glassfish.jersey.server.ServerRuntime$Responder Thread[helidon-server-1,5,server]: Exception 'TEST_EXCEPTION' has been mapped by 'io.helidon.webserver.jersey.JerseySupport$InternalErrorMapper' to response 'Internal Server Error' (500:SERVER_ERROR). "5cdef3e9-413a-395f-46be-8254d5b18e23"
2024.10.14 17:49:26.312 FINE io.helidon.webserver.BareResponseImpl Thread[helidon-server-1,5,server]: [Response: 124948812, Channel: 0xbf354c73, StreamID: N/A] Writing headers 500 Internal Server Error "5cdef3e9-413a-395f-46be-8254d5b18e23"
2024.10.14 17:49:26.313 FINEST io.helidon.webserver.RequestContext Thread[helidon-server-1,5,server]: Running in context helidon-cdi:42 "5cdef3e9-413a-395f-46be-8254d5b18e23"

```

**Comment by spericas** [comment]
Did you append `.level`? That is, `io.helidon.microprofile.server.level`?

**Comment by wahuang** [comment]
Hi Santiago @spericas , I fixed that property like below
`io.helidon.microprofile.server.level=FINEST`

but still no additional logs were generated

**Comment by spericas** [comment]
Could you extract a smaller reproducible that I can try? It may be easier that way.

**Comment by wahuang** [comment]
Hi Santiago @spericas , please see attached for minimal oidc security provider code to reproduce the error
[helidon-security-providers-oidc-cust.zip](https://github.com/user-attachments/files/17371088/helidon-security-providers-oidc-cust.zip)

security provider MP config as below
```
security.providers.0.abac=
security.providers.1.oidc-cust.client-id=client-id
security.providers.1.oidc-cust.client-secret=client-secret
security.providers.1.oidc-cust.identity-uri=https://idcs.identity.com
security.providers.1.oidc-cust.oidc-metadata-well-known=false
security.providers.1.oidc-cust.token-endpoint-uri=https://idcs.identity.com/oauth2/v1/token
security.providers.1.oidc-cust.authorization-endpoint-uri=https://idcs.identity.com/oauth2/v1/authorize
security.providers.1.oidc-cust.introspect-endpoint-uri=https://idcs.identity.com/oauth2/v1/introspect
security.providers.1.oidc-cust.issuer=https://identity.oraclecloud.com/
security.providers.1.oidc-cust.header-use=true
security.providers.1.oidc-cust.redirect=false
security.providers.1.oidc-cust.name=idcs-12345
```
Below is code snippet of  rest resource for testing

```
@Path("testcode/v1")
@RequestScoped
@SecurityScheme(securitySchemeName = "jwt", type = SecuritySchemeType.HTTP, scheme = "bearer", bearerFormat = "jwt")
public class TestResource {
	
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	@Authenticated(provider = "oidc-cust")
	@Path("/testoidc")
	public Response generateTestResponse(@HeaderParam("x-idheader") String idheader) {
		Response.ResponseBuilder rb = Response.status(Response.Status.OK)
                .entity(new TestResponseDto(idheader, "success"));
        return rb.build();
    }
	
	public static class TestResponseDto {
		private String idheader;
		private String responseMessage;
		
		public String getIdheader() {
			return idheader;
		}

		public void setIdheader(String idheader) {
			this.idheader = idheader;
		}

		public String getResponseMessage() {
			return responseMessage;
		}

		public void setResponseMessage(String responseMessage) {
			this.responseMessage = responseMessage;
		}

		TestResponseDto(String idheader, String msg) {
			this.idheader = idheader;
			responseMessage = msg;
		}		
	}
}
```
curl command to trigger the error
```
curl --location --request GET 'https://localhost:8080/testcode/v1/testoidc' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUVVNFUiIsImF1ZCI6Imh0dHBzOi8vaWRjcy5pZGVudGl0eS5vcmFjbGVjbG91ZC5jb20iLCJzdWJfdHlwZSI6InVzZXIiLCJpc3MiOiJodHRwczovL2lkZW50aXR5Lm9yYWNsZWNsb3VkLmNvbS8iLCJ0b2tfdHlwZSI6IkFUIiwicmVnaW9uX25hbWUiOiJ1cy1hc2hidXJuLWlkY3MtMSJ9.BvL9DhZUzrIjDlN0duf9US8hvkYkPk9wNtrk8pPAYzjY20cRxUGkHuFrLL-9cXbllOpw0aey0tCbMdjDJnj1Sg'
```

**Comment by spericas** [comment]
@wahuang Is there any chance you can provide a complete project? One that includes the test resource, the configuration you are using and the exact set of dependencies in your pom file? May help pin your exact problem; otherwise, I'd need to update all those parts myself, possibly changing the behavior.

**Comment by spericas** [comment]
@wahuang Your project had several problems. I made changes to it and verified that classes are discovered as expected if you include a `beans.xml` file and the appropriate annotations on the classes:

```
(~/Downloads/helidon-security-providers-oidc-cust) >> java -jar target/helidon-security-providers-oidc-cust.jar 
2024.10.22 13:00:49 INFO io.helidon.common.LogConfig Thread[#1,main,5,main]: Logging at initialization configured using classpath: /logging.properties
2024.10.22 13:00:49 FINEST io.helidon.microprofile.server.JaxRsCdiExtension Thread[#1,main,5,main]: Discovered @Provider class io.helidon.security.providers.oidc.InternalServerErrorExceptionMapper
2024.10.22 13:00:49 FINEST io.helidon.microprofile.server.JaxRsCdiExtension Thread[#1,main,5,main]: Discovered resource class io.helidon.security.providers.oidc.TestResource
2024.10.22 13:00:49 FINEST io.helidon.microprofile.server.Server Thread[#1,main,5,main]: Container context id: helidon-cdi
2024.10.22 13:00:49 INFO io.helidon.tracing.tracerresolver.TracerResolverBuilder Thread[#1,main,5,main]: TracerResolver not configured, tracing is disabled
2024.10.22 13:00:49 WARNING io.helidon.microprofile.tracing.TracingCdiExtension Thread[#1,main,5,main]: helidon-microprofile-tracing is on the classpath, yet there is no tracer implementation library. Tracing uses a no-op tracer. As a result, no tracing will be configured for WebServer and JAX-RS
2024.10.22 13:00:49 INFO io.helidon.microprofile.security.SecurityCdiExtension Thread[#1,main,5,main]: Authentication provider is missing from security configuration, but security extension for microprofile is enabled (requires providers configuration at key security.providers). Security will not have any valid authentication provider
2024.10.22 13:00:49 INFO io.helidon.microprofile.security.SecurityCdiExtension Thread[#1,main,5,main]: Authorization provider is missing from security configuration, but security extension for microprofile is enabled (requires providers configuration at key security.providers). ABAC provider is configured for authorization.
2024.10.22 13:00:49 FINER io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: Adding deferrable request KPI metrics context for routing with name '<unnamed>'
2024.10.22 13:00:49 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: Registering JAX-RS Application: HelidonMP
2024.10.22 13:00:49 FINEST io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: Application HelidonMP, class: javax.ws.rs.core.Application, contextRoot: Optional.empty, namedRouting: Optional.empty, routingNameRequired: false
2024.10.22 13:00:49 FINE io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: JAX-RS application HelidonMP registered on '/'
2024.10.22 13:00:49 INFO io.helidon.webserver.NettyWebServer Thread[#75,nioEventLoopGroup-2-1,10,main]: Channel '@default' started: [id: 0x410e4c93, L:/127.0.0.1:7001]
2024.10.22 13:00:49 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[#1,main,5,main]: Server started on http://localhost:7001 in 822 milliseconds (since JVM startup).
Started application on     http://localhost:7001
2024.10.22 13:00:49 INFO io.helidon.common.HelidonFeatures Thread[#76,features-thread,5,main]: Helidon MP 2.6.4 features: [CDI, Config, Fault Tolerance, Health, JAX-RS, Metrics, Open API, REST Client, Security, Server, Tracing]
```

First few lines at the top show discovery of exception mapper etc. Please work with the zip file that I'm attaching to see if the issue is reproducible.

[helidon-security-providers-oidc-cust-modified.zip](https://github.com/user-attachments/files/17479816/helidon-security-providers-oidc-cust-modified.zip)

**Comment by wahuang** [comment]
Thanks Santiago. We will work on it.

**Comment by spericas** [comment]
I'm closing this one because it's been inactive for a month. Let's reopen it if necessary.
