### ISSUE TITLE
4.x: test: LraDisabledDiscoveryResourceTest.testLraCompensate

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#9389]
Seen on helidon-4.1.x branch:

```
2024-10-14T16:18:11.2569645Z [INFO] Running io.helidon.microprofile.testing.lra.NonLraResourceTest
2024-10-14T16:18:13.2095294Z [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.946 s - in io.helidon.microprofile.testing.lra.NonLraResourceTest
2024-10-14T16:18:13.2101245Z [INFO] Running io.helidon.microprofile.testing.lra.LraDisabledDiscoveryResourceTest
2024-10-14T16:18:13.8506329Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.637 s <<< FAILURE! - in io.helidon.microprofile.testing.lra.LraDisabledDiscoveryResourceTest
2024-10-14T16:18:13.8509086Z [ERROR] io.helidon.microprofile.testing.lra.LraDisabledDiscoveryResourceTest.testLraCompensate  Time elapsed: 0.317 s  <<< FAILURE!
2024-10-14T16:18:13.8510604Z java.lang.AssertionError: 
2024-10-14T16:18:13.8510955Z 
2024-10-14T16:18:13.8511147Z Expected: is <Cancelled>
2024-10-14T16:18:13.8511646Z      but: was <Cancelling>
2024-10-14T16:18:13.8512458Z 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
2024-10-14T16:18:13.8513470Z 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
2024-10-14T16:18:13.8515173Z 	at io.helidon.microprofile.testing.lra.LraDisabledDiscoveryResourceTest.testLraCompensate(LraDisabledDiscoveryResourceTest.java:117)
2024-10-14T16:18:13.8517429Z 	at io.helidon.microprofile.testing.lra.LraDisabledDiscoveryResourceTest$Proxy$_$$_WeldClientProxy.testLraCompensate(Unknown Source)
```

**Comment by jbescos** [comment]
Is this still an issue?. I am running it in a loop and I don't get the error.
