### ISSUE TITLE
AddConfigBlock doesn't override prod config

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#9410]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: main

----------

## Problem Description
When production config file exists, it is possible to override it with:
```java
@AddConfig(key = "another.key", value = "test.value")
```

But `@AddConfigBlock` behaves differently and doesn't override existing properties.

## Steps to reproduce
```diff
diff --git a/microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java b/microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java
--- a/microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java	(revision d47f53aea182799c1da5f1172b8acf289a24b3a8)
+++ b/microprofile/tests/testing/junit5/src/test/java/io/helidon/microprofile/tests/testing/junit5/TestAddConfigBlockYaml.java	(date 1729174260197)
@@ -29,6 +29,8 @@
 
 @HelidonTest
 @AddConfigBlock(type = "yaml", value = """
+    another:
+      key: "test.value"
     another1:
       key: "another1.value"
     another2:
@@ -36,6 +38,10 @@
 """)
 class TestAddConfigBlockYaml {
 
+    @Inject
+    @ConfigProperty(name = "another.key")
+    private String another;
+
     @Inject
     @ConfigProperty(name = "another1.key")
     private String another1;
@@ -46,6 +52,7 @@
 
     @Test
     void testValue() {
+        assertThat(another, is("test.value"));
         assertThat(another1, is("another1.value"));
         assertThat(another2, is("another2.value"));
     }

diff --git a/microprofile/tests/testing/junit5/src/main/resources/application.yaml b/microprofile/tests/testing/junit5/src/main/resources/application.yaml
new file mode 100644
--- /dev/null	(date 1729174221128)
+++ b/microprofile/tests/testing/junit5/src/main/resources/application.yaml	(date 1729174221128)
@@ -0,0 +1,2 @@
+another:
+  key: "prod.value"
\ No newline at end of file
```

Result:
```
java.lang.AssertionError: 
Expected: is "test.value"
     but: was "prod.value"
Expected :test.value
Actual   :prod.value
<Click to see difference>


	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at io.helidon.microprofile.tests.testing.junit5.TestAddConfigBlockYaml.testValue(TestAddConfigBlockYaml.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by danielkec** [comment]
Workaround is adding `config_ordinal` to the block:
```
@AddConfigBlock(type = "yaml", value = """
    config_ordinal: 205
    another:
      key: "test.value"
```

**Comment by Captain1653** [comment]
It was interesting for me to find out the root cause of this bug. Maybe it helps somebody, somehow, but I'm not sure :) .

It turned out, that `@AddConfigSource` also doesn't work. 

Works as expected only `AddConfig`.

Overriding doesn't work for `@AddConfigBlock`, `@AddConfigSource` and (I believe) for `@Configuration`, because in `HelidonTestConfigSynthetic` test configurations are created as `normal` configs and they have default ordinal (100). That's why they can't override the default configuration from `META-INF/microprofile-config.properties`

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/fa4f10e7-736f-4152-93f0-2a1a3b3c2678" />

<br/><br/>

Workaround with `custom_ordinal` starts to work when `custom_ordinal`>=101. I checked it.

<br/><br/><br/><br/>

**Question:** `AddConfig` works. Why?
**Answer:** Properties from `AddConfig` are added directly to `Map` and this map has `config_ordinal=1000`, that's why it works as expected and overrides `META-INF/microprofile-config.properties`

<img width="1038" alt="Image" src="https://github.com/user-attachments/assets/139b997c-b366-45ec-979b-ee2a8cdfeb0a" />

**Thoughts**
1. Maybe all test configs should have higher priority?
2. What about priority between `@AddConfig`, `@AddConfigBlock`, `@AddConfigSource` and etc ? Which approach should have the highest ordinal?

**Comment by romain-grecourt** [comment]
It's working as-designed unless something that worked in 4.1.x stopped working in 4.2.x.

There is currently no API to define priority, the only mechanism is `config_ordinal`. Because `@AddConfig` is a key/value pair mechanism it cannot define `config_ordinal`, hence the hard-coded priority.

We could decide to add a priority API to all the annotations, however that should be considered be an improvement, not a bug.
